<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MagicAST.Query.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../libs/magic-ast/MagicAST.csproj" />
    <ProjectReference Include="../../libs/mast-query/MagicAST.Query.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="queries/**/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
