using System.Text;
using Flowthru.Step;
using MagicAtlas.Data._00_Config.Schemas;
using MagicAtlas.Data._03_Primary.Schemas;

namespace MagicAtlas.Flows.TagLabeling.Nodes;

/// <summary>
/// Folds <c>ScryfallTagCuration</c> into a tree by parsing the colon-delimited canonical
/// slugs (<c>removal:creature</c> nests under <c>removal</c>; <c>tribal:elf</c> nests under
/// <c>tribal</c>). Emits two siblings:
/// </summary>
/// <list type="number">
/// <item><see cref="TagHierarchyNode"/> tree (JSON) for downstream code that wants to reason
/// over the taxonomy as a tree.</item>
/// <item>Mermaid <c>flowchart</c> text for human-readable rendering in markdown / live editors.</item>
/// </list>
/// <remarks>
/// Synthesizes "ghost" parents for slugs that have children but no explicit curation entry
/// (e.g. if <c>removal:planeswalker</c> exists but no <c>removal:planeswalker</c> parent does,
/// it still attaches correctly under <c>removal</c>; if there's no <c>removal</c> entry either,
/// a ghost root is created). Ghost nodes are flagged so reporting can style them differently.
/// </remarks>
[FlowthruStep]
public static class BuildTagHierarchyNode
{
  public static Func<
    IEnumerable<ScryfallTagCanonical>,
    Task<(IEnumerable<TagHierarchyNode>, string)>
  > Create() =>
    canonicals => Task.FromResult(Build(canonicals.ToList()));

  internal static (IEnumerable<TagHierarchyNode>, string) Build(IReadOnlyList<ScryfallTagCanonical> canonicals)
  {
    // ── First pass: materialize a node per existing canonical, keyed by slug.
    var nodes = new Dictionary<string, TagHierarchyNode>();
    foreach (var c in canonicals)
    {
      nodes[c.CanonicalSlug] = new TagHierarchyNode
      {
        Slug = c.CanonicalSlug,
        Name = c.Name,
        Category = string.IsNullOrWhiteSpace(c.Category) ? null : c.Category,
        Description = string.IsNullOrWhiteSpace(c.Description) ? null : c.Description,
        AliasCount = c.Aliases.Count,
        IsGhost = false,
      };
    }

    // ── Second pass: walk every slug's prefix path and synthesize missing parents as ghosts
    // so an entry like `removal:planeswalker:exile` doesn't dangle when `removal:planeswalker`
    // isn't an explicit canonical.
    foreach (var slug in canonicals.Select(c => c.CanonicalSlug).ToList())
    {
      var segments = slug.Split(':');
      for (int i = 1; i < segments.Length; i++)
      {
        var ancestorSlug = string.Join(':', segments.Take(i));
        if (!nodes.ContainsKey(ancestorSlug))
        {
          nodes[ancestorSlug] = new TagHierarchyNode
          {
            Slug = ancestorSlug,
            Name = SegmentToTitle(segments[i - 1]),
            Category = null,
            Description = "(implicit parent — no explicit curation entry)",
            AliasCount = 0,
            IsGhost = true,
          };
        }
      }
    }

    // ── Third pass: link children to parents.
    var roots = new List<TagHierarchyNode>();
    foreach (var (slug, node) in nodes.OrderBy(kv => kv.Key, StringComparer.Ordinal))
    {
      var lastColon = slug.LastIndexOf(':');
      if (lastColon < 0)
      {
        roots.Add(node);
        continue;
      }
      var parentSlug = slug[..lastColon];
      nodes[parentSlug].Children.Add(node);
    }

    // Stable child ordering: real entries first (by AliasCount desc, name), then ghosts.
    SortChildren(roots);

    // ── Mermaid render.
    var mermaid = RenderMermaid(roots);
    return (roots.AsEnumerable(), mermaid);
  }

  private static void SortChildren(List<TagHierarchyNode> nodes)
  {
    nodes.Sort((a, b) =>
    {
      if (a.IsGhost != b.IsGhost) return a.IsGhost ? 1 : -1;
      var byAliases = b.AliasCount.CompareTo(a.AliasCount);
      return byAliases != 0 ? byAliases : string.CompareOrdinal(a.Name, b.Name);
    });
    foreach (var n in nodes) SortChildren(n.Children);
  }

  private static string SegmentToTitle(string segment)
  {
    if (string.IsNullOrEmpty(segment)) return segment;
    return string.Join(' ', segment.Split('-').Select(w =>
      w.Length == 0 ? w : char.ToUpperInvariant(w[0]) + w[1..]
    ));
  }

  private static string RenderMermaid(IReadOnlyList<TagHierarchyNode> roots)
  {
    var totalNodes = WalkAll(roots).Count();
    var realCount = WalkAll(roots).Count(n => !n.IsGhost);
    var ghostCount = totalNodes - realCount;

    var sb = new StringBuilder();
    // Markdown frontmatter so the file renders cleanly in GitHub / VS Code / IDE previewers.
    sb.AppendLine("# Scryfall Tag Hierarchy");
    sb.AppendLine();
    sb.AppendLine(
      $"Auto-generated by `BuildTagHierarchyNode` from `Catalog.ScryfallTagCuration`. " +
      $"{realCount} canonical{(realCount == 1 ? "" : "s")} ({ghostCount} synthetic parent{(ghostCount == 1 ? "" : "s")})."
    );
    sb.AppendLine();
    sb.AppendLine("```mermaid");
    sb.AppendLine("flowchart LR");
    sb.AppendLine();

    // Emit nodes. Quoting the slug as the node identifier lets Mermaid accept the canonical's
    // colon hierarchy verbatim (`"removal:creature"`) — no need to mangle to alphanumeric.
    foreach (var n in WalkAll(roots))
    {
      var nodeId = QuoteSlug(n.Slug);
      var label = n.IsGhost
        ? $"{EscapeLabel(n.Name)} (ghost)"
        : $"{EscapeLabel(n.Name)} ({n.AliasCount})";
      sb.AppendLine($"    {nodeId}[\"{label}\"]");
    }
    sb.AppendLine();

    // Emit edges.
    foreach (var parent in WalkAll(roots))
    {
      foreach (var child in parent.Children)
      {
        sb.AppendLine($"    {QuoteSlug(parent.Slug)} --> {QuoteSlug(child.Slug)}");
      }
    }
    sb.AppendLine();

    // Style ghosts distinctly.
    sb.AppendLine("    classDef ghost stroke-dasharray: 4 3, fill:#FAFAFA, color:#888");
    var ghostIds = WalkAll(roots).Where(n => n.IsGhost).Select(n => QuoteSlug(n.Slug)).ToList();
    if (ghostIds.Count > 0)
    {
      sb.AppendLine($"    class {string.Join(',', ghostIds)} ghost");
    }
    sb.AppendLine("```");
    return sb.ToString();
  }

  private static string QuoteSlug(string slug) => $"\"{slug}\"";

  private static IEnumerable<TagHierarchyNode> WalkAll(IEnumerable<TagHierarchyNode> roots)
  {
    foreach (var r in roots)
    {
      yield return r;
      foreach (var d in WalkAll(r.Children)) yield return d;
    }
  }

  private static string EscapeLabel(string s) =>
    s.Replace("\"", "&quot;").Replace("<", "&lt;").Replace(">", "&gt;");
}
