using System.Text.RegularExpressions;

namespace MagicAtlas.Ast.Tests.Flows.ArtifactCensus;

/// <summary>
/// The ADR-0004 §1 artifact classifier — the single, pure, filesystem-driven implementation shared by
/// the <c>ArtifactCensus</c> Flowthru flow (which writes the human-readable manifest) and the NUnit
/// classification gate (which asserts the invariant). Deliberately NOT a Flowthru step: a step would
/// bind the gate to a generated artifact, and the gate must hold on a clean checkout with no
/// <c>_08_Reporting</c> present.
/// </summary>
/// <remarks>
/// <para><b>The classification is derived, not stored.</b> ADR 0004's whole point is that a
/// hand-maintained claim <i>about</i> the data is the enemy, so every kind here is computed from a
/// structural fact about the repository:</para>
/// <list type="number">
///   <item><b>Catalog output</b> — the path is the <c>.AtPath(...)</c> target of a Flowthru catalog
///     item, i.e. a flow declares it as an output. <b>Derived</b>, definitively.</item>
///   <item><b>Reporting layer</b> — the path lives under a <c>Data/_08_Reporting/</c> directory.
///     <b>Derived</b> by the project's own layering convention.</item>
///   <item><b>Gold convention</b> — the path lives under a hand-authored fixture directory
///     (<c>HandParsedCards</c>, <c>Interactions/golds</c>, …). <b>Evidence</b>.</item>
///   <item><b>Named writer</b> — a product source file writes this exact filename: the target
///     expression of a write call resolves to the literal through the file's local path symbols.
///     <b>Derived</b> — this is how frozen computations (snapshots, expectation pins) are caught.</item>
///   <item><b>Generated sibling</b> — the filename never appears literally in any source file, but the
///     full directory path it lives in is reconstructed from a regenerator's write target. Catches
///     computed-filename snapshot families (<c>Slug(name) + ".json"</c>). <b>Derived</b>.</item>
/// </list>
/// <para>Anything that survives all five is <b>needs-human-classification</b>. That is a success
/// state, not a failure — but it must be <i>acknowledged</i>: see
/// <see cref="AcknowledgedAmbiguous"/>, the one hand-maintained table in this file, and
/// <see cref="HumanRulings"/>, which is where an acknowledgment goes to die once a human rules on it.
/// The gate is stateless: <i>every discovered artifact is either resolved by a rule above or carries
/// an explicit acknowledgment</i>. It is not a count and it does not ratchet.</para>
/// </remarks>
public static class ArtifactClassifier
{
  public const string Evidence = "Evidence";
  public const string Derived = "Derived";
  public const string ArchitecturalDecision = "architectural-decision";
  public const string NeedsHuman = "needs-human-classification";

  // ── Scan roots (ADR-0004 issue scope, plus the roots the census itself surfaced) ─────────────────

  /// <summary>The declared artifact surface. Each root is scanned recursively; a missing root is
  /// reported as absent rather than silently skipped (a generated-and-gitignored root such as
  /// <c>_08_Reporting</c> is legitimately empty on a clean checkout).</summary>
  public static readonly IReadOnlyList<ScanRoot> ScanRoots =
  [
    new("tests/magic-ast-tests/Fixtures", "NUnit fixture surface (issue scope: tests/**/Fixtures)"),
    new("tests/magic-ast-tests/Data/_08_Reporting", "Flowthru reporting layer (issue scope: **/Data/_08_Reporting)"),
    new("libs/atlas-flows/Data/_08_Reporting", "Flowthru reporting layer (issue scope: **/Data/_08_Reporting)"),
    new("dumps", "External bulk-data drop (issue scope: dumps/)"),
    new("libs", "Library data files (issue scope: libs/**/*.json)", JsonOnly: true),
    // Surfaced BY the census, not named by the issue: committed snapshot families sit outside
    // Fixtures/ entirely, and a snapshot regenerated by UPDATE_SNAPSHOTS=1 is the ADR's canonical
    // "looks like Evidence, is actually Derived" case.
    new("tests/magic-ast-tests/Tests", "Committed test-adjacent data (snapshots) — surfaced by the census, not by the issue scope"),
    new("tests/atlas-flow-test", "Second test project's data surface — surfaced by the census"),
  ];

  /// <summary>Directory segments never scanned: build output, dependency trees, VCS, agent worktrees,
  /// and Flowthru's own memoization cache (runtime state, not an artifact).</summary>
  private static readonly string[] ExcludedSegments =
  [
    "/bin/", "/obj/", "/node_modules/", "/.git/", "/.flowthru/", "/.venv/", "/__pycache__/",
    "/.http-cache/", "/.claude/worktrees/", "/Metadata/",
  ];

  // ── Named exclusions: files inside a scan root that are not data artifacts at all ────────────────

  /// <summary>Explicitly named, reported (never silent) exclusions. Each carries the rule that
  /// excluded it so the manifest shows what was set aside and why.</summary>
  public static string? ExclusionRule(string repoRelPath)
  {
    var name = Path.GetFileName(repoRelPath);
    var ext = Path.GetExtension(repoRelPath).ToLowerInvariant();

    if (ext is ".cs" or ".py" or ".ts" or ".tsx" or ".js" or ".sh" or ".csproj" or ".props" or ".targets" or ".lscache" or ".toml" or ".lock")
      return "Source";
    if (ext is ".md")
      return "Documentation";
    if (name is "project.json" or "appsettings.json" or "appsettings.Local.json" or "package.json" or "tsconfig.json" or "nx.json")
      return "BuildConfiguration";
    if (name is ".gitkeep" or ".gitignore" or ".DS_Store")
      return "VcsPlumbing";
    return null;
  }

  // ── Convention rules ─────────────────────────────────────────────────────────────────────────────

  /// <summary>Directories whose contents are hand-authored primary observation by construction —
  /// ADR 0004 §1 Evidence. These are the loop's irreducible seed (ADR 0003 §8).</summary>
  private static readonly (string Prefix, string Why)[] EvidenceDirectories =
  [
    ("tests/magic-ast-tests/Fixtures/HandParsedCards/", "hand-parsed gold AST (MAST parse Evidence)"),
    ("tests/magic-ast-tests/Fixtures/KeywordExpansions/", "hand-authored keyword-expansion gold"),
    ("tests/magic-ast-tests/Fixtures/MalformedParsedCards/", "hand-authored negative-case gold"),
    ("tests/magic-ast-tests/Fixtures/FilterRelations/", "hand-authored filter-relation gold"),
    ("tests/magic-ast-tests/Fixtures/Query/", "hand-authored query conformance/reference gold"),
    ("tests/magic-ast-tests/Fixtures/Interactions/golds/", "hand-authored interaction gold (ADR 0003 §8)"),
  ];

  /// <summary>A path segment that marks the Flowthru reporting layer. Everything a reporting layer
  /// holds is by definition a flow output.</summary>
  private const string ReportingSegment = "/Data/_08_Reporting/";

  /// <summary>
  /// Directories whose contents are wholly machine-generated under computed filenames, so no
  /// per-file rule could ever see them (a snapshot named <c>Slug(sentinel.Name) + ".json"</c> appears
  /// in no source file). <b>Two-key</b>: a directory only counts when it is named here AND the source
  /// index independently confirms a regenerator writes into it — the name alone cannot promote
  /// anything, and <c>Generated_directories_are_confirmed_by_source</c> fails if the confirmation
  /// stops holding.
  /// </summary>
  /// <remarks>
  /// Inferring this purely from source was tried and was wrong in both directions: reconstructing the
  /// write target's directory promotes everything directly under <c>Fixtures/</c>, because
  /// <c>GoldSpanReserializeUtility</c> legitimately rewrites golds in place from a
  /// <c>fixturesRoot</c> symbol. Rather than keep tuning a heuristic that silently marks hand-authored
  /// fixtures as generated, the directory is named and the machine checks the name.
  /// </remarks>
  public static readonly IReadOnlyDictionary<string, string> GeneratedDirectories =
    new Dictionary<string, string>(StringComparer.Ordinal)
    {
      ["tests/magic-ast-tests/Tests/Interaction/Snapshots"] =
        "PortWalkSentinelSnapshotTest.Regenerate_snapshots writes one canonical pipeline snapshot per "
        + "sentinel, named Slug(sentinel.Name) + \".json\" — a frozen computation, Derived by ADR 0004 "
        + "§1 despite being committed. Files in here whose names DO appear in source (the sentinels.json "
        + "manifest, captures-accepted-pairs.txt) are classified on their own merits.",
    };

  // ── The two hand-maintained tables. Keep them SMALL; see the class remarks. ──────────────────────

  /// <summary>
  /// <b>HAND-MAINTAINED (1 of 2).</b> Human rulings that override the derived classification. Every
  /// entry must name the ruling's basis. This table exists so that resolving an ambiguity is a code
  /// review, not a silent data edit — and so it stays visibly small. Empty is the healthy state.
  /// </summary>
  public static readonly IReadOnlyDictionary<string, (string Kind, string Basis)> HumanRulings =
    new Dictionary<string, (string, string)>(StringComparer.Ordinal)
    {
      ["tests/magic-ast-tests/Fixtures/CardAtlas/sac-fixture.json"] = (
        Evidence,
        "RULED 2026-07-20. The census originally flagged this as a frozen slice of D1-D4 OUTPUT needing a "
          + "regenerator. That reading was wrong: reading CardAtlasContractTests shows the file is an "
          + "INPUT — five cards' oracle text plus three combo definitions, fed INTO the pipeline steps, "
          + "with the test asserting invariants on the computed result. So there is no computation frozen "
          + "here and no regenerator is owed. What the file records is a human's SELECTION ('these cards "
          + "exercise the contract'), which nothing derives and nothing should — Evidence. Its oracle-text "
          + "CONTENT is copied from Scryfall rather than authored, and that half is now gated byte-exact "
          + "by SacFixtureOracleFidelityTests, closing the drift the Suture Priest fix (295f3506) hit in "
          + "the parse-track golds."
      ),
    };

  /// <summary>
  /// <b>HAND-MAINTAINED (2 of 2) — the gate's whitelist.</b> Artifacts the classifier could not
  /// resolve, each with the reason it is genuinely ambiguous. This is an explicit named membership
  /// set, never a count: adding a new unclassified artifact fails the build because it is <i>not in
  /// this set</i>, not because a number went up. Entries leave by being ruled on (moved to
  /// <see cref="HumanRulings"/> or given a regeneration path), never by being tolerated.
  /// </summary>
  public static readonly IReadOnlyDictionary<string, string> AcknowledgedAmbiguous =
    new Dictionary<string, string>(StringComparer.Ordinal)
    {
      // ── Fixtures/ root: the parse-track whitelists and pins ─────────────────────────────────────
      ["tests/magic-ast-tests/Fixtures/edge-diff-expected.json"] =
        "Carve-out list consumed by tools/gate-corpus-edge-diff.sh. Its ENTRIES are hand-added when a "
        + "batch legitimately reprojects a non-target card — but each entry is a frozen claim about a "
        + "cross-card reprojection that the corpus could invalidate. Evidence (a human's ruling that "
        + "this diff was intended) or a Derived expectation pin (recomputable from the batch diff)?",
      ["tests/magic-ast-tests/Fixtures/fidelity-uncovered-allowlist.json"] =
        "Allowlist read by GoldOracleTextFidelityTests. Hand-added, but every entry asserts 'this gold's "
        + "oracle text is legitimately uncoverable', which is a claim about the parser/corpus state — the "
        + "ADR's named failure shape (known-coarse-projections.json). Should likely become asserted-absence "
        + "golds (§1) rather than be classified.",
      ["tests/magic-ast-tests/Fixtures/oracle-text-quarantine.json"] =
        "Named directly in ADR 0004's Context table as one of the four failure artifacts (the "
        + "quarantine↔combo-tier JOIN that was never wrong, merely disconnected). Hand-maintained "
        + "shrink-only quarantine; its classification is entangled with issue #24's join work.",
      ["tests/magic-ast-tests/Fixtures/whitelist-freetext.json"] =
        "Hand-curated parser free-text whitelist. No product-source writer; the only regeneration path is "
        + "an agent skill script (.claude/skills/mast-tdd-loop), which is agent tooling, not the product's "
        + "derivation path. Evidence-shaped (a human ruling) but content-wise a claim about parser state.",
      ["tests/magic-ast-tests/Fixtures/whitelist-unparsed.json"] =
        "Same shape as whitelist-freetext.json — hand-curated, agent-script-appended, asserts a claim "
        + "about current parser coverage rather than recording a primary observation.",

      // ── Fixtures/Interactions: the ADR 0003 Stage 0b retirement backlog ──────────────────────────
      ["tests/magic-ast-tests/Fixtures/Interactions/known-families.json"] =
        "ADR 0003 Stage 0b calls for its retirement once witnessed, but it is STILL LOADED by "
        + "InteractionTriageFlow (Program.cs knownFamiliesPath -> LabelEdgesStep) and still gated by "
        + "PortGraphEngineTest's grammar-figure guard. Live input, scheduled for death: classifying it "
        + "either way pre-empts the retirement decision.",
      ["tests/magic-ast-tests/Fixtures/Interactions/families.json"] =
        "ORPHAN. No product source references it (only ADRs 0002/0003/0004, an agent definition, and a "
        + "2026-06-02 judgment doc). It is the pre-ADR-0003 abstract family grammar, superseded by the "
        + "rollup. Ambiguous only in that it may be deletable rather than classifiable.",
      ["tests/magic-ast-tests/Fixtures/Interactions/blood-artist-engine.json"] =
        "ORPHAN, and provably absorbed: golds/ruthless-knave-x-blood-artist.json records "
        + "source.absorbed_from = 'Fixtures/Interactions/blood-artist-engine.json'. The Evidence it "
        + "carried now lives in a gold; the file itself is a residue. Deletion candidate, not a "
        + "classification.",
      ["tests/magic-ast-tests/Fixtures/Interactions/topology-scaffold.json"] =
        "UPDATED 2026-07-20 (ADR-0004 §7, issue #26): the conflation this entry described is GONE. The "
        + "four sections that made the file simultaneously a declared input and a stale derived claim — "
        + "stems_representative, aliases, attribute_axes, and the archetypal frozen computation holes{} "
        + "('the report WAS the bug') — are deleted, and port-topology.json is now 100% witness-derived. "
        + "What remains is genuinely mixed in KIND, which is why it is still not classifiable as one thing: "
        + "kinds/supergroups/event_verbs_no_supergroup are architectural rulings a gold cannot witness "
        + "(ADR 0004 §1 routes those to ADR prose, but the generator has to consume them as data), while "
        + "connectivity_predictions and reject are awaiting conversion to executable sweeps (#27) and "
        + "asserted-absence golds (#28). The file is a transit lounge, not a category.",

      // ── Fixtures/Interactions/cards ─────────────────────────────────────────────────────────────
      ["tests/magic-ast-tests/Fixtures/Interactions/cards/BloodArtist.json"] = InteractionCardReason,
      ["tests/magic-ast-tests/Fixtures/Interactions/cards/Chatterfang.json"] = InteractionCardReason,
      ["tests/magic-ast-tests/Fixtures/Interactions/cards/PitilessPlunderer.json"] = InteractionCardReason,
      ["tests/magic-ast-tests/Fixtures/Interactions/cards/RuthlessKnave.json"] = InteractionCardReason,

      // ── Test-adjacent snapshots ─────────────────────────────────────────────────────────────────
      ["tests/magic-ast-tests/Tests/Interaction/Snapshots/sentinels.json"] =
        "The snapshot MANIFEST — the hand-curated list of which cards/combos get a pipeline snapshot. Not "
        + "written by Regenerate_snapshots (which only writes the slug files it enumerates). Evidence-like "
        + "in that a human chose the sentinels, but it records a coverage decision, not an observation "
        + "about Magic.",

      // ── libs/magic-ast/schema ───────────────────────────────────────────────────────────────────
      ["libs/magic-ast/schema/discriminator-justifications.json"] =
        "Hand-written prose justifying why two near-duplicate discriminators must both exist. UPDATED "
        + "2026-07-20: no longer 'a justification string that nothing checks' — with discriminator-"
        + "baseline.json retired, this file is the explicit named whitelist for the now-stateless lint, "
        + "read by DiscriminatorNearDuplicateTests in the CORE ring, which also fails on a DEAD entry "
        + "(one whose pair no longer near-collides) so it cannot rot the way the baseline did. Still "
        + "ambiguous in kind: the entries are architectural rulings about representation (which ADR 0004 "
        + "§1 routes to ADR prose) that a gate nonetheless has to consume as data.",
      ["libs/magic-ast/schema/destring-worklist.json"] =
        "Initiative-05 burn-down worklist: a frozen MEASUREMENT of which golds carry free-text sinks. "
        + "Recomputable from the golds (therefore Derived), but deliberately frozen to pin migration debt "
        + "at a point in time — the ADR does not say whether a deliberately-frozen measurement is Derived "
        + "or a decision record.",
    };

  private const string InteractionCardReason =
    "Card AST input for the interaction tests (BloodArtistPortGraphTest / the sentinel manifest). Each is "
    + "a card's parsed AST — Derived if it was produced by running the parser over oracle text, Evidence if "
    + "it was hand-parsed like a HandParsedCards gold. Indistinguishable from the file alone, and it "
    + "duplicates a card that also exists under Fixtures/HandParsedCards.";

  // ── The scan ─────────────────────────────────────────────────────────────────────────────────────

  public sealed record ScanRoot(string RelativePath, string Rationale, bool JsonOnly = false);

  public sealed record ArtifactRecord(
    string Path,
    string Kind,
    string Rule,
    string Basis,
    bool Acknowledged
  );

  public sealed record ExclusionRecord(string Path, string Rule);

  public sealed record ScanRootResult(string Path, string Rationale, bool Exists, int ArtifactCount);

  public sealed record CensusResult(
    IReadOnlyList<ScanRootResult> Roots,
    IReadOnlyList<ArtifactRecord> Artifacts,
    IReadOnlyList<ExclusionRecord> Exclusions,
    IReadOnlyList<string> UnconfirmedGeneratedDirectories
  )
  {
    /// <summary>The gate's failure set: artifacts no rule resolved and no human acknowledged.</summary>
    public IReadOnlyList<ArtifactRecord> Unclassified =>
      Artifacts.Where(a => a.Kind == NeedsHuman && !a.Acknowledged).ToList();
  }

  /// <summary>Locate the repository root by walking up for the workspace marker.</summary>
  public static string RepoRoot(string? start = null)
  {
    var dir = new DirectoryInfo(start ?? AppContext.BaseDirectory);
    while (dir is not null)
    {
      if (File.Exists(Path.Combine(dir.FullName, "MagicAtlas.slnx")))
        return dir.FullName;
      dir = dir.Parent;
    }
    throw new InvalidOperationException("Could not locate the repository root (MagicAtlas.slnx).");
  }

  /// <summary>Enumerate + classify every artifact on the declared surface. Pure w.r.t. the working
  /// tree: reads the filesystem, writes nothing.</summary>
  public static CensusResult Run(string repoRoot)
  {
    var source = SourceIndex.Build(repoRoot);
    var catalogOutputs = source.CatalogOutputSuffixes;

    var roots = new List<ScanRootResult>();
    var artifacts = new List<ArtifactRecord>();
    var exclusions = new List<ExclusionRecord>();

    foreach (var root in ScanRoots)
    {
      var abs = Path.Combine(repoRoot, root.RelativePath);
      if (!Directory.Exists(abs))
      {
        roots.Add(new ScanRootResult(root.RelativePath, root.Rationale, false, 0));
        continue;
      }

      var found = 0;
      foreach (var file in EnumerateFiles(abs))
      {
        var rel = Rel(repoRoot, file);
        if (root.JsonOnly && !rel.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
          continue;

        var excluded = ExclusionRule(rel);
        if (excluded is not null)
        {
          exclusions.Add(new ExclusionRecord(rel, excluded));
          continue;
        }

        artifacts.Add(Classify(rel, catalogOutputs, source));
        found++;
      }
      roots.Add(new ScanRootResult(root.RelativePath, root.Rationale, true, found));
    }

    // Roots overlap (libs/ subsumes libs/atlas-flows/Data/_08_Reporting); dedupe on path.
    var deduped = artifacts
      .GroupBy(a => a.Path, StringComparer.Ordinal)
      .Select(g => g.First())
      .OrderBy(a => a.Path, StringComparer.Ordinal)
      .ToList();

    var dedupedExclusions = exclusions
      .GroupBy(e => e.Path, StringComparer.Ordinal)
      .Select(g => g.First())
      .OrderBy(e => e.Path, StringComparer.Ordinal)
      .ToList();

    // Second key for rule 5: a named generated directory must exist AND be confirmed by the source
    // index. A name whose regenerator was deleted or renamed is stale hand-maintained state.
    var unconfirmed = GeneratedDirectories
      .Keys.Where(d =>
        !Directory.Exists(Path.Combine(repoRoot, d))
        || source.DirectoryRegeneratorFor(d + "/probe") is null
      )
      .OrderBy(d => d, StringComparer.Ordinal)
      .ToList();

    return new CensusResult(roots, deduped, dedupedExclusions, unconfirmed);
  }

  private static ArtifactRecord Classify(
    string rel,
    IReadOnlyDictionary<string, string> catalogOutputs,
    SourceIndex source
  )
  {
    // 0. A human ruling always wins.
    if (HumanRulings.TryGetValue(rel, out var ruling))
      return new ArtifactRecord(rel, ruling.Kind, "HumanRuling", ruling.Basis, true);

    // 1. Declared Flowthru catalog output. Matched in BOTH directions, because a catalog path and an
    // artifact path can each be the longer one:
    //   - the artifact sits under a project's Data root, so its repo-relative path is the LONGER string
    //     and ends with the catalog's declared suffix (tests/magic-ast-tests/Data/_08_Reporting/x.json
    //     ends with _08_Reporting/x.json);
    //   - or the artifact has been PROMOTED out to a shorter repo-root path, so the catalog suffix is the
    //     longer string and ends with the artifact's whole path (the D1–D4 CardAtlas dumps are declared at
    //     _08_Reporting/dumps/card-ports.json and promoted to dumps/card-ports.json for atlas-api /
    //     atlas-diag to consume).
    // Both directions require a full path-segment match, so a promoted artifact is recognized while a
    // foreign file dropped into the same directory still falls through to the unclassified set.
    var norm = rel.Replace('\\', '/');
    var catalogHit = catalogOutputs.FirstOrDefault(kv =>
      norm.EndsWith(kv.Key, StringComparison.Ordinal)
      || kv.Key.EndsWith("/" + norm, StringComparison.Ordinal)
    );
    if (catalogHit.Key is not null)
      return new ArtifactRecord(
        rel,
        Derived,
        "FlowthruCatalogOutput",
        norm.EndsWith(catalogHit.Key, StringComparison.Ordinal)
          ? $"declared as a catalog item output at {catalogHit.Value}"
          : $"promoted copy of the catalog item output {catalogHit.Key}, declared at {catalogHit.Value}",
        false
      );

    // 2. Reporting layer — a flow output by the project's layering convention.
    if (("/" + rel.Replace('\\', '/')).Contains(ReportingSegment, StringComparison.Ordinal))
      return new ArtifactRecord(
        rel,
        Derived,
        "ReportingLayer",
        "lives under Data/_08_Reporting (Flowthru reporting layer: generated, gitignored)",
        false
      );

    // 3. Hand-authored gold directory.
    foreach (var (prefix, why) in EvidenceDirectories)
      if (rel.StartsWith(prefix, StringComparison.Ordinal))
        return new ArtifactRecord(rel, Evidence, "GoldConvention", why, false);

    // 4. A product source file writes this exact filename.
    var writer = source.WriterFor(Path.GetFileName(rel));
    if (writer is not null)
      return new ArtifactRecord(
        rel,
        Derived,
        "NamedWriter",
        $"regenerated by {writer}",
        false
      );

    // 5. Computed-filename member of a named, machine-confirmed generated directory.
    var dir = (Path.GetDirectoryName(rel) ?? "").Replace('\\', '/');
    if (
      !source.MentionsFileName(Path.GetFileName(rel))
      && GeneratedDirectories.ContainsKey(dir)
      && source.DirectoryRegeneratorFor(rel) is { } dirRegen
    )
      return new ArtifactRecord(
        rel,
        Derived,
        "GeneratedSibling",
        $"filename never appears in source; its directory is a named generated directory, confirmed "
          + $"regenerated by {dirRegen}",
        false
      );

    // 6. Unresolved.
    var ack = AcknowledgedAmbiguous.TryGetValue(rel, out var reason);
    return new ArtifactRecord(
      rel,
      NeedsHuman,
      "Unresolved",
      ack
        ? reason!
        : "No classification rule resolved this artifact and no human acknowledgment exists for it. "
          + "Add an entry to ArtifactClassifier.AcknowledgedAmbiguous (with the reason it is ambiguous) "
          + "or to ArtifactClassifier.HumanRulings (with the ruling), or give it a regeneration path.",
      ack
    );
  }

  /// <summary>Enumerate under <paramref name="root"/>, dropping excluded directories. Exclusion is
  /// tested on the path RELATIVE to the root — the repository may itself live under an excluded
  /// segment (an agent worktree under <c>.claude/worktrees/</c> is the live case), and testing the
  /// absolute path would silently census nothing.</summary>
  private static IEnumerable<string> EnumerateFiles(string root) =>
    Directory
      .EnumerateFiles(root, "*", SearchOption.AllDirectories)
      .Where(f => !IsExcludedPath(Path.GetRelativePath(root, f)));

  private static bool IsExcludedPath(string relativePath)
  {
    var p = "/" + relativePath.Replace('\\', '/');
    return ExcludedSegments.Any(s => p.Contains(s, StringComparison.Ordinal));
  }

  private static string Rel(string repoRoot, string abs) =>
    Path.GetRelativePath(repoRoot, abs).Replace('\\', '/');

  // ── Source-code index: the derivation evidence behind rules 1, 4 and 5 ───────────────────────────

  /// <summary>
  /// A one-pass index over PRODUCT source (tests/, libs/, tools/, apps/). Agent tooling under
  /// <c>.claude/</c> is deliberately NOT indexed: a skill script that rewrites a whitelist is agent
  /// convenience, not the product's derivation path, and treating it as one would silently promote
  /// hand-curated whitelists to "Derived".
  /// </summary>
  /// <remarks>
  /// <para><b>Write sites are resolved through symbols, never by proximity.</b> The first cut of this
  /// index called a file a writer when a write primitive sat within N lines of the filename literal,
  /// and it was wrong in exactly the way ADR 0004 warns about — it promoted
  /// <c>oracle-text-quarantine.json</c> to "Derived" off a sweep utility whose neighbouring
  /// <c>File.WriteAllText</c> targets a different file and whose very next line says the quarantine is
  /// "NOT auto-edited". A near-miss that silently reclassifies a hand-curated whitelist is worse than
  /// no rule at all: an unresolved artifact merely gets flagged.</para>
  /// <para>So each write call's arguments are followed through the file's local path-symbol
  /// definitions (up to <see cref="MaxSymbolDepth"/> hops — <c>path → SnapshotPath() →
  /// "captures-accepted-pairs.txt"</c> is a real two-hop chain here) and only the filename literals
  /// actually reachable count. A writer whose target is computed (<c>Slug(name) + ".json"</c>)
  /// resolves to no filename, which is correct — rule 5 picks those up by directory.</para>
  /// <para>Rule 5 reconstructs the <b>whole path</b> a regenerator writes into, not just the last
  /// segment. Matching on the segment alone made every file directly under <c>Fixtures/</c> look
  /// generated, because some regenerator somewhere mentions <c>"Fixtures"</c> — which silently
  /// swallowed the gate's own teeth probe.</para>
  /// </remarks>
  private sealed class SourceIndex
  {
    private static readonly string[] SourceRoots = ["tests", "libs", "tools", "apps"];
    private static readonly string[] SourceExtensions =
    [
      ".cs", ".py", ".sh", ".ts", ".tsx", ".js", ".mjs",
    ];

    /// <summary>How many symbol hops a write target is followed through.</summary>
    private const int MaxSymbolDepth = 4;

    /// <summary>How many lines of a call's argument list count as part of the write site.</summary>
    private const int CallSpanLines = 3;

    /// <summary>Cap on a symbol definition's body, for wrapped <c>Path.Combine(...)</c> calls.</summary>
    private const int MaxDefinitionLines = 8;

    private static readonly Regex FileLiteral = new(
      @"[A-Za-z0-9_\-][A-Za-z0-9._\-]*\.(?:json|jsonl|txt|csv|html|parquet)",
      RegexOptions.Compiled
    );

    /// <summary>Write primitives, each capturing its <b>target expression</b> (the first argument) so
    /// resolution follows what is actually being written to, not whatever identifiers happen to share
    /// the line. Shell redirects are deliberately absent: a shell <c>&gt;</c> cannot be attributed to a
    /// target without parsing the script (the corpus-edge-diff gate redirects into a <c>mktemp</c> two
    /// lines after merely reading its carve-out list), and a false attribution is worse than an
    /// unresolved artifact — the latter at least gets flagged.</summary>
    private static readonly Regex[] WriteTargets =
    [
      new(
        @"(?:File\.WriteAll(?:Text|Bytes|Lines)(?:Async)?|File\.Create|new StreamWriter|writeFileSync)\s*\(\s*([^,)\n]*)",
        RegexOptions.Compiled
      ),
      // Python: only a write/append mode counts — plain open() is a read.
      new(@"open\(\s*([^,)\n]*)\s*,\s*[""'][wa]", RegexOptions.Compiled),
      new(@"\.to_json\(\s*([^,)\n]*)", RegexOptions.Compiled),
    ];

    private static readonly Regex RegenerationMarker = new(
      @"UPDATE_SNAPSHOT|\bRegenerate\w*|--update\b|REGENERATE",
      RegexOptions.Compiled
    );

    private static readonly Regex AtPathLiteral = new(
      @"\.AtPath\(\s*\$?""([^""]+)""",
      RegexOptions.Compiled
    );

    /// <summary>A path-carrying symbol definition: <c>X =</c>, <c>X =></c>, or <c>X() =></c>.</summary>
    private static readonly Regex SymbolDefinition = new(
      @"\b([A-Za-z_]\w*)\s*(?:\(\s*\))?\s*(?:=>|=)(?![=>])",
      RegexOptions.Compiled
    );

    private static readonly Regex Identifier = new(@"\b([A-Za-z_]\w*)\b", RegexOptions.Compiled);

    /// <summary>A quoted token shaped like a single path segment.</summary>
    private static readonly Regex SegmentLiteral = new(
      @"[""']([A-Za-z0-9_][A-Za-z0-9._\-]*)[""']",
      RegexOptions.Compiled
    );

    /// <summary>Filenames mentioned anywhere in indexed source (rule 5's negative precondition).</summary>
    private readonly HashSet<string> _mentioned = new(StringComparer.Ordinal);

    /// <summary>filename -> the source site that writes it.</summary>
    private readonly Dictionary<string, string> _writers = new(StringComparer.Ordinal);

    /// <summary>reconstructed directory path -> the regenerating write site.</summary>
    private readonly Dictionary<string, string> _dirRegenerators = new(StringComparer.Ordinal);

    /// <summary>normalized catalog output suffix -> the catalog file:line that declares it.</summary>
    public Dictionary<string, string> CatalogOutputSuffixes { get; } = new(StringComparer.Ordinal);

    public static SourceIndex Build(string repoRoot)
    {
      var idx = new SourceIndex();
      foreach (var root in SourceRoots)
      {
        var abs = Path.Combine(repoRoot, root);
        if (!Directory.Exists(abs))
          continue;
        foreach (var file in EnumerateFiles(abs))
        {
          if (!SourceExtensions.Contains(Path.GetExtension(file).ToLowerInvariant()))
            continue;
          idx.Ingest(repoRoot, file);
        }
      }
      return idx;
    }

    private void Ingest(string repoRoot, string absFile)
    {
      var rel = Rel(repoRoot, absFile);
      string[] lines;
      try
      {
        lines = File.ReadAllLines(absFile);
      }
      catch (IOException)
      {
        return;
      }

      var hasRegenMarker = false;
      foreach (var line in lines)
      {
        if (RegenerationMarker.IsMatch(line))
          hasRegenMarker = true;
        foreach (Match m in FileLiteral.Matches(line))
          _mentioned.Add(m.Value);
      }

      for (var i = 0; i < lines.Length; i++)
        foreach (Match m in AtPathLiteral.Matches(lines[i]))
        {
          var suffix = NormalizeCatalogPath(m.Groups[1].Value);
          if (suffix.Length > 0)
            CatalogOutputSuffixes.TryAdd(suffix, $"{rel}:{i + 1}");
        }

      var symbols = BuildSymbolTable(lines);

      for (var i = 0; i < lines.Length; i++)
      {
        var target = WriteTargetExpression(lines, i);
        if (target is null)
          continue;

        var reached = Reachable(target, symbols);

        foreach (var file in FileLiteral.Matches(target).Select(m => m.Value)
          .Concat(reached.SelectMany(s => symbols[s].Files)))
          _writers.TryAdd(file, $"{rel}:{i + 1}");

        // Rule 5's evidence: the directory this write site targets, reconstructed from the ordered
        // path-segment literals of every symbol the target expression reaches. Only regenerators
        // qualify — a plain report writer is not evidence that its directory is wholly generated.
        if (!hasRegenMarker)
          continue;
        foreach (var dir in reached.Select(s => symbols[s].DirectoryPath).Where(d => d.Length > 0))
          _dirRegenerators.TryAdd(dir, $"{rel}:{i + 1}");
      }
    }

    /// <summary>The target expression of a write call starting on <paramref name="i"/>, or null if the
    /// line is not a write. An argument list wrapped onto the next line ("File.WriteAllText(\n
    /// WhitelistPath(),") is followed for <see cref="CallSpanLines"/> lines.</summary>
    private static string? WriteTargetExpression(string[] lines, int i)
    {
      foreach (var rx in WriteTargets)
      {
        var m = rx.Match(lines[i]);
        if (!m.Success)
          continue;
        var expr = m.Groups[1].Value.Trim();
        for (var j = i + 1; expr.Length == 0 && j < lines.Length && j - i < CallSpanLines; j++)
          expr = lines[j].Split(',')[0].Trim();
        return expr;
      }
      return null;
    }

    private sealed record SymbolInfo(
      HashSet<string> Files,
      HashSet<string> Refs,
      string DirectoryPath
    );

    /// <summary>The file's local path-symbol table: for each definition, the filename literals it
    /// contains, the identifiers it refers to, and the directory path its ordered segment literals
    /// spell out.</summary>
    private static Dictionary<string, SymbolInfo> BuildSymbolTable(string[] lines)
    {
      var table = new Dictionary<string, SymbolInfo>(StringComparer.Ordinal);
      for (var i = 0; i < lines.Length; i++)
      {
        var def = SymbolDefinition.Match(lines[i]);
        if (!def.Success)
          continue;
        var name = def.Groups[1].Value;
        var body = lines[i][(def.Index + def.Length)..];
        for (var j = i + 1; j < lines.Length && j - i < MaxDefinitionLines && !body.Contains(';'); j++)
          body += "\n" + lines[j];

        var files = FileLiteral.Matches(body).Select(m => m.Value).ToHashSet(StringComparer.Ordinal);
        var refs = Identifier
          .Matches(body)
          .Select(m => m.Value)
          .Where(id => id != name)
          .ToHashSet(StringComparer.Ordinal);
        var segments = SegmentLiteral
          .Matches(body)
          .Select(m => m.Groups[1].Value)
          .Where(s => !files.Contains(s) && !s.Contains('.'))
          .ToList();

        // A name can be defined more than once in a file (a `var path = …` in one method, another in
        // the next). C#-accurate scoping is out of proportion here; UNION the definitions instead —
        // per-file over-approximation, which at worst widens rule 4 and can never silently narrow it.
        var dirPath = segments.Count >= 2 ? string.Join('/', segments) : "";
        if (table.TryGetValue(name, out var prior))
        {
          files.UnionWith(prior.Files);
          refs.UnionWith(prior.Refs);
          if (dirPath.Length == 0)
            dirPath = prior.DirectoryPath;
        }
        table[name] = new SymbolInfo(files, refs, dirPath);
      }
      return table;
    }

    /// <summary>Every symbol reachable from a call's argument text, following aliases.</summary>
    private static HashSet<string> Reachable(
      string callText,
      Dictionary<string, SymbolInfo> symbols
    )
    {
      var reached = new HashSet<string>(StringComparer.Ordinal);
      var frontier = Identifier.Matches(callText).Select(m => m.Value).ToList();
      for (var depth = 0; depth < MaxSymbolDepth && frontier.Count > 0; depth++)
      {
        var next = new List<string>();
        foreach (var id in frontier)
        {
          if (!symbols.TryGetValue(id, out var info) || !reached.Add(id))
            continue;
          next.AddRange(info.Refs);
        }
        frontier = next;
      }
      return reached;
    }

    /// <summary>Strip the catalog's <c>{_basePath}</c> interpolation and collapse <c>..</c> so the
    /// declared output becomes a path suffix matchable against a repo-relative artifact path.</summary>
    private static string NormalizeCatalogPath(string raw)
    {
      var s = raw.Replace('\\', '/');
      var brace = s.LastIndexOf('}');
      if (brace >= 0)
        s = s[(brace + 1)..];
      s = s.TrimStart('/');
      var parts = new List<string>();
      foreach (var seg in s.Split('/', StringSplitOptions.RemoveEmptyEntries))
      {
        if (seg == "..")
        {
          if (parts.Count > 0)
            parts.RemoveAt(parts.Count - 1);
          continue;
        }
        if (seg == ".")
          continue;
        parts.Add(seg);
      }
      var normalized = string.Join('/', parts);
      // Require at least dir/file so a bare filename cannot match half the repo.
      return normalized.Contains('/') ? "/" + normalized : "";
    }

    public bool MentionsFileName(string fileName) => _mentioned.Contains(fileName);

    /// <summary>The source site that writes <paramref name="fileName"/>, or null.</summary>
    public string? WriterFor(string fileName) =>
      _writers.TryGetValue(fileName, out var site) ? site : null;

    /// <summary>The regenerator that writes into the artifact's containing directory — matched on the
    /// FULL reconstructed path, so a regenerator that merely mentions <c>"Fixtures"</c> does not claim
    /// everything under it.</summary>
    public string? DirectoryRegeneratorFor(string relPath)
    {
      var dir = (Path.GetDirectoryName(relPath.Replace('\\', '/')) ?? "").Replace('\\', '/');
      if (dir.Length == 0)
        return null;
      foreach (var (candidate, site) in _dirRegenerators)
        if (dir.Equals(candidate, StringComparison.Ordinal)
          || dir.EndsWith("/" + candidate, StringComparison.Ordinal))
          return site;
      return null;
    }
  }
}
