namespace MagicAST.Parsing.Parsers.Activated.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// "Prevent the next N damage that would be dealt to any target this turn."
///
/// Maps to <see cref="PreventDamageEffect"/> with a literal <see cref="Amount"/>,
/// <see cref="ObjectReferenceKind.AnyTarget"/> as the <see cref="PreventDamageEffect.Target"/>,
/// and an <c>untilEndOfTurn</c> <see cref="MagicAST.AST.Effects.Duration"/>.
///
/// CR 615.8 (cited verbatim): "Some prevention effects generated by the resolution of a spell
/// or ability refer to the next time a specific source would deal damage. These effects prevent
/// the next instance of damage from that source, regardless of how much damage that is."
/// </summary>
[ActivatedEffectRule(Priority = 980)]
public sealed class PreventNextNDamageToAnyTargetEffectRule : IActivatedEffectRule
{
  // Pattern: "Prevent the next N damage that would be dealt to any target this turn"
  // N is a digit string (1, 2, 3, ...) or spelled-out word.
  private static readonly Regex Pattern = new(
    @"^[Pp]revent\s+the\s+next\s+(?<amount>\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+damage\s+that\s+would\s+be\s+dealt\s+to\s+any\s+target\s+this\s+turn$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public Effect? TryMatch(string effectText)
  {
    var trimmed = effectText.Trim().TrimEnd('.').Trim();
    var m = Pattern.Match(trimmed);
    if (!m.Success)
    {
      return null;
    }

    var raw = m.Groups["amount"].Value.ToLowerInvariant();
    int amount = raw switch
    {
      "one" => 1,
      "two" => 2,
      "three" => 3,
      "four" => 4,
      "five" => 5,
      "six" => 6,
      "seven" => 7,
      "eight" => 8,
      "nine" => 9,
      "ten" => 10,
      _ => int.Parse(raw),
    };

    return new PreventDamageEffect
    {
      Amount = LiteralQuantity.Of(amount),
      Target = new ObjectReference { Kind = ObjectReferenceKind.AnyTarget },
      Duration = UntilTimeDuration.EndOfTurn,
    };
  }
}
