namespace MagicAST.Parsing.Parsers.Activated.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// "Prevent the next N damage that would be dealt to target creature this turn."
/// (Kei Takahashi's activated ability.)
///
/// Maps to <see cref="PreventDamageEffect"/> with a literal <see cref="Amount"/>,
/// a <see cref="ObjectReferenceKind.Target"/> reference filtered to
/// <c>CardTypes=["creature"]</c> as the <see cref="PreventDamageEffect.Target"/>,
/// and an <c>untilEndOfTurn</c> <see cref="MagicAST.AST.Effects.Duration"/>. The
/// creature-targeted sibling of <see cref="PreventNextNDamageToAnyTargetEffectRule"/>.
///
/// This is a bounded-amount prevention shield, distinct from the "next instance"
/// (Circle/Rune of Protection) shield. CR 615.7 (cited verbatim): "Some prevention
/// effects generated by the resolution of a spell or ability refer to a specific
/// amount of damage-for example, "Prevent the next 3 damage that would be dealt to
/// any target this turn." These work like shields. Each 1 damage that would be
/// dealt to the "shielded" permanent or player is prevented. Preventing 1 damage
/// reduces the remaining shield by 1. ... Once the shield has been reduced to 0,
/// any remaining damage is dealt normally. Such effects count only the amount of
/// damage; the number of events or sources dealing it doesn't matter."
/// </summary>
[ActivatedEffectRule(Priority = 980)]
public sealed class PreventNextNDamageToTargetCreatureEffectRule : IActivatedEffectRule
{
  // Anchored: "Prevent the next N damage that would be dealt to target creature this turn".
  // N is a digit string (1, 2, 3, ...) or a spelled-out word.
  private static readonly Regex Pattern = new(
    @"^[Pp]revent\s+the\s+next\s+(?<amount>\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s+damage\s+that\s+would\s+be\s+dealt\s+to\s+target\s+creature\s+this\s+turn$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public Effect? TryMatch(string effectText)
  {
    var trimmed = effectText.Trim().TrimEnd('.').Trim();
    var m = Pattern.Match(trimmed);
    if (!m.Success)
    {
      return null;
    }

    var raw = m.Groups["amount"].Value.ToLowerInvariant();
    int amount = raw switch
    {
      "one" => 1,
      "two" => 2,
      "three" => 3,
      "four" => 4,
      "five" => 5,
      "six" => 6,
      "seven" => 7,
      "eight" => 8,
      "nine" => 9,
      "ten" => 10,
      _ => int.Parse(raw),
    };

    return new PreventDamageEffect
    {
      Amount = LiteralQuantity.Of(amount),
      Target = ObjectReference.Target(new ObjectFilter { CardTypes = ["creature"] }),
      Duration = UntilTimeDuration.EndOfTurn,
    };
  }
}
