namespace MagicAST.Parsing.Parsers.Activated.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.References;

/// <summary>
/// "The next time a source of your choice would deal damage to any target this
/// turn, prevent that damage." — the one-shot prevention shield with no source
/// restriction whose recipient is "any target" rather than "you" (e.g. Martyr's
/// Cause, Circle of Despair, Sanctum Guardian).
///
/// This is the "to any target" sibling of
/// <see cref="PreventNextDamageFromChosenSourceEffectRule"/> (the "to you"
/// variant): same CR-615.8 next-instance shield, same controller-chosen unfiltered
/// designated source, but the protected recipient is
/// <see cref="ObjectReferenceKind.AnyTarget"/> (matching how
/// <see cref="PreventNextNDamageToAnyTargetEffectRule"/> records "any target").
/// Maps to <see cref="PreventDamageEffect"/> with
/// <see cref="PreventDamageEffect.NextInstance"/> set (the "next instance,
/// regardless of amount" semantics — distinct from a bounded
/// <see cref="PreventDamageEffect.Amount"/> or the all-instances
/// <see cref="PreventDamageEffect.All"/>), the damage
/// <see cref="PreventDamageEffect.Source"/> as an unfiltered
/// <see cref="ObjectReferenceKind.Designated"/> reference (any source,
/// controller-chosen — not a target, no targeting keyword in the oracle), the
/// <see cref="PreventDamageEffect.Target"/> (recipient) as
/// <see cref="ObjectReferenceKind.AnyTarget"/>, and an <c>untilTime</c>/end-of-turn
/// <see cref="MagicAST.AST.Effects.Duration"/> for "this turn".
///
/// "of your choice" is recorded as the player-designated reference itself, not its
/// resolution (ADR 0004 reference-not-resolution). This is CR-615 prevention, NOT a
/// replacement effect — no replacement ordering/layering is modelled.
///
/// The pattern is anchored <c>^…prevent that damage$</c> so it matches ONLY the
/// standalone uncoloured "to any target" line: it cannot fire on the "to you"
/// sibling, the coloured/typed variants ("a red source"), or the qualified
/// follow-ups (e.g. Honorable Passage's "… If damage from a red source is prevented
/// this way …"), each of which carries extra tokens outside the fixed anchors.
///
/// CR 615.8 (cited verbatim): "Some prevention effects generated by the resolution of a
/// spell or ability refer to the next time a specific source would deal damage. These
/// effects prevent the next instance of damage from that source, regardless of how much
/// damage that is. Once an instance of damage from that source has been prevented, any
/// subsequent instances of damage that would be dealt by that source are dealt normally."
///
/// CR 615.2 (cited verbatim): "Many prevention effects apply to damage from a source.
/// See rule 609.7."
/// </summary>
[ActivatedEffectRule(Priority = 990)]
public sealed class PreventNextDamageFromChosenSourceToAnyTargetEffectRule : IActivatedEffectRule
{
  // "The next time a source of your choice would deal damage to any target this turn, prevent that damage"
  private static readonly Regex Pattern = new(
    @"^[Tt]he\s+next\s+time\s+a\s+source\s+of\s+your\s+choice\s+would\s+deal\s+damage\s+to\s+any\s+target\s+this\s+turn,\s+prevent\s+that\s+damage$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public Effect? TryMatch(string effectText)
  {
    var trimmed = effectText.Trim().TrimEnd('.').Trim();
    if (!Pattern.IsMatch(trimmed))
    {
      return null;
    }

    return new PreventDamageEffect
    {
      NextInstance = true,
      Source = new ObjectReference { Kind = ObjectReferenceKind.Designated },
      Target = new ObjectReference { Kind = ObjectReferenceKind.AnyTarget },
      Duration = UntilTimeDuration.EndOfTurn,
    };
  }
}
