namespace MagicAST.Parsing.Parsers.Activated.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.References;

/// <summary>
/// "The next time a [color] source of your choice would deal damage to you this
/// turn, prevent that damage." — the Circle/Rune of Protection one-shot prevention
/// shield (e.g. Circle of Protection: Red, Rune of Protection: Red).
///
/// Maps to <see cref="PreventDamageEffect"/> with <see cref="PreventDamageEffect.NextInstance"/>
/// set (the "next instance, regardless of amount" semantics — distinct from a bounded
/// <see cref="PreventDamageEffect.Amount"/> or the all-instances <see cref="PreventDamageEffect.All"/>),
/// the damage <see cref="PreventDamageEffect.Source"/> as a <see cref="ObjectReferenceKind.Designated"/>
/// reference filtered by the named color ("a red source of your choice" — the controller
/// designates which qualifying source at resolution; not a target, no targeting keyword
/// in the oracle, and not controller-bound), the <see cref="PreventDamageEffect.Target"/>
/// (recipient) as <see cref="ObjectReferenceKind.You"/>, and an <c>untilTime</c>/end-of-turn
/// <see cref="MagicAST.AST.Effects.Duration"/> for "this turn".
///
/// "of your choice" is recorded as the player-designated reference itself, not its
/// resolution (ADR 0004 reference-not-resolution). This is CR-615 prevention, NOT a
/// replacement effect — no replacement ordering/layering is modelled.
///
/// CR 615.8 (cited verbatim): "Some prevention effects generated by the resolution of a
/// spell or ability refer to the next time a specific source would deal damage. These
/// effects prevent the next instance of damage from that source, regardless of how much
/// damage that is. Once an instance of damage from that source has been prevented, any
/// subsequent instances of damage that would be dealt by that source are dealt normally."
///
/// CR 615.2 (cited verbatim): "Many prevention effects apply to damage from a source.
/// See rule 609.7."
/// </summary>
[ActivatedEffectRule(Priority = 990)]
public sealed class PreventNextDamageFromColorSourceEffectRule : IActivatedEffectRule
{
  // "The next time a <color> source of your choice would deal damage to you this turn, prevent that damage"
  private static readonly Regex Pattern = new(
    @"^[Tt]he\s+next\s+time\s+a\s+(?<color>white|blue|black|red|green)\s+source\s+of\s+your\s+choice\s+would\s+deal\s+damage\s+to\s+you\s+this\s+turn,\s+prevent\s+that\s+damage$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Single-letter colour codes as used throughout the corpus (ObjectFilter.Colors).
  private static readonly Dictionary<string, string> ColorCodes = new(StringComparer.OrdinalIgnoreCase)
  {
    ["white"] = "W",
    ["blue"] = "U",
    ["black"] = "B",
    ["red"] = "R",
    ["green"] = "G",
  };

  public Effect? TryMatch(string effectText)
  {
    var trimmed = effectText.Trim().TrimEnd('.').Trim();
    var m = Pattern.Match(trimmed);
    if (!m.Success)
    {
      return null;
    }

    var color = ColorCodes[m.Groups["color"].Value];

    return new PreventDamageEffect
    {
      NextInstance = true,
      Source = new ObjectReference
      {
        Kind = ObjectReferenceKind.Designated,
        Filter = new ObjectFilter { Colors = [color] },
      },
      Target = new ObjectReference { Kind = ObjectReferenceKind.You },
      Duration = UntilTimeDuration.EndOfTurn,
    };
  }
}
