namespace MagicAST.Parsing.Parsers.Activated.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.References;

/// <summary>
/// "The next time a source of your choice would deal damage to you this turn,
/// prevent that damage." — the uncoloured one-shot prevention shield with no
/// source restriction (e.g. Pentagram of the Ages, Haazda Shield Mate,
/// Invulnerability, Righteous Aura).
///
/// This is the sibling of <see cref="PreventNextDamageFromColorSourceEffectRule"/>
/// (the "a [color] source of your choice" Circle/Rune-of-Protection variant): same
/// CR-615.8 next-instance shield, but the designated source carries no colour/type
/// filter — the controller may name any source ("a source of your choice"). Maps to
/// <see cref="PreventDamageEffect"/> with <see cref="PreventDamageEffect.NextInstance"/>
/// set (the "next instance, regardless of amount" semantics — distinct from a bounded
/// <see cref="PreventDamageEffect.Amount"/> or the all-instances <see cref="PreventDamageEffect.All"/>),
/// the damage <see cref="PreventDamageEffect.Source"/> as an unfiltered
/// <see cref="ObjectReferenceKind.Designated"/> reference (any source, controller-chosen —
/// not a target, no targeting keyword in the oracle), the
/// <see cref="PreventDamageEffect.Target"/> (recipient) as
/// <see cref="ObjectReferenceKind.You"/>, and an <c>untilTime</c>/end-of-turn
/// <see cref="MagicAST.AST.Effects.Duration"/> for "this turn".
///
/// "of your choice" is recorded as the player-designated reference itself, not its
/// resolution (ADR 0004 reference-not-resolution). This is CR-615 prevention, NOT a
/// replacement effect — no replacement ordering/layering is modelled.
///
/// The pattern is anchored <c>^…prevent that damage$</c> so it matches ONLY the
/// standalone uncoloured "to you" line: it cannot fire on the coloured/typed siblings
/// ("a red source", "an artifact source"), a different recipient ("to target creature",
/// "to any target"), or the qualified variants ("… with art by …", "… of the chosen
/// color …") — each carries extra tokens between the fixed anchors and so fails the match.
///
/// CR 615.8 (cited verbatim): "Some prevention effects generated by the resolution of a
/// spell or ability refer to the next time a specific source would deal damage. These
/// effects prevent the next instance of damage from that source, regardless of how much
/// damage that is. Once an instance of damage from that source has been prevented, any
/// subsequent instances of damage that would be dealt by that source are dealt normally."
///
/// CR 615.2 (cited verbatim): "Many prevention effects apply to damage from a source.
/// See rule 609.7."
/// </summary>
[ActivatedEffectRule(Priority = 990)]
public sealed class PreventNextDamageFromChosenSourceEffectRule : IActivatedEffectRule
{
  // "The next time a source of your choice would deal damage to you this turn, prevent that damage"
  private static readonly Regex Pattern = new(
    @"^[Tt]he\s+next\s+time\s+a\s+source\s+of\s+your\s+choice\s+would\s+deal\s+damage\s+to\s+you\s+this\s+turn,\s+prevent\s+that\s+damage$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public Effect? TryMatch(string effectText)
  {
    var trimmed = effectText.Trim().TrimEnd('.').Trim();
    if (!Pattern.IsMatch(trimmed))
    {
      return null;
    }

    return new PreventDamageEffect
    {
      NextInstance = true,
      Source = new ObjectReference { Kind = ObjectReferenceKind.Designated },
      Target = new ObjectReference { Kind = ObjectReferenceKind.You },
      Duration = UntilTimeDuration.EndOfTurn,
    };
  }
}
