namespace MagicAtlas.Bench.Tests;

using System.Text.Json;

/// <summary>
/// The combo-recall GATE — an EXPLICIT per-combo expected-tier whitelist (de-ratcheted 2026-06-16).
/// Re-runs the combo-recall bench over the pinned Spellbook snapshot + the gold corpus, then for EACH
/// eligible combo asserts that the engine's CURRENT reconstruction tier (Green/Amber/Missed) equals the
/// tier explicitly PINNED for that combo on <c>combo-expected-tiers.json</c>.
///
/// <para>
/// This replaces the opaque aggregate moving-baseline ratchet (recall@Green / recall@(Green+Amber) may
/// not decrease vs <c>bench-report.json</c>). The gate is now STATELESS: the expected tiers are explicit
/// and per-combo, not a net aggregate that lets a regression on one combo hide behind an improvement on
/// another. Every drift is a LOUD, per-combo failure:
/// <list type="bullet">
///   <item>a REGRESSION (e.g. Green→Amber, Amber→Missed) fails — a merged batch that silently loses
///         interaction-reconstruction coverage on a specific combo is caught by name;</item>
///   <item>an IMPROVEMENT (e.g. Missed→Amber) ALSO fails, telling you to update the pin for that combo —
///         a coverage gain is a deliberate, reviewed edit to the named pin, never a silent ratchet;</item>
///   <item>a combo present in the run but absent from the whitelist (or vice-versa) fails — the whitelist
///         is a list of NAMES, exhaustive over the eligible set, never a count.</item>
///   <item>a combo whose tier is UNCHANGED but whose reconstructed cycle's diagnostics drifted (a
///         different limiting hop, a flipped Balanced/Productive/etc. flag) fails — the tier-only check
///         above is blind to "stayed Amber but the REASON silently changed"; the diagnostics-equality
///         check below is the assertion that catches it.</item>
/// </list>
/// </para>
///
/// <para>
/// The aggregate recall numbers (RecallAtGreen / RecallAtAmber / the G/A/M counts) are now a DERIVED
/// REPORT, not the gate: <c>bench-report.json</c> stays as the committed report artifact, regenerated by
/// <c>dotnet run -- --write</c>, but it no longer drives pass/fail. <c>combo-expected-tiers.json</c> does.
/// </para>
/// </summary>
[TestFixture]
public class ComboExpectedTierTest
{
  /// <summary>
  /// One pinned expectation: a combo id, its cards (for the failure message), its tier, and its
  /// mechanistic <c>expected</c> diagnostics block (<c>null</c> only for Missed combos).
  /// </summary>
  private sealed record ExpectedTier(
    string Id,
    IReadOnlyList<string> Cards,
    string Tier,
    ExpectedDiagnostics? Expected
  );

  // The current bench run, keyed by combo id (one run, shared across cases).
  private static readonly Lazy<IReadOnlyDictionary<string, ComboResult>> _current = new(RunCurrent);

  // The committed per-combo whitelist, keyed by combo id.
  private static readonly Lazy<IReadOnlyDictionary<string, ExpectedTier>> _expected = new(
    LoadExpected
  );

  [Test]
  public void Whitelist_and_run_are_present()
  {
    Assert.That(
      _expected.Value,
      Is.Not.Empty,
      $"combo-expected-tiers.json is empty/missing at {BenchPaths.ExpectedTiersPath} — seed it from a run."
    );
    Assert.That(_current.Value, Is.Not.Empty, "The bench produced no eligible combos — unexpected.");
  }

  /// <summary>The eligible set is exactly the whitelisted set — no combo run-but-unpinned or pinned-but-gone.</summary>
  [Test]
  public void Eligible_set_matches_the_whitelist_exactly()
  {
    var run = _current.Value.Keys.OrderBy(id => id, StringComparer.Ordinal).ToList();
    var pinned = _expected.Value.Keys.OrderBy(id => id, StringComparer.Ordinal).ToList();

    var runButNotPinned = run.Where(id => !_expected.Value.ContainsKey(id)).ToList();
    var pinnedButNotRun = pinned.Where(id => !_current.Value.ContainsKey(id)).ToList();

    Assert.Multiple(() =>
    {
      Assert.That(
        runButNotPinned,
        Is.Empty,
        "Eligible combo(s) ran but are NOT pinned in combo-expected-tiers.json: "
          + $"[{string.Join(", ", runButNotPinned)}]. Add each with its current tier (the whitelist must "
          + "be exhaustive over the eligible set — a list of NAMES, not a count)."
      );
      Assert.That(
        pinnedButNotRun,
        Is.Empty,
        "Combo(s) pinned in combo-expected-tiers.json are no longer in the eligible run: "
          + $"[{string.Join(", ", pinnedButNotRun)}]. Remove each stale pin (its cards likely left the "
          + "gold corpus or the snapshot)."
      );
    });
  }

  /// <summary>For EACH pinned combo: its current reconstruction tier must equal its pinned expected tier.</summary>
  [TestCaseSource(nameof(WhitelistCases))]
  public void Combo_reconstructs_at_its_pinned_tier(
    string id,
    IReadOnlyList<string> cards,
    string expected,
    ExpectedDiagnostics? _
  )
  {
    Assert.That(
      _current.Value.ContainsKey(id),
      Is.True,
      $"Combo '{id}' ({string.Join(" + ", cards)}) is pinned to '{expected}' but is no longer eligible "
        + "in the run — remove its stale pin from combo-expected-tiers.json."
    );

    var actual = _current.Value[id].Outcome.ToString();
    Assert.That(
      actual,
      Is.EqualTo(expected),
      $"Combo '{id}' ({string.Join(" + ", cards)}) reconstructs at '{actual}' but is pinned to '{expected}' "
        + "in combo-expected-tiers.json. "
        + (TierRank(actual) < TierRank(expected)
          ? "This is a REGRESSION — interaction-reconstruction coverage on this combo dropped; investigate "
            + "the engine/gold change that demoted it."
          : "This is an IMPROVEMENT — update the pin for this combo to '" + actual + "' (a coverage gain is "
            + "a deliberate, reviewed pin edit; the aggregate recall in bench-report.json is a derived report, "
            + "regenerate it via `dotnet run -- --write`).")
    );
  }

  /// <summary>
  /// For EACH pinned combo whose TIER already matches (the test above): the live run's <c>ComboDiagnostics</c>
  /// must structurally equal the pinned <c>expected</c> block — catching "stayed Amber but the limiting
  /// reason / a §8 flag silently changed", which the tier-only check above cannot see. Only meaningful
  /// once the tier matches; if it doesn't, the tier test above already fails loudly, so this test skips
  /// rather than double-reporting the same drift.
  /// </summary>
  [TestCaseSource(nameof(WhitelistCases))]
  public void Combo_diagnostics_matches_the_pinned_expected_block(
    string id,
    IReadOnlyList<string> cards,
    string tier,
    ExpectedDiagnostics? expected
  )
  {
    Assert.That(_current.Value.ContainsKey(id), Is.True, $"Combo '{id}' is no longer eligible in the run.");
    var result = _current.Value[id];

    Assume.That(
      result.Outcome.ToString(),
      Is.EqualTo(tier),
      "Tier already mismatches (see Combo_reconstructs_at_its_pinned_tier) — skipping the diagnostics "
        + "comparison to avoid double-reporting the same drift."
    );

    if (tier == "Missed")
    {
      Assert.Multiple(() =>
      {
        Assert.That(
          result.Diagnostics,
          Is.Null,
          $"Combo '{id}' is pinned Missed but the live run produced a ComboDiagnostics — should be null."
        );
        Assert.That(
          expected,
          Is.Null,
          $"Combo '{id}' is pinned Missed but has a non-null 'expected' block in combo-expected-tiers.json "
            + "— Missed combos must pin 'expected': null."
        );
      });
      return;
    }

    Assert.That(
      result.Diagnostics,
      Is.Not.Null,
      $"Combo '{id}' is pinned '{tier}' but the live run produced no ComboDiagnostics — unexpected."
    );
    Assert.That(
      expected,
      Is.Not.Null,
      $"Combo '{id}' is pinned '{tier}' but has no 'expected' block in combo-expected-tiers.json — "
        + "regenerate it via `dotnet run -- --regenerate-expected-tiers`."
    );

    var actual = ExpectedDiagnostics.FromDiagnostics(result.Diagnostics!);
    Assert.That(
      actual,
      Is.EqualTo(expected),
      $"Combo '{id}' ({string.Join(" + ", cards)}) stays '{tier}' but its live diagnostics no longer "
        + "structurally match the pinned 'expected' block — the REASON it reconstructs at this tier "
        + "silently changed (a different limiting hop, or a flipped §8 flag). If this is a deliberate, "
        + "reviewed engine change, regenerate the pin via `dotnet run -- --regenerate-expected-tiers` "
        + $"(refuses unless expectedTier already matches the live run).\n  actual   : {actual}\n  expected : {expected}"
    );
  }

  /// <summary>Green > Amber > Missed — lets the message distinguish a regression from an improvement.</summary>
  private static int TierRank(string tier) =>
    tier switch
    {
      "Green" => 2,
      "Amber" => 1,
      "Missed" => 0,
      _ => -1,
    };

  public static IEnumerable<TestCaseData> WhitelistCases() =>
    _expected
      .Value.Values.OrderBy(e => e.Id, StringComparer.Ordinal)
      .Select(e =>
        new TestCaseData(e.Id, e.Cards, e.Tier, e.Expected).SetName($"Combo_{e.Id}_is_{e.Tier}")
      );

  private static IReadOnlyDictionary<string, ComboResult> RunCurrent()
  {
    var snapshot = ComboSnapshot.Load(BenchPaths.SnapshotPath);
    var runner = ComboRecallRunner.Create(BenchPaths.FixturesRoot, BenchPaths.OntologyPath);
    return runner.Run(snapshot).Combos.ToDictionary(c => c.Id, StringComparer.Ordinal);
  }

  private static IReadOnlyDictionary<string, ExpectedTier> LoadExpected()
  {
    var path = BenchPaths.ExpectedTiersPath;
    Assert.That(
      File.Exists(path),
      Is.True,
      $"Missing per-combo expected-tier whitelist at {path}. Seed it from a run "
        + "(`dotnet run -- --write` regenerates the derived report; the whitelist is hand-pinned)."
    );

    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    var map = new Dictionary<string, ExpectedTier>(StringComparer.Ordinal);
    if (doc.RootElement.TryGetProperty("combos", out var combos))
    {
      foreach (var e in combos.EnumerateArray())
      {
        var id = e.GetProperty("id").GetString()!;
        var tier = e.GetProperty("expectedTier").GetString()!;
        var cards = e.TryGetProperty("cards", out var c)
          ? c.EnumerateArray().Select(x => x.GetString()!).ToList()
          : [];
        Assert.That(
          tier is "Green" or "Amber" or "Missed",
          Is.True,
          $"Combo '{id}' has an invalid expectedTier '{tier}' — must be Green, Amber, or Missed."
        );

        Assert.That(
          e.TryGetProperty("expected", out _) || e.TryGetProperty("narrative", out _),
          Is.True,
          $"Combo '{id}' still uses the pre-2026-07-18 flat 'reason' schema — migrate it via "
            + "`dotnet run -- --regenerate-expected-tiers` (combo-expected-tiers.json must be fully "
            + "migrated: every entry needs 'expected' + 'narrative' + 'narrativeVerifiedAt')."
        );

        ExpectedDiagnostics? expectedDiagnostics = null;
        if (e.TryGetProperty("expected", out var expectedEl) && expectedEl.ValueKind != JsonValueKind.Null)
          expectedDiagnostics = JsonSerializer.Deserialize<ExpectedDiagnostics>(expectedEl.GetRawText());

        map[id] = new ExpectedTier(id, cards, tier, expectedDiagnostics);
      }
    }

    return map;
  }
}
