using System.Text.Json.Nodes;
using Flowthru.Flow;
using MagicAtlas.Ast.Tests.Data;
using MagicAtlas.Ast.Tests.Data._08_Reporting.Schemas;
using MagicAtlas.Ast.Tests.Flows.InteractionRollup.Steps;
using MagicAtlas.Ast.Tests.Flows.TopologyDemand.Steps;

namespace MagicAtlas.Ast.Tests.Flows.TopologyDemand;

/// <summary>
/// The value-ranked demand overlay for the ADR-3 topology — a SEPARATE, corpus-gated flow (never folded
/// into the hermetic <c>InteractionRollup</c>). It reads only committed hermetic inputs (the golds and the
/// committed <c>port-topology.cited.json</c> / <c>topology-scaffold.json</c>) plus the corpus-gated
/// <c>combo-anchor-report.json</c> (gitignored; regenerated by <c>nx run mast:combo-anchors</c>) — and
/// degrades gracefully when the corpus report is absent. Emits
/// <c>Data/_08_Reporting/port-topology-demand.json</c> (a corpus report, gitignored, never committed).
/// </summary>
public static class TopologyDemandFlow
{
  public static BuiltFlow Create(
    Catalog catalog,
    string goldsDir,
    string topologyCitedPath,
    string scaffoldPath,
    string comboAnchorPath
  ) =>
    FlowBuilder.CreateFlow(
      "TopologyDemand",
      pipeline =>
      {
        // Reuse the hermetic golds loader (id + source.popularity). Distinct label + item from
        // InteractionRollup's — Flowthru validates step-label + producer uniqueness across the merged DAG.
        pipeline.AddStep<IEnumerable<JsonNode>>(
          label: "LoadGoldsForDemand",
          transform: LoadInteractionGoldsStep.Create(goldsDir),
          outputs: catalog.InteractionGoldsForDemand
        );

        // Rank the topology concepts by combo demand.
        pipeline.AddStep<IEnumerable<JsonNode>, PortTopologyDemand>(
          label: "TopologyDemand",
          transform: TopologyDemandStep.Create(topologyCitedPath, scaffoldPath, comboAnchorPath),
          inputs: catalog.InteractionGoldsForDemand,
          outputs: catalog.PortTopologyDemand
        );
      }
    );
}
