namespace MagicAST.Tests.Tests;

using System.Text.Json;
using MagicAST.Tests.Infrastructure;

/// <summary>
/// Fidelity smoke test: a gold fixture's <c>Input.OracleText</c> must be the exact oracle text the
/// corpus parser consumes for that card (<c>card-inputs.json</c>, a faithful projection of Scryfall).
///
/// <para>
/// The per-card parser tests (<see cref="HandParsedCardTests"/>) cannot catch a wrong input string:
/// the expected AST and its <c>RawText</c> spans are sliced from the same <c>Input.OracleText</c>, so
/// a gold authored from the wrong card is internally self-consistent and parses green. This test is
/// the only thing that reaches an authoritative source, so it is the only thing that catches a gold
/// drifting from (or never matching) the real card.
/// </para>
///
/// <para>
/// Cards on <c>Fixtures/oracle-text-quarantine.json</c> are known pre-existing drift, exempt from the
/// match assertion. The quarantine is a ratchet that only shrinks: a quarantined gold that is fixed
/// (now matches) fails until removed from the list, and any gold NOT on the list must match — so no
/// new drift can land. See <c>libs/mast-interaction/docs/interaction-refinement-round2.md</c>.
/// </para>
///
/// <para>
/// The corpus (<c>card-inputs.json</c>) is only the commander-legal-paper SUBSET, so a gold whose card
/// is filtered out of it (digital-only, non-commander, un-cards) would otherwise be un-validatable — the
/// dangerous case, because such a gold parses green on pure self-consistency. The SUPERSET authoritative
/// source closes that hole: the full Scryfall oracle bulk (<see cref="TestData.OracleCardsPath"/>), a
/// faithful, verbatim projection regenerated by the <c>MagicAstTriage</c> Flowthru flow (gitignored, like
/// the corpus — neither is in version control; both are present once the flow has run). For an
/// absent-from-corpus gold it is consulted as a SECOND authoritative source, treated exactly like the
/// corpus: a MATCH validates (the gold must then NOT be on the synthetic register), and a MISMATCH is
/// REAL drift — gated by the same <c>oracle-text-quarantine.json</c> as corpus drift (fix the gold, or
/// quarantine it if the mismatch is known/intentional). The seed is authoritative Scryfall data, so a
/// mismatch is a genuine signal, never suppressed.
/// </para>
///
/// <para>
/// Only a gold whose card is in NEITHER source (absent from the corpus AND from the full bulk) truly
/// cannot be validated; those are registered in <c>Fixtures/synthetic-card-golds.json</c>. That file is
/// NOT a coverage allowlist (its old name, <c>fidelity-uncovered-allowlist.json</c>, said otherwise): every
/// entry was verified against the full Scryfall bulk under a sibling control — the other golds filed in the
/// same set folder DO resolve — so each entry records a fact about Magic (no printed card bears this name),
/// which is Evidence, not a claim about parser or corpus state. It is gated in three directions with no
/// suppression path: an unresolvable gold must be registered, a registered gold that becomes resolvable must
/// be removed (it now gets real validation), and every entry must name a gold that still exists
/// (<see cref="Synthetic_register_entry_names_a_live_gold"/>).
/// </para>
/// </summary>
[TestFixture]
public class GoldOracleTextFidelityTests
{
  // Name -> OracleText from the corpus the parser consumes; null when card-inputs.json is absent.
  private static readonly Lazy<Dictionary<string, string?>?> _corpus = new(LoadCorpus);

  // Name -> oracle_text from the full Scryfall oracle bulk (oracle-cards.json, gitignored; regenerated
  // by the MagicAstTriage flow); null when absent. The SUPERSET authoritative source for golds whose
  // card is filtered out of the commander-legal-paper corpus — see class doc + LoadOracleCards.
  private static readonly Lazy<Dictionary<string, string?>?> _oracleCards = new(LoadOracleCards);

  private static readonly Lazy<HashSet<string>> _quarantine = new(
    () => LoadFixtureNameSet("oracle-text-quarantine.json")
  );

  // testCase.Name set of golds whose card is currently absent from the corpus and so cannot be
  // validated — grandfathered, shrink-only (see class doc).
  private static readonly Lazy<HashSet<string>> _syntheticGolds = new(
    () => LoadFixtureNameSet("synthetic-card-golds.json")
  );

  private static Dictionary<string, string?>? LoadCorpus()
  {
    var path = TestData.CardInputsPath;
    if (!File.Exists(path))
    {
      return null;
    }

    var dict = new Dictionary<string, string?>(StringComparer.Ordinal);
    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    foreach (var rec in doc.RootElement.EnumerateArray())
    {
      if (!rec.TryGetProperty("Input", out var input))
      {
        continue;
      }

      var name = input.TryGetProperty("Name", out var n) ? n.GetString() : null;
      if (name is null || dict.ContainsKey(name))
      {
        continue;
      }

      dict[name] = input.TryGetProperty("OracleText", out var ot) ? ot.GetString() : null;
    }

    return dict;
  }

  // Loads the raw Scryfall seed as name -> oracle_text. Delegates to the shared index in TestData so
  // the "a real card wins over a token/art-series printing of the same name" rule lives in exactly one
  // place (see TestData.LoadOracleCardsByName). Returns null when the gitignored bulk is absent.
  private static Dictionary<string, string?>? LoadOracleCards() => TestData.LoadOracleCardsByName();

  // Loads a committed Fixtures/*.json whitelist — { "entries": [ { "card": ..., "tag": ..., "reason": ... } ] }
  // — and returns the set of card names. tag/reason are documentation for humans; the test keys on the
  // names. (Replaced the old flat-array allowlist format when the gold ratchets were de-ratcheted.)
  private static HashSet<string> LoadFixtureNameSet(string fileName)
  {
    var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Fixtures", fileName);
    var set = new HashSet<string>(StringComparer.Ordinal);
    if (!File.Exists(path))
    {
      return set;
    }

    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    if (doc.RootElement.TryGetProperty("entries", out var entries))
    {
      foreach (var e in entries.EnumerateArray())
      {
        if (e.TryGetProperty("card", out var c) && c.GetString() is { } name)
        {
          set.Add(name);
        }
      }
    }

    return set;
  }

  // Trivial normalization only: line endings + surrounding whitespace. Everything else (reminder
  // text, templating drift, reordering) is a real mismatch the smoke test is meant to surface.
  private static string Norm(string? s) => s is null ? "" : s.Replace("\r\n", "\n").Trim();

  /// <summary>
  /// Entry liveness — the third direction, and the one the file lacked while it was called an
  /// "allowlist". The two card-facing directions above only ever run for golds the loader still finds, so
  /// an entry naming a gold that was deleted or renamed was silently inert: dead weight asserting a fact
  /// about a fixture that no longer exists. That is precisely the drift ADR-0004 hunts (a hand-maintained
  /// claim with nothing checking it still refers to anything), and it is why this register is Evidence
  /// only for as long as every entry points at a live gold. Unlike the other two, this check does not need
  /// the gitignored corpus or bulk, so it holds on a clean checkout.
  /// </summary>
  [TestCaseSource(nameof(SyntheticRegisterEntries))]
  public void Synthetic_register_entry_names_a_live_gold(string card)
  {
    var gold = Path.Combine(
      TestContext.CurrentContext.TestDirectory,
      "Fixtures",
      "HandParsedCards",
      card.Replace('/', Path.DirectorySeparatorChar) + ".json"
    );

    Assert.That(
      File.Exists(gold),
      Is.True,
      $"Fixtures/synthetic-card-golds.json registers '{card}' as a synthetic gold, but no gold exists at "
        + $"Fixtures/HandParsedCards/{card}.json. The register may only name live golds — remove the entry "
        + "(or restore the gold). A dangling entry asserts nothing and hides the fact that it asserts "
        + "nothing."
    );
  }

  public static IEnumerable<string> SyntheticRegisterEntries() =>
    _syntheticGolds.Value.OrderBy(c => c, StringComparer.Ordinal);

  [TestCaseSource(
    typeof(HandParsedTestCaseLoader),
    nameof(HandParsedTestCaseLoader.GetTestCaseData)
  )]
  public void Gold_oracle_text_matches_corpus(CardTestCase testCase)
  {
    var corpus = _corpus.Value;
    if (corpus is null)
    {
      Assert.Ignore(
        "card-inputs.json absent — run the InteractionTriage flow to enable oracle-text fidelity checks."
      );
      return;
    }

    var name = testCase.InputNode["Name"]?.ToString();
    var goldText = testCase.InputNode["OracleText"]?.ToString();

    if (name is null)
    {
      Assert.Ignore($"Gold '{testCase.Name}' has no Input.Name — cannot validate.");
      return;
    }

    if (!corpus.TryGetValue(name, out var corpusText))
    {
      // The card is filtered out of the commander-legal-paper corpus. Fall back to the SUPERSET
      // authoritative source — the full Scryfall oracle bulk (oracle-cards.json) — and validate against
      // it exactly as we would against the corpus: a match validates, a mismatch is REAL drift gated by
      // the quarantine. The seed is verbatim Scryfall data, so a mismatch is a genuine signal.
      var seed = _oracleCards.Value;
      if (seed is not null && seed.TryGetValue(name, out var seedText) && seedText is not null)
      {
        var matchesSeed = Norm(goldText) == Norm(seedText);

        // Validated against the bulk → the name resolves, so it is not synthetic. Deregister it.
        Assert.That(
          _syntheticGolds.Value.Contains(testCase.Name),
          Is.False,
          $"'{testCase.Name}' card '{name}' is covered by the full Scryfall bulk (oracle-cards.json) and "
            + "so gets real validation — a printed card bears this name, so the gold is NOT synthetic. "
            + "Remove its entry from Fixtures/synthetic-card-golds.json."
        );

        if (_quarantine.Value.Contains(testCase.Name))
        {
          Assert.That(
            matchesSeed,
            Is.False,
            $"'{testCase.Name}' is on the oracle-text quarantine but its gold now MATCHES the Scryfall "
              + "bulk (oracle-cards.json). Remove it from Fixtures/oracle-text-quarantine.json — the "
              + "quarantine only shrinks."
          );
          return;
        }

        Assert.That(
          matchesSeed,
          Is.True,
          $"Gold oracle text for '{testCase.Name}' (card '{name}', filtered out of the corpus) differs "
            + "from the authoritative Scryfall bulk (oracle-cards.json).\n"
            + $"  gold:   {Norm(goldText)}\n"
            + $"  bulk:   {Norm(seedText)}\n"
            + "Fix the gold's Input.OracleText to match the real card. If this is known/intentional drift, "
            + "add it to Fixtures/oracle-text-quarantine.json (but prefer fixing the gold)."
        );
        return;
      }

      // The card is in NEITHER source (corpus nor full bulk), so it cannot be validated against any
      // authoritative source — the dangerous case (a wrong gold would slip through). LOUD failure UNLESS
      // the gold is registered as synthetic (no printed card bears the name).
      Assert.That(
        _syntheticGolds.Value.Contains(testCase.Name),
        Is.True,
        $"Gold '{testCase.Name}' card '{name}' is absent from the corpus (card-inputs.json) AND the full "
          + "Scryfall bulk (oracle-cards.json), so its oracle text CANNOT be validated against any "
          + "authoritative source — a wrong gold would slip through. Make the card present (preferred — "
          + "re-run the MagicAstTriage flow), or, only if truly unavoidable, add '"
          + testCase.Name
          + "' to Fixtures/synthetic-card-golds.json — but ONLY after checking, against the bulk, that "
          + "no printed card bears the name (the sibling golds in the same set folder should resolve)."
      );
      return;
    }

    // The card IS in the corpus now, so a printed card bears this name and the gold is not synthetic.
    Assert.That(
      _syntheticGolds.Value.Contains(testCase.Name),
      Is.False,
      $"'{testCase.Name}' is registered as a synthetic gold but its card '{name}' is in the corpus, so "
        + "a printed card bears this name and it can be validated. Remove its entry from "
        + "Fixtures/synthetic-card-golds.json."
    );

    var matches = Norm(goldText) == Norm(corpusText);
    var quarantined = _quarantine.Value.Contains(testCase.Name);

    if (quarantined)
    {
      Assert.That(
        matches,
        Is.False,
        $"'{testCase.Name}' is on the oracle-text quarantine but its gold oracle text now MATCHES the "
          + "corpus. Remove it from Fixtures/oracle-text-quarantine.json — the quarantine only shrinks."
      );
      return;
    }

    Assert.That(
      matches,
      Is.True,
      $"Gold oracle text for '{testCase.Name}' differs from the corpus (card-inputs.json).\n"
        + $"  gold:   {Norm(goldText)}\n"
        + $"  corpus: {Norm(corpusText)}\n"
        + "Fix the gold's Input.OracleText to match the real card. If this is intentional known drift, "
        + "add it to Fixtures/oracle-text-quarantine.json (but prefer fixing the gold)."
    );
  }
}
