namespace MagicAST.Tests.Tests;

using System.Text.Json;
using MagicAST.Tests.Infrastructure;

/// <summary>
/// Fidelity smoke test: a gold fixture's <c>Input.OracleText</c> must be the exact oracle text the
/// corpus parser consumes for that card (<c>card-inputs.json</c>, a faithful projection of Scryfall).
///
/// <para>
/// The per-card parser tests (<see cref="HandParsedCardTests"/>) cannot catch a wrong input string:
/// the expected AST and its <c>RawText</c> spans are sliced from the same <c>Input.OracleText</c>, so
/// a gold authored from the wrong card is internally self-consistent and parses green. This test is
/// the only thing that reaches an authoritative source, so it is the only thing that catches a gold
/// drifting from (or never matching) the real card.
/// </para>
///
/// <para>
/// Cards on <c>Fixtures/oracle-text-quarantine.json</c> are known pre-existing drift, exempt from the
/// match assertion. The quarantine is a ratchet that only shrinks: a quarantined gold that is fixed
/// (now matches) fails until removed from the list, and any gold NOT on the list must match — so no
/// new drift can land. See <c>libs/mast-interaction/docs/interaction-refinement-round2.md</c>.
/// </para>
///
/// <para>
/// The corpus (<c>card-inputs.json</c>) is only the commander-legal-paper SUBSET, so a gold whose card
/// is filtered out of it (digital-only, non-commander, un-cards) would otherwise be un-validatable — the
/// dangerous case, because such a gold parses green on pure self-consistency. The SUPERSET authoritative
/// source closes that hole: the full Scryfall oracle bulk (<see cref="TestData.OracleCardsPath"/>), a
/// faithful, verbatim projection regenerated by the <c>MagicAstTriage</c> Flowthru flow (gitignored, like
/// the corpus — neither is in version control; both are present once the flow has run). For an
/// absent-from-corpus gold it is consulted as a SECOND authoritative source, treated exactly like the
/// corpus: a MATCH validates (the gold must then NOT be on the uncovered allowlist), and a MISMATCH is
/// REAL drift — gated by the same <c>oracle-text-quarantine.json</c> as corpus drift (fix the gold, or
/// quarantine it if the mismatch is known/intentional). The seed is authoritative Scryfall data, so a
/// mismatch is a genuine signal, never suppressed.
/// </para>
///
/// <para>
/// Only a gold whose card is in NEITHER source (absent from the corpus AND from the full bulk) truly
/// cannot be validated; those go on <c>Fixtures/fidelity-uncovered-allowlist.json</c>. The allowlist is a
/// ratchet that only shrinks: once a gold's card appears in EITHER source it must be removed (it now gets
/// real validation), and no new absentee can land un-justified. Prefer making the card present over the
/// allowlist.
/// </para>
/// </summary>
[TestFixture]
public class GoldOracleTextFidelityTests
{
  // Name -> OracleText from the corpus the parser consumes; null when card-inputs.json is absent.
  private static readonly Lazy<Dictionary<string, string?>?> _corpus = new(LoadCorpus);

  // Name -> oracle_text from the full Scryfall oracle bulk (oracle-cards.json, gitignored; regenerated
  // by the MagicAstTriage flow); null when absent. The SUPERSET authoritative source for golds whose
  // card is filtered out of the commander-legal-paper corpus — see class doc + LoadOracleCards.
  private static readonly Lazy<Dictionary<string, string?>?> _oracleCards = new(LoadOracleCards);

  private static readonly Lazy<HashSet<string>> _quarantine = new(
    () => LoadFixtureNameSet("oracle-text-quarantine.json")
  );

  // testCase.Name set of golds whose card is currently absent from the corpus and so cannot be
  // validated — grandfathered, shrink-only (see class doc).
  private static readonly Lazy<HashSet<string>> _uncoveredAllowlist = new(
    () => LoadFixtureNameSet("fidelity-uncovered-allowlist.json")
  );

  private static Dictionary<string, string?>? LoadCorpus()
  {
    var path = TestData.CardInputsPath;
    if (!File.Exists(path))
    {
      return null;
    }

    var dict = new Dictionary<string, string?>(StringComparer.Ordinal);
    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    foreach (var rec in doc.RootElement.EnumerateArray())
    {
      if (!rec.TryGetProperty("Input", out var input))
      {
        continue;
      }

      var name = input.TryGetProperty("Name", out var n) ? n.GetString() : null;
      if (name is null || dict.ContainsKey(name))
      {
        continue;
      }

      dict[name] = input.TryGetProperty("OracleText", out var ot) ? ot.GetString() : null;
    }

    return dict;
  }

  // Loads the raw Scryfall seed (oracle-cards.json) as name -> oracle_text. snake_case schema, first
  // entry per name wins (mirrors the corpus loader). DFC/MDFC: top-level oracle_text is empty, so join
  // the per-face oracle_text with a blank line (the CensusStep idiom). Returns null when absent.
  private static Dictionary<string, string?>? LoadOracleCards()
  {
    var path = TestData.OracleCardsPath;
    if (!File.Exists(path))
    {
      return null;
    }

    var dict = new Dictionary<string, string?>(StringComparer.Ordinal);
    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    foreach (var rec in doc.RootElement.EnumerateArray())
    {
      var name = rec.TryGetProperty("name", out var n) ? n.GetString() : null;
      if (name is null || dict.ContainsKey(name))
      {
        continue;
      }

      var text = rec.TryGetProperty("oracle_text", out var ot) ? ot.GetString() : null;
      if (string.IsNullOrWhiteSpace(text) && rec.TryGetProperty("card_faces", out var faces))
      {
        text = string.Join(
          "\n\n",
          faces
            .EnumerateArray()
            .Select(f => f.TryGetProperty("oracle_text", out var fot) ? fot.GetString() : null)
            .Where(t => !string.IsNullOrEmpty(t))
        );
      }

      dict[name] = text;
    }

    return dict;
  }

  // Loads a committed Fixtures/*.json whitelist — { "entries": [ { "card": ..., "tag": ..., "reason": ... } ] }
  // — and returns the set of card names. tag/reason are documentation for humans; the test keys on the
  // names. (Replaced the old flat-array allowlist format when the gold ratchets were de-ratcheted.)
  private static HashSet<string> LoadFixtureNameSet(string fileName)
  {
    var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Fixtures", fileName);
    var set = new HashSet<string>(StringComparer.Ordinal);
    if (!File.Exists(path))
    {
      return set;
    }

    using var doc = JsonDocument.Parse(File.ReadAllText(path));
    if (doc.RootElement.TryGetProperty("entries", out var entries))
    {
      foreach (var e in entries.EnumerateArray())
      {
        if (e.TryGetProperty("card", out var c) && c.GetString() is { } name)
        {
          set.Add(name);
        }
      }
    }

    return set;
  }

  // Trivial normalization only: line endings + surrounding whitespace. Everything else (reminder
  // text, templating drift, reordering) is a real mismatch the smoke test is meant to surface.
  private static string Norm(string? s) => s is null ? "" : s.Replace("\r\n", "\n").Trim();

  [TestCaseSource(
    typeof(HandParsedTestCaseLoader),
    nameof(HandParsedTestCaseLoader.GetTestCaseData)
  )]
  public void Gold_oracle_text_matches_corpus(CardTestCase testCase)
  {
    var corpus = _corpus.Value;
    if (corpus is null)
    {
      Assert.Ignore(
        "card-inputs.json absent — run the InteractionTriage flow to enable oracle-text fidelity checks."
      );
      return;
    }

    var name = testCase.InputNode["Name"]?.ToString();
    var goldText = testCase.InputNode["OracleText"]?.ToString();

    if (name is null)
    {
      Assert.Ignore($"Gold '{testCase.Name}' has no Input.Name — cannot validate.");
      return;
    }

    if (!corpus.TryGetValue(name, out var corpusText))
    {
      // The card is filtered out of the commander-legal-paper corpus. Fall back to the SUPERSET
      // authoritative source — the full Scryfall oracle bulk (oracle-cards.json) — and validate against
      // it exactly as we would against the corpus: a match validates, a mismatch is REAL drift gated by
      // the quarantine. The seed is verbatim Scryfall data, so a mismatch is a genuine signal.
      var seed = _oracleCards.Value;
      if (seed is not null && seed.TryGetValue(name, out var seedText) && seedText is not null)
      {
        var matchesSeed = Norm(goldText) == Norm(seedText);

        // Validated against the bulk → must not still be on the can't-validate allowlist (shrink-only).
        Assert.That(
          _uncoveredAllowlist.Value.Contains(testCase.Name),
          Is.False,
          $"'{testCase.Name}' card '{name}' is covered by the full Scryfall bulk (oracle-cards.json) and "
            + "so gets real validation — it must NOT be on Fixtures/fidelity-uncovered-allowlist.json. "
            + "Remove it (the allowlist only shrinks)."
        );

        if (_quarantine.Value.Contains(testCase.Name))
        {
          Assert.That(
            matchesSeed,
            Is.False,
            $"'{testCase.Name}' is on the oracle-text quarantine but its gold now MATCHES the Scryfall "
              + "bulk (oracle-cards.json). Remove it from Fixtures/oracle-text-quarantine.json — the "
              + "quarantine only shrinks."
          );
          return;
        }

        Assert.That(
          matchesSeed,
          Is.True,
          $"Gold oracle text for '{testCase.Name}' (card '{name}', filtered out of the corpus) differs "
            + "from the authoritative Scryfall bulk (oracle-cards.json).\n"
            + $"  gold:   {Norm(goldText)}\n"
            + $"  bulk:   {Norm(seedText)}\n"
            + "Fix the gold's Input.OracleText to match the real card. If this is known/intentional drift, "
            + "add it to Fixtures/oracle-text-quarantine.json (but prefer fixing the gold)."
        );
        return;
      }

      // The card is in NEITHER source (corpus nor full bulk), so it cannot be validated against any
      // authoritative source — the dangerous case (a wrong gold would slip through). LOUD failure UNLESS
      // on the grandfathered, shrink-only allowlist.
      Assert.That(
        _uncoveredAllowlist.Value.Contains(testCase.Name),
        Is.True,
        $"Gold '{testCase.Name}' card '{name}' is absent from the corpus (card-inputs.json) AND the full "
          + "Scryfall bulk (oracle-cards.json), so its oracle text CANNOT be validated against any "
          + "authoritative source — a wrong gold would slip through. Make the card present (preferred — "
          + "re-run the MagicAstTriage flow), or, only if truly unavoidable, add '"
          + testCase.Name
          + "' to Fixtures/fidelity-uncovered-allowlist.json (the allowlist only shrinks)."
      );
      return;
    }

    // The card IS in the corpus now. If it is still on the uncovered allowlist, it gets real validation
    // and must be removed — the allowlist is a ratchet that only shrinks.
    Assert.That(
      _uncoveredAllowlist.Value.Contains(testCase.Name),
      Is.False,
      $"'{testCase.Name}' is on the fidelity uncovered allowlist but its card '{name}' is now in the "
        + "corpus and can be validated. Remove it from Fixtures/fidelity-uncovered-allowlist.json — the "
        + "allowlist only shrinks."
    );

    var matches = Norm(goldText) == Norm(corpusText);
    var quarantined = _quarantine.Value.Contains(testCase.Name);

    if (quarantined)
    {
      Assert.That(
        matches,
        Is.False,
        $"'{testCase.Name}' is on the oracle-text quarantine but its gold oracle text now MATCHES the "
          + "corpus. Remove it from Fixtures/oracle-text-quarantine.json — the quarantine only shrinks."
      );
      return;
    }

    Assert.That(
      matches,
      Is.True,
      $"Gold oracle text for '{testCase.Name}' differs from the corpus (card-inputs.json).\n"
        + $"  gold:   {Norm(goldText)}\n"
        + $"  corpus: {Norm(corpusText)}\n"
        + "Fix the gold's Input.OracleText to match the real card. If this is intentional known drift, "
        + "add it to Fixtures/oracle-text-quarantine.json (but prefer fixing the gold)."
    );
  }
}
