namespace MagicAST.Parsing.Parsers.Triggered.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// "another target creature you control gains [keyword] until end of turn." —
/// the effect clause of an attack/enter trigger that grants a keyword ability to
/// a chosen creature the controller controls, other than the source, for the
/// remainder of the turn. Covers Starry-Eyed Skyrider's attack trigger:
/// "Whenever this creature attacks, another target creature you control gains
/// flying until end of turn."
///
/// <para>
/// CR 603.1: triggered abilities have a trigger condition and an effect; this
/// rule handles the effect clause only (the trigger side is owned by
/// <see cref="AttacksConditionRule"/>). CR 611.2a: "A continuous effect
/// generated by the resolution of a spell or ability lasts as long as stated by
/// the spell or ability creating it (such as 'until end of turn')." CR 514.2:
/// all "until end of turn" effects end during the cleanup step — modelled as
/// <see cref="UntilTimeDuration.EndOfTurn"/>.
/// </para>
///
/// <para>
/// "another target creature you control" is a targeted reference
/// (<see cref="ObjectReferenceKind.Target"/>) whose filter carries two axes
/// distinct from the bare <see cref="TargetCreatureGainsKeywordUntilEndOfTurnRule"/>
/// ("target creature gains …"): <c>Controller = You</c> ("you control", CR
/// 109.5: "The words 'you' and 'your' on an object refer to the object's
/// controller …") and <c>ExcludeSelf = true</c> ("another" — codebase
/// convention mapping "another" to <see cref="ObjectFilter.ExcludeSelf"/>, per
/// GLOSSARY.md and <c>AnotherTargetModifyPTSpellRule</c>). The granted keyword
/// resolves through <see cref="TriggeredRuleHelpers.BuildKeywordStaticAbility"/>
/// (CR 702.9a/702.9b for flying); an unrecognised keyword bails so no free text
/// is emitted.
/// </para>
///
/// <para>
/// Anchored (^ … $) and prefixed with "another" so it can never substring-match
/// the sibling <c>^target creature gains …</c> surface, and vice versa.
/// </para>
/// </summary>
[TriggeredRule(Priority = 65)]
public sealed class AnotherTargetControlledCreatureGainsKeywordUntilEndOfTurnRule : ITriggeredRule
{
  private static readonly Regex _pattern = new(
    @"^another\s+target\s+creature\s+you\s+control\s+gains?\s+(?<keyword>[A-Za-z][a-z]+(?:\s+[a-z]+)?)\s+until\s+end\s+of\s+turn\.?$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    var m = _pattern.Match(text.Trim());
    if (!m.Success)
    {
      return false;
    }

    var rawKeyword = m.Groups["keyword"].Value;
    var ability = TriggeredRuleHelpers.BuildKeywordStaticAbility(rawKeyword);
    if (ability is null)
    {
      // Unrecognised keyword — bail so fallback handles it; no free text.
      return false;
    }

    effect = new GainAbilityEffect
    {
      Target = ObjectReference.Target(new ObjectFilter
      {
        CardTypes = ["creature"],
        Controller = ControllerFilter.You,
        ExcludeSelf = true,
      }),
      GainedAbility = ability,
      Duration = UntilTimeDuration.EndOfTurn,
    };
    return true;
  }
}
