namespace MagicAST.Parsing.Parsers.Triggered.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Keyword;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// "this creature gains [keyword] until end of turn." — grants a keyword
/// ability to the source permanent itself (self-reference, not a chosen
/// target) for the remainder of the turn. Covers Kalastria Nightwatch:
/// "Whenever you gain life, this creature gains flying until end of turn."
///
/// Rule 603.1: triggered abilities have a trigger condition and an effect;
/// this rule handles the effect clause. "This creature" is the source
/// permanent naming itself, modelled as <see cref="ObjectReferenceKind.Self"/>
/// (CR 611.1: continuous effects generated by resolving a one-shot effect
/// have a duration — here, "until end of turn").
///
/// Distinct from <see cref="TargetCreatureGainsKeywordUntilEndOfTurnRule"/>,
/// which grants the keyword to a separately chosen target creature, and
/// <see cref="ItGainsKeywordUntilEndOfTurnRule"/>, which grants it to the
/// anaphoric "it" (the object named by the trigger's own filter, e.g. an
/// entering creature) rather than the ability's source.
/// </summary>
[TriggeredRule(Priority = 60)]
public sealed class ThisCreatureGainsKeywordUntilEndOfTurnRule : ITriggeredRule
{
  private static readonly Regex _pattern = new(
    @"^this\s+creature\s+gains?\s+(?<keyword>[A-Za-z][a-z]+(?:\s+[a-z]+)?)\s+until\s+end\s+of\s+turn\.?$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    var m = _pattern.Match(text.Trim());
    if (!m.Success)
    {
      return false;
    }

    var rawKeyword = m.Groups["keyword"].Value;
    var ability = TriggeredRuleHelpers.BuildKeywordStaticAbility(rawKeyword);
    if (ability is null)
    {
      // Unrecognised keyword — bail so fallback handles it; no free text.
      return false;
    }

    effect = new GainAbilityEffect
    {
      Target = ObjectReference.Self(),
      GainedAbility = ability,
      Duration = UntilTimeDuration.EndOfTurn,
    };
    return true;
  }
}
