namespace MagicAST.AST.Effects.Damage;

using System.Text.Json.Serialization;
using MagicAST.AST.Abilities;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;
using MagicAST.Serialization.DiscriminatorAttributes;
using MagicAST.AST.Effects.Traits;

/// <summary>
/// "prevent [damage]"
/// </summary>
[OracleEffect("preventDamage")]
public sealed record PreventDamageEffect : ContinuousEffect
{
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public Quantity? Amount { get; init; }

  /// <summary>
  /// True if preventing all damage (no quantity limit).
  /// </summary>
  public bool All { get; init; }

  /// <summary>
  /// True for the one-shot "next instance of damage" shield — the Circle/Rune of
  /// Protection pattern: "The next time a [source] would deal damage to [recipient]
  /// this turn, prevent that damage." CR 615.8 (cited verbatim): "Some prevention
  /// effects generated by the resolution of a spell or ability refer to the next
  /// time a specific source would deal damage. These effects prevent the next
  /// instance of damage from that source, regardless of how much damage that is.
  /// Once an instance of damage from that source has been prevented, any subsequent
  /// instances of damage that would be dealt by that source are dealt normally."
  ///
  /// Distinct from <see cref="All"/> (every instance, no count) and from a literal
  /// <see cref="Amount"/> (a bounded number of damage points): this prevents exactly
  /// one instance of any size. The shield / which-instance bookkeeping is engine
  /// territory (per the descriptive-not-engine doctrine), mirroring how
  /// <see cref="MagicAST.AST.Effects.ZoneChange.RegenerateEffect"/> records a
  /// "next time it would be destroyed this turn" shield without modelling the
  /// replacement machinery. This is CR-615 prevention, not a replacement effect.
  /// </summary>
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public bool NextInstance { get; init; }

  /// <summary>
  /// True if only combat damage is prevented (oracle says "combat damage").
  /// False/absent means all damage (regardless of source type) is prevented.
  /// </summary>
  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
  public bool CombatOnly { get; init; }

  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public ObjectReference? Source { get; init; }

  [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
  public ObjectReference? Target { get; init; }
}
