using Flowthru.Data.Schema;

namespace MagicAtlas.Ast.Tests.Data._08_Reporting.Schemas;

/// <summary>
/// INTERACTION-ROLLUP artifacts (ADR-0003 §8, Migration Stage 0b). Generated by the
/// <c>InteractionRollup</c> flow from the hand-authored interaction golds
/// (<c>Fixtures/Interactions/golds/*.json</c>) — never hand-edited. Two schema types back four files:
/// <see cref="PortTopology"/> emits <c>port-topology.json</c> (lean) + <c>port-topology.cited.json</c>
/// (verbose), and <see cref="PortInteractions"/> emits <c>port-interactions.json</c> +
/// <c>port-interactions.cited.json</c>.
///
/// <para><b>Lean = strip(provenance) of cited.</b> There is ONE schema per artifact; the provenance
/// fields (<c>witnesses</c>, <c>desc</c>, <c>cr</c>, <c>corroborates</c>) are nullable. The step emits
/// the cited version with them populated and the lean version with them null. Flowthru's JSON serializer
/// runs with <c>DefaultIgnoreCondition = WhenWritingNull</c>, so the null provenance fields are simply
/// omitted from the lean files — the two files cannot drift (ADR-0003 §8). Nullable <c>parent</c> /
/// <c>corroborates</c> that happen to be null are likewise omitted (semantically identical to the Python
/// prototype's explicit <c>null</c>).</para>
/// </summary>
[FlowthruSchema]
public partial record PortTopology
{
  /// <summary>Provenance stamp — the generator identity, kept as the historical <c>tools/interaction-rollup</c> literal.</summary>
  [SerializedLabel("$generated")]
  public required string Generated { get; init; }

  /// <summary>The gold ids that fed this rollup (sorted).</summary>
  [SerializedLabel("$golds")]
  public required IReadOnlyList<string> Golds { get; init; }

  /// <summary>Event/State/Behavior kind → the stems seen carrying that kind (sorted).</summary>
  [SerializedLabel("kinds")]
  public required IReadOnlyDictionary<string, IReadOnlyList<string>> Kinds { get; init; }

  /// <summary>Stem → its topology entry, keyed by the is-a-spine stem name (sorted).</summary>
  [SerializedLabel("stems")]
  public required IReadOnlyDictionary<string, StemEntry> Stems { get; init; }

  /// <summary>Attribute axis → where it is seen and its value lattice (sorted).</summary>
  [SerializedLabel("attribute_axes")]
  public required IReadOnlyDictionary<string, AxisEntry> AttributeAxes { get; init; }
}

/// <summary>One stem's topology entry (is-a parent + kind + observed attribute set).</summary>
[FlowthruSchema]
public partial record StemEntry
{
  [SerializedLabel("kind")]
  public required string Kind { get; init; }

  /// <summary>The is-a parent (stem up to the last <c>:</c>), or null for a top-level stem (omitted when null).</summary>
  [SerializedLabel("parent")]
  public string? Parent { get; init; }

  [SerializedLabel("status")]
  public required string Status { get; init; }

  /// <summary>The distinct attribute keys seen on ports carrying this stem (sorted).</summary>
  [SerializedLabel("attrs")]
  public required IReadOnlyList<string> Attrs { get; init; }

  /// <summary>Provenance (cited only): the golds that witnessed this stem (sorted). Null → omitted in the lean file.</summary>
  [SerializedLabel("witnesses")]
  public IReadOnlyList<string>? Witnesses { get; init; }
}

/// <summary>One attribute axis' rollup: the stems that carry it, its value lattice, and whether any value
/// carried provenance or a polarity (an object-valued attribute).</summary>
[FlowthruSchema]
public partial record AxisEntry
{
  [SerializedLabel("stems")]
  public required IReadOnlyList<string> Stems { get; init; }

  [SerializedLabel("values_seen")]
  public required IReadOnlyList<string> ValuesSeen { get; init; }

  [SerializedLabel("carries_provenance_or_polarity")]
  public required bool CarriesProvenanceOrPolarity { get; init; }
}

/// <summary>
/// The generalized connection rules for novel pairs (ADR-0003 §8, artifact 2): the residual layer —
/// polarity table, match policies, guard registry, bridges + tier ceilings — each rule carrying its
/// promotion status (<c>observed</c> → <c>corroborated</c> → <c>confirmed</c>). A non-empty
/// <see cref="Conflicts"/> set fails the generation pass (the flow throws before this is ever emitted).
/// </summary>
[FlowthruSchema]
public partial record PortInteractions
{
  [SerializedLabel("$generated")]
  public required string Generated { get; init; }

  [SerializedLabel("$golds")]
  public required IReadOnlyList<string> Golds { get; init; }

  /// <summary>Rule-union conflicts (same id, different core). Always empty in an emitted artifact — a
  /// non-empty set throws before write. Present for shape-parity with the Python prototype.</summary>
  [SerializedLabel("conflicts")]
  public required IReadOnlyList<string> Conflicts { get; init; }

  [SerializedLabel("polarity")]
  public required IReadOnlyList<RuleEntry> Polarity { get; init; }

  [SerializedLabel("match_policy")]
  public required IReadOnlyList<RuleEntry> MatchPolicy { get; init; }

  [SerializedLabel("guards")]
  public required IReadOnlyList<RuleEntry> Guards { get; init; }

  [SerializedLabel("bridges")]
  public required IReadOnlyList<RuleEntry> Bridges { get; init; }
}

/// <summary>
/// One residual rule across any section. The section-specific core fields are nullable and only populated
/// for the owning section (the others are omitted by the WhenWritingNull serializer), so a single record
/// type covers polarity / match_policy / guards / bridges. Provenance fields (<c>witnesses</c>,
/// <c>desc</c>, <c>cr</c>, <c>corroborates</c>) are populated only in the cited artifact.
/// </summary>
[FlowthruSchema]
public partial record RuleEntry
{
  [SerializedLabel("id")]
  public required string Id { get; init; }

  // polarity core
  [SerializedLabel("attr")]
  public string? Attr { get; init; }

  [SerializedLabel("context")]
  public string? Context { get; init; }

  [SerializedLabel("value")]
  public string? Value { get; init; }

  // match_policy core
  [SerializedLabel("consume_kind")]
  public string? ConsumeKind { get; init; }

  [SerializedLabel("subject")]
  public string? Subject { get; init; }

  // guards core
  [SerializedLabel("impl")]
  public string? Impl { get; init; }

  // bridges core
  [SerializedLabel("from_stem")]
  public string? FromStem { get; init; }

  [SerializedLabel("to_stem")]
  public string? ToStem { get; init; }

  [SerializedLabel("ceiling")]
  public string? Ceiling { get; init; }

  [SerializedLabel("status")]
  public required string Status { get; init; }

  /// <summary>Bridge from-side attribute filter (present on bridge rules in both lean and cited).</summary>
  [SerializedLabel("from_attrs")]
  public IReadOnlyDictionary<string, string>? FromAttrs { get; init; }

  // provenance (cited only)
  [SerializedLabel("witnesses")]
  public IReadOnlyList<string>? Witnesses { get; init; }

  [SerializedLabel("desc")]
  public string? Desc { get; init; }

  [SerializedLabel("cr")]
  public IReadOnlyList<string>? Cr { get; init; }

  [SerializedLabel("corroborates")]
  public string? Corroborates { get; init; }
}
