using Flowthru.Data.Schema;

namespace MagicAtlas.Ast.Tests.Data._08_Reporting.Schemas;

/// <summary>
/// INTERACTION-ROLLUP artifacts (ADR-0003 §8, Migration Stage 0b). Generated by the
/// <c>InteractionRollup</c> flow from the hand-authored interaction golds
/// (<c>Fixtures/Interactions/golds/*.json</c>) — never hand-edited. Two schema types back four files:
/// <see cref="PortTopology"/> emits <c>port-topology.json</c> (lean) + <c>port-topology.cited.json</c>
/// (verbose), and <see cref="PortInteractions"/> emits <c>port-interactions.json</c> +
/// <c>port-interactions.cited.json</c>.
///
/// <para><b>Lean = strip(provenance) of cited.</b> There is ONE schema per artifact; the provenance
/// fields (<c>witnesses</c>, <c>desc</c>, <c>cr</c>, <c>corroborates</c>) are nullable. The step emits
/// the cited version with them populated and the lean version with them null. Flowthru's JSON serializer
/// runs with <c>DefaultIgnoreCondition = WhenWritingNull</c>, so the null provenance fields are simply
/// omitted from the lean files — the two files cannot drift (ADR-0003 §8). Nullable <c>parent</c> /
/// <c>corroborates</c> that happen to be null are likewise omitted (semantically identical to the Python
/// prototype's explicit <c>null</c>).</para>
/// </summary>
[FlowthruSchema]
public partial record PortTopology
{
  /// <summary>Provenance stamp — the generator identity, kept as the historical <c>tools/interaction-rollup</c> literal.</summary>
  [SerializedLabel("$generated")]
  public required string Generated { get; init; }

  /// <summary>The gold ids that fed this rollup (sorted).</summary>
  [SerializedLabel("$golds")]
  public required IReadOnlyList<string> Golds { get; init; }

  /// <summary>Event/State/Behavior kind → its definition (pass-through from the topology scaffold).</summary>
  [SerializedLabel("kinds")]
  public required IReadOnlyDictionary<string, string> Kinds { get; init; }

  /// <summary>The six supergroups (kind-view + definition) — the DECLARED half from the scaffold.</summary>
  [SerializedLabel("supergroups")]
  public required IReadOnlyDictionary<string, SupergroupEntry> Supergroups { get; init; }

  /// <summary>Bare EVENT verbs with no supergroup (dice/damage/combat-presence) — scaffold pass-through.</summary>
  [SerializedLabel("event_verbs")]
  public required IReadOnlyDictionary<string, EventVerbEntry> EventVerbs { get; init; }

  /// <summary>Stem → its topology entry, keyed by the is-a-spine stem name (sorted). The DECLARED half
  /// (scaffold <c>stems_representative</c>) unioned with the WITNESSED half (gold-projected stems).</summary>
  [SerializedLabel("stems")]
  public required IReadOnlyDictionary<string, StemEntry> Stems { get; init; }

  /// <summary>Attribute axis → its scaffold-declared licensing/lattice unioned with the gold-witnessed
  /// value lattice (sorted).</summary>
  [SerializedLabel("attribute_axes")]
  public required IReadOnlyDictionary<string, AxisEntry> AttributeAxes { get; init; }

  /// <summary>Named attribute-constraints (aliases / slang views) — scaffold pass-through.</summary>
  [SerializedLabel("aliases")]
  public required IReadOnlyDictionary<string, string> Aliases { get; init; }

  /// <summary>The six declared holes — the <c>witness:sought</c> targeted-witnessing backlog (scaffold).</summary>
  [SerializedLabel("holes")]
  public required IReadOnlyDictionary<string, HoleEntry> Holes { get; init; }
}

/// <summary>A supergroup — a VIEW over stems that may span kinds (scaffold-declared).</summary>
[FlowthruSchema]
public partial record SupergroupEntry
{
  [SerializedLabel("kind_view")]
  public required string KindView { get; init; }

  [SerializedLabel("def")]
  public required string Def { get; init; }
}

/// <summary>A bare EVENT verb with no supergroup (dice-rolled / damage-dealt / combat-presence).</summary>
[FlowthruSchema]
public partial record EventVerbEntry
{
  [SerializedLabel("kind")]
  public required string Kind { get; init; }

  [SerializedLabel("def")]
  public required string Def { get; init; }
}

/// <summary>A declared hole — a proposed stem with no witness yet (<c>status: sought</c>).</summary>
[FlowthruSchema]
public partial record HoleEntry
{
  [SerializedLabel("priority")]
  public required int Priority { get; init; }

  [SerializedLabel("kind")]
  public required string Kind { get; init; }

  [SerializedLabel("proposed_stem")]
  public required string ProposedStem { get; init; }

  [SerializedLabel("attrs")]
  public IReadOnlyList<string>? Attrs { get; init; }

  [SerializedLabel("slang")]
  public IReadOnlyList<string>? Slang { get; init; }

  [SerializedLabel("note")]
  public string? Note { get; init; }

  /// <summary>Always <c>sought</c> — the hole is declared but not yet witnessed (ADR-0003 §8).</summary>
  [SerializedLabel("status")]
  public required string Status { get; init; }
}

/// <summary>One stem's topology entry (is-a parent + kind + observed attribute set + declared|witnessed status).</summary>
[FlowthruSchema]
public partial record StemEntry
{
  [SerializedLabel("kind")]
  public required string Kind { get; init; }

  /// <summary>The is-a parent (scaffold-declared, else stem up to the last <c>:</c>), or null for a top-level stem.</summary>
  [SerializedLabel("parent")]
  public string? Parent { get; init; }

  /// <summary><c>witnessed</c> if any gold projects this stem, else <c>declared</c> (scaffold-only).</summary>
  [SerializedLabel("status")]
  public required string Status { get; init; }

  /// <summary>The distinct attribute keys seen on ports carrying this stem (sorted).</summary>
  [SerializedLabel("attrs")]
  public required IReadOnlyList<string> Attrs { get; init; }

  /// <summary>A gold projects this stem but the scaffold never predicted it (the "witnessed but never
  /// predicted" diff). Omitted (null) when the stem was predicted.</summary>
  [SerializedLabel("unpredicted")]
  public bool? Unpredicted { get; init; }

  /// <summary>Provenance (cited only): the golds that witnessed this stem (sorted). Null → omitted (lean,
  /// and any declared-only stem with no witnesses).</summary>
  [SerializedLabel("witnesses")]
  public IReadOnlyList<string>? Witnesses { get; init; }
}

/// <summary>One attribute axis: the scaffold-declared closed-set licensing/lattice unioned with the
/// gold-witnessed stems + value lattice.</summary>
[FlowthruSchema]
public partial record AxisEntry
{
  /// <summary>Stems that carry this axis in the golds (witnessed; empty for a declared-only axis).</summary>
  [SerializedLabel("stems")]
  public required IReadOnlyList<string> Stems { get; init; }

  /// <summary>The value lattice actually witnessed in the golds (empty for a declared-only axis).</summary>
  [SerializedLabel("values_seen")]
  public required IReadOnlyList<string> ValuesSeen { get; init; }

  [SerializedLabel("carries_provenance_or_polarity")]
  public required bool CarriesProvenanceOrPolarity { get; init; }

  // ── scaffold-declared licensing / lattice (pass-through; omitted when absent) ──

  [SerializedLabel("licensed_by")]
  public IReadOnlyList<string>? LicensedBy { get; init; }

  [SerializedLabel("lattice")]
  public string? Lattice { get; init; }

  [SerializedLabel("enum")]
  public IReadOnlyList<string>? Enum { get; init; }

  [SerializedLabel("bindable")]
  public IReadOnlyList<string>? Bindable { get; init; }

  [SerializedLabel("kind")]
  public string? Kind { get; init; }

  [SerializedLabel("note")]
  public string? Note { get; init; }
}

/// <summary>
/// The generalized connection rules for novel pairs (ADR-0003 §8, artifact 2): the residual layer —
/// polarity table, match policies, guard registry, bridges + tier ceilings — each rule carrying its
/// promotion status (<c>observed</c> → <c>corroborated</c> → <c>confirmed</c>). A non-empty
/// <see cref="Conflicts"/> set fails the generation pass (the flow throws before this is ever emitted).
/// </summary>
[FlowthruSchema]
public partial record PortInteractions
{
  [SerializedLabel("$generated")]
  public required string Generated { get; init; }

  [SerializedLabel("$golds")]
  public required IReadOnlyList<string> Golds { get; init; }

  /// <summary>Rule-union conflicts (same id, different core). Always empty in an emitted artifact — a
  /// non-empty set throws before write. Present for shape-parity with the Python prototype.</summary>
  [SerializedLabel("conflicts")]
  public required IReadOnlyList<string> Conflicts { get; init; }

  [SerializedLabel("polarity")]
  public required IReadOnlyList<RuleEntry> Polarity { get; init; }

  [SerializedLabel("match_policy")]
  public required IReadOnlyList<RuleEntry> MatchPolicy { get; init; }

  [SerializedLabel("guards")]
  public required IReadOnlyList<RuleEntry> Guards { get; init; }

  [SerializedLabel("bridges")]
  public required IReadOnlyList<RuleEntry> Bridges { get; init; }
}

/// <summary>
/// One residual rule across any section. The section-specific core fields are nullable and only populated
/// for the owning section (the others are omitted by the WhenWritingNull serializer), so a single record
/// type covers polarity / match_policy / guards / bridges. Provenance fields (<c>witnesses</c>,
/// <c>desc</c>, <c>cr</c>, <c>corroborates</c>) are populated only in the cited artifact.
/// </summary>
[FlowthruSchema]
public partial record RuleEntry
{
  [SerializedLabel("id")]
  public required string Id { get; init; }

  // polarity core
  [SerializedLabel("attr")]
  public string? Attr { get; init; }

  [SerializedLabel("context")]
  public string? Context { get; init; }

  [SerializedLabel("value")]
  public string? Value { get; init; }

  // match_policy core
  [SerializedLabel("consume_kind")]
  public string? ConsumeKind { get; init; }

  [SerializedLabel("subject")]
  public string? Subject { get; init; }

  // guards core
  [SerializedLabel("impl")]
  public string? Impl { get; init; }

  // bridges core
  [SerializedLabel("from_stem")]
  public string? FromStem { get; init; }

  [SerializedLabel("to_stem")]
  public string? ToStem { get; init; }

  [SerializedLabel("ceiling")]
  public string? Ceiling { get; init; }

  [SerializedLabel("status")]
  public required string Status { get; init; }

  /// <summary>Bridge from-side attribute filter (present on bridge rules in both lean and cited).</summary>
  [SerializedLabel("from_attrs")]
  public IReadOnlyDictionary<string, string>? FromAttrs { get; init; }

  // provenance (cited only)
  [SerializedLabel("witnesses")]
  public IReadOnlyList<string>? Witnesses { get; init; }

  [SerializedLabel("desc")]
  public string? Desc { get; init; }

  [SerializedLabel("cr")]
  public IReadOnlyList<string>? Cr { get; init; }

  [SerializedLabel("corroborates")]
  public string? Corroborates { get; init; }
}
