using Flowthru.Data.Schema;

namespace MagicAtlas.Ast.Tests.Data._08_Reporting.Schemas;

/// <summary>
/// VALUE-RANKED DEMAND OVERLAY for the ADR-3 topology (a corpus-gated DIAGNOSTIC, never a gate). Ranks the
/// rankable topology concepts — witnessed stems, the six sought holes, and the supergroups — by how much
/// combo demand each carries, so the taxonomy-redesign TDD loop can pick a sought stem/hole by DEMAND
/// rather than hand priority. Two demand signals per concept:
/// <list type="bullet">
///   <item><b>witnessed</b> — Σ <c>source.popularity</c> over the golds that witness the stem (the
///     provenance-side demand; witnessed stems only).</item>
///   <item><b>corpus</b> — Σ <c>popularityMass</c> over Commander-Spellbook combo anchors whose payoffs
///     name the concept (a coarse slang overlay of the corpus-side demand).</item>
/// </list>
///
/// <para><b>Honesty caveat (encoded, not hidden).</b> Payoff-matching measures PAYOFF-side demand, so it
/// under-counts ENABLER concepts (cost-modification / restriction-grant produce no combo payoff string)
/// and fairly counts PAYOFF concepts (prevention → "Prevent all damage…"; untap → "Infinite untap…"). It
/// is NOT ground truth — the real per-stem demand join lands at Migration Stage 4 when the engine emits
/// ADR-3 ports. See <see cref="Note"/>.</para>
///
/// <para>Corpus-derived → written next to the other corpus reports (<c>Data/_08_Reporting/</c>,
/// gitignored), regenerated by re-running the flow after <c>nx run mast:combo-anchors</c>; never committed.
/// If the combo-anchor report is absent (worktree / no corpus) the overlay degrades gracefully — corpus
/// signals null, holes ranked by hand priority only.</para>
/// </summary>
[FlowthruSchema]
public partial record PortTopologyDemand
{
  /// <summary>The honesty caveat + corpus-availability statement (read this first).</summary>
  [SerializedLabel("$note")]
  public required string Note { get; init; }

  [SerializedLabel("$generated")]
  public required string Generated { get; init; }

  /// <summary>False when the combo-anchor report was absent — all <c>corpus</c> signals are then null.</summary>
  [SerializedLabel("$corpus_available")]
  public required bool CorpusAvailable { get; init; }

  /// <summary>Witnessed stems, ranked by <c>demand.witnessed</c> (gold popularity) DESC.</summary>
  [SerializedLabel("witnessed_stems")]
  public required IReadOnlyList<DemandEntry> WitnessedStems { get; init; }

  /// <summary>Declared-only stems (no gold witness yet), ranked by <c>demand.corpus</c> DESC.</summary>
  [SerializedLabel("declared_stems")]
  public required IReadOnlyList<DemandEntry> DeclaredStems { get; init; }

  /// <summary>The sought holes, ranked by <c>demand.corpus</c> DESC then <c>priority</c> ASC.</summary>
  [SerializedLabel("holes")]
  public required IReadOnlyList<DemandEntry> Holes { get; init; }

  /// <summary>The supergroups, ranked by rolled-up <c>demand.corpus</c> DESC.</summary>
  [SerializedLabel("supergroups")]
  public required IReadOnlyList<DemandEntry> Supergroups { get; init; }
}

/// <summary>One rankable concept's demand entry.</summary>
[FlowthruSchema]
public partial record DemandEntry
{
  [SerializedLabel("concept")]
  public required string Concept { get; init; }

  [SerializedLabel("kind")]
  public string? Kind { get; init; }

  /// <summary><c>witnessed</c> | <c>declared</c> | <c>sought</c> | <c>supergroup</c>.</summary>
  [SerializedLabel("status")]
  public required string Status { get; init; }

  [SerializedLabel("demand")]
  public required DemandCounts Demand { get; init; }

  /// <summary>Hand priority (holes only; the tiebreak, not the primary rank key).</summary>
  [SerializedLabel("priority")]
  public int? Priority { get; init; }

  /// <summary>The distinct combo payoff strings that matched — the citation / audit trail. Null → omitted.</summary>
  [SerializedLabel("matched_payoffs")]
  public IReadOnlyList<string>? MatchedPayoffs { get; init; }

  /// <summary>An honesty annotation — e.g. the enabler-side / payoff-invisible caveat. Null → omitted.</summary>
  [SerializedLabel("note")]
  public string? Note { get; init; }
}

/// <summary>The two demand signals. A null <c>corpus</c> means the overlay was unavailable (degrade path).</summary>
[FlowthruSchema]
public partial record DemandCounts
{
  /// <summary>Σ gold <c>source.popularity</c> over the concept's witnesses (witnessed stems only; else null).</summary>
  [SerializedLabel("witnessed")]
  public long? Witnessed { get; init; }

  /// <summary>Σ combo <c>popularityMass</c> over anchors whose payoffs name the concept. Null when the
  /// combo-anchor report was absent.</summary>
  [SerializedLabel("corpus")]
  public long? Corpus { get; init; }
}
