using Flowthru.Flow;
using MagicAtlas.Data;
using MagicAtlas.Data._02_Intermediate.Schemas;
using MagicAtlas.Data._08_Reporting.Schemas;
using MagicAtlas.Flows.CardAtlas.Steps;

namespace MagicAtlas.Flows.CardAtlas;

/// <summary>
/// The CardAtlas data layer (D1–D4) — the "shape → buildable" datasets the explorer/exploiter reviews
/// found missing, generated by MAST over the parse-ready CSB combo-card union (offline; committed
/// combos.json + card-inputs.json):
/// <list type="bullet">
///   <item><b>D1 CardPorts</b> → card-meta.json + card-ports.json: the card↔port index + colour/CMC/type.</item>
///   <item><b>D4 ComboInstances</b> → combo-instances.json: per-combo reconstructed loops (named cards,
///     tier, result, family-signature).</item>
///   <item><b>D2 ResourceGraph</b> → resource-graph.json: the family subway map, realized-combo-annotated.</item>
///   <item><b>D3 ArchetypeCatalog</b> → archetype-catalog.json: the realized combo-shape catalog.</item>
/// </list>
/// Datasets flow UI→API→DATA in reverse: the persona user stories drove these shapes. Diagnostics; never gates.
///
/// <para>Promoted from tests/magic-ast-tests/Flows/CardAtlas/CardAtlasFlow.cs into this shippable library
/// (upstream-atlas-data-plan §0/§6 P0) so production — not the test assembly — emits the D1–D4 dumps.
/// Outputs land under <c>{basePath}/_08_Reporting/dumps/</c> (see <c>Catalog.Reporting</c>).</para>
/// </summary>
public static class CardAtlasFlow
{
  public static BuiltFlow Create(Catalog catalog, string ontologyPath) =>
    FlowBuilder.CreateFlow(
      "CardAtlas",
      pipeline =>
      {
        // D1 — the card↔port index + metadata (keystone).
        pipeline.AddStep<
          IEnumerable<Combo>,
          IEnumerable<MastCardInput>,
          IEnumerable<CardMetaRow>,
          IEnumerable<CardPortRow>
        >(
          label: "CardPorts",
          transform: CardPortsStep.Create(ontologyPath),
          inputs: (catalog.Combos, catalog.CardInputs),
          outputs: (catalog.CardMeta, catalog.CardPorts)
        );

        // D4 — per-combo reconstructed loops (named cards + tier + result), plus the wide
        // reconstruction-recall measurement co-produced from the same per-combo pass.
        pipeline.AddStep<
          IEnumerable<Combo>,
          IEnumerable<MastCardInput>,
          IEnumerable<ComboInstanceRow>,
          ExtendedRecallReport
        >(
          label: "ReconstructCombos",
          transform: ReconstructCombosStep.Create(ontologyPath),
          inputs: (catalog.Combos, catalog.CardInputs),
          outputs: (catalog.ComboInstances, catalog.ExtendedRecall)
        );

        // D2 + D3 — the family rollups (aggregated from D1 + D4, no re-materialize).
        pipeline.AddStep<
          IEnumerable<CardPortRow>,
          IEnumerable<ComboInstanceRow>,
          ResourceGraph,
          ArchetypeCatalog
        >(
          label: "FamilyRollup",
          transform: FamilyRollupStep.Create(),
          inputs: (catalog.CardPorts, catalog.ComboInstances),
          outputs: (catalog.ResourceGraph, catalog.ArchetypeCatalog)
        );
      }
    );
}
