namespace MagicAST.Parsing.Parsers.Spell.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// Recognises the mass P/T-modification shape for creature subsets where the
/// power and/or toughness modifiers are the spell's announced X (rather than a
/// literal number):
///   "All creatures get +X/-X until end of turn."               (Flowstone Slide)
///
/// Sibling group to <see cref="MassAnthemSpellRule"/> (which requires a
/// LITERAL digit in both slots — its <c>\d+</c> pattern never matches an
/// X/Y/Z letter, so the two rules are disjoint by construction, no dispatch
/// priority needed) and to <see cref="ModifyPTBothVariableSpellRule"/> (which
/// covers the same X-scaled shape but for a SINGLE "Target creature" subject
/// rather than a mass creature-subset subject).
///
/// <para>
/// CR 107.3a: "Some spells and abilities have an 'X' in their costs. ... The
/// player announces the value of X when casting the spell." CR 107.3i:
/// "Normally, all instances of X on an object have the same value at any given
/// time." — the same announced X is referenced by both P/T slots here, so both
/// share one <see cref="VariableQuantity"/> letter; a negative slot ("-X")
/// negates that same value via a <see cref="CalculatedQuantity"/> multiply-by
/// -1 wrapper (mirroring how <c>ScentOfNightshade.json</c>'s gold AST negates
/// a non-X quantity for its own "-X/-X" shape).
/// </para>
///
/// <para>
/// CR 611.2: a continuous effect may be generated by the resolution of a spell
/// — "All creatures get +X/-X until end of turn" is such a one-shot continuous
/// effect, in scope only until end of turn. CR 613.4c (Layer 7c): "Effects and
/// counters that modify power and/or toughness (but don't set power and/or
/// toughness to a specific number or value) are applied" — a P/T modification,
/// hence <see cref="ModifyPTEffect"/>, not a set-P/T effect.
/// </para>
///
/// Examples:
/// <list type="bullet">
///   <item>"All creatures get +X/-X until end of turn."  (Flowstone Slide)</item>
/// </list>
/// </summary>
[SpellRule]
public sealed class MassModifyPTVariableSpellRule : ISpellRule
{
  // Named capture groups mirror MassAnthemSpellRule's subject alternation, but
  // require an X/Y/Z variable (with its own sign) in each P/T slot instead of a
  // literal digit.
  private static readonly Regex _pattern = new(
    @"^(?<subj>All\s+creatures|Creatures\s+you\s+control|Creatures\s+your\s+opponents\s+control|Attacking\s+creatures|Blocking\s+creatures)"
    + @"\s+get\s+(?<psign>[+\-])(?<pvar>[XYZ])/(?<tsign>[+\-])(?<tvar>[XYZ])\s+until\s+end\s+of\s+turn$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    var m = _pattern.Match(text.Trim());
    if (!m.Success)
    {
      return false;
    }

    var subj = m.Groups["subj"].Value;
    var powerVar = m.Groups["pvar"].Value.ToUpperInvariant();
    var toughnessVar = m.Groups["tvar"].Value.ToUpperInvariant();
    var powerNegative = m.Groups["psign"].Value == "-";
    var toughnessNegative = m.Groups["tsign"].Value == "-";

    effect = new ModifyPTEffect
    {
      Target = new ObjectReference
      {
        Kind = ObjectReferenceKind.Each,
        Filter = BuildFilter(subj),
      },
      PowerModifier = BuildModifier(powerVar, powerNegative),
      ToughnessModifier = BuildModifier(toughnessVar, toughnessNegative),
      Duration = UntilTimeDuration.EndOfTurn,
    };
    return true;
  }

  private static Quantity BuildModifier(string variableName, bool negative)
  {
    var variable = new VariableQuantity { Name = variableName };
    if (!negative)
    {
      return variable;
    }

    return new CalculatedQuantity
    {
      BaseQuantity = variable,
      Operation = "multiply",
      Operand = -1,
    };
  }

  private static ObjectFilter BuildFilter(string subj)
  {
    var s = subj.Trim();

    if (s.Equals("Creatures you control", StringComparison.OrdinalIgnoreCase))
    {
      return new ObjectFilter
      {
        CardTypes = ["creature"],
        Controller = ControllerFilter.You,
      };
    }

    if (s.Equals("Creatures your opponents control", StringComparison.OrdinalIgnoreCase))
    {
      return new ObjectFilter
      {
        CardTypes = ["creature"],
        Controller = ControllerFilter.Opponent,
      };
    }

    if (s.Equals("Attacking creatures", StringComparison.OrdinalIgnoreCase))
    {
      return new ObjectFilter
      {
        CardTypes = ["creature"],
        Characteristics = [Characteristic.InCombat(CombatState.Attacking)],
      };
    }

    if (s.Equals("Blocking creatures", StringComparison.OrdinalIgnoreCase))
    {
      return new ObjectFilter
      {
        CardTypes = ["creature"],
        Characteristics = [Characteristic.InCombat(CombatState.Blocking)],
      };
    }

    // "All creatures" — no controller restriction.
    return new ObjectFilter
    {
      CardTypes = ["creature"],
    };
  }
}
