namespace MagicAST.Parsing.Parsers.Spell.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.CardFlow;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// Two-sentence compound spell of the "pump-then-conditional-draw" shape:
///   "Target creature gets -N/-M until end of turn. If &lt;condition&gt;, draw &lt;count&gt; card(s)."
///
/// <para>
/// Representative card: Chilling Trap —
/// "Target creature gets -4/-0 until end of turn. If you control a Wizard, draw a card."
/// </para>
///
/// <para>
/// Sentence 1 is a <see cref="ModifyPTEffect"/> targeting a creature with an end-of-turn
/// <see cref="ContinuousEffect.Duration"/>. Sentence 2 is a <see cref="DrawCardsEffect"/>
/// guarded by its own <see cref="DrawCardsEffect.Condition"/> (the standard structured slot
/// for the "If &lt;condition&gt;, draw a card" idiom — see <c>ReturnKickedDrawRule</c>). The
/// two effects sit as siblings on <see cref="MagicAST.AST.Abilities.SpellAbility.Effects"/>;
/// the condition is descriptive, not a runtime branch (ADR 0004: MAST describes, does not
/// execute). The condition phrase is structured by <see cref="MagicAST.Parsing.ConditionParser"/>
/// — "you control a Wizard" becomes a subtype <c>CountCondition</c>.
/// </para>
///
/// <para>
/// This is a <see cref="IMultiSpellRule"/>: the shape always yields two sibling effects and
/// is anchored to the FULL two-sentence text (sentence 1 MUST be the ModifyPT form), so it
/// cannot collide with the generic sentence-bundle path or with any sibling that shares only
/// the conditional-draw tail.
/// </para>
///
/// <para>
/// CR 121.1: "A player draws a card by putting the top card of their library into their hand."
/// CR 611.2: a continuous effect may be generated by the resolution of a spell (the P/T buff).
/// </para>
/// </summary>
[SpellRule(Priority = 80)]
public sealed class ModifyPTThenConditionalDrawRule : ISpellRule, IMultiSpellRule
{
  // Sentence 1: "Target creature gets -N/-M until end of turn"
  private static readonly Regex Sentence1 = new(
    @"^Target\s+creature\s+gets\s+(?<p>[+\-]\d+)/(?<t>[+\-]\d+)\s+until\s+end\s+of\s+turn$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Sentence 2: "If <condition>, draw <count> card(s)"
  private static readonly Regex Sentence2 = new(
    @"^If\s+(?<cond>.+?),\s+draw\s+(?<count>a|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s+cards?$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Full two-sentence split: sentence 1 ends at the first ". " before the "If ..." tail.
  private static readonly Regex TwoSentence = new(
    @"^(?<s1>Target\s+creature\s+gets\s+[+\-]\d+/[+\-]\d+\s+until\s+end\s+of\s+turn)\.\s+(?<s2>If\s+.+)$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  /// <inheritdoc/>
  /// <remarks>Returns <c>false</c> unconditionally — this shape always produces two
  /// sibling effects; callers must use <see cref="TryMatchMulti"/>.</remarks>
  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    return false;
  }

  /// <inheritdoc/>
  public bool TryMatchMulti(string text, out IReadOnlyList<Effect>? effects)
  {
    effects = null;

    var full = text.Trim().TrimEnd('.');
    var split = TwoSentence.Match(full);
    if (!split.Success)
    {
      return false;
    }

    var m1 = Sentence1.Match(split.Groups["s1"].Value.Trim());
    if (!m1.Success)
    {
      return false;
    }

    var m2 = Sentence2.Match(split.Groups["s2"].Value.Trim().TrimEnd('.'));
    if (!m2.Success)
    {
      return false;
    }

    var power = int.Parse(m1.Groups["p"].Value);
    var toughness = int.Parse(m1.Groups["t"].Value);

    var modifyEffect = new ModifyPTEffect
    {
      Target = new ObjectReference
      {
        Kind = ObjectReferenceKind.Target,
        Filter = new ObjectFilter { CardTypes = ["creature"] },
      },
      PowerModifier = LiteralQuantity.Of(power),
      ToughnessModifier = LiteralQuantity.Of(toughness),
      Duration = UntilTimeDuration.EndOfTurn,
    };

    var drawCount = SpellRuleHelpers.ParseSmallWord(m2.Groups["count"].Value);
    var drawEffect = new DrawCardsEffect
    {
      Count = LiteralQuantity.Of(drawCount),
      Player = ObjectReference.You(),
      Condition = MagicAST.Parsing.ConditionParser.Parse(m2.Groups["cond"].Value.Trim()),
    };

    effects = [modifyEffect, drawEffect];
    return true;
  }
}
