namespace MagicAST.Parsing.Parsers.Spell.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.References;

/// <summary>
/// "The next time a source of your choice would deal damage to you this turn,
/// prevent that damage." — the uncoloured one-shot prevention shield printed as a
/// spell (instant/sorcery) resolution effect, e.g. Intervention Pact, Reverse
/// Damage, Invulnerability, New Way Forward, Deflecting Palm.
///
/// <para>
/// This is the spell-ability counterpart of
/// <see cref="MagicAST.Parsing.Parsers.Activated.Rules.PreventNextDamageFromChosenSourceEffectRule"/>
/// (the same shield printed as an activated ability on Pentagram of the Ages,
/// Haazda Shield Mate, Righteous Aura). It emits the identical
/// <see cref="PreventDamageEffect"/> shape: <see cref="PreventDamageEffect.NextInstance"/>
/// set (the "next instance, regardless of amount" semantics — distinct from a bounded
/// <see cref="PreventDamageEffect.Amount"/> or the all-instances
/// <see cref="PreventDamageEffect.All"/>), the damage <see cref="PreventDamageEffect.Source"/>
/// as an unfiltered <see cref="ObjectReferenceKind.Designated"/> reference (any source,
/// controller-chosen — not a target, no targeting keyword in the oracle), the
/// <see cref="PreventDamageEffect.Target"/> (recipient) as
/// <see cref="ObjectReferenceKind.You"/>, and an <c>untilTime</c>/end-of-turn
/// <see cref="MagicAST.AST.Effects.Duration"/> for "this turn".
/// </para>
///
/// <para>
/// "of your choice" is recorded as the player-designated reference itself, not its
/// resolution (ADR 0004 reference-not-resolution). This is CR-615 prevention, NOT a
/// replacement effect — no replacement ordering/layering is modelled.
/// </para>
///
/// <para>
/// ANCHORED (<c>^…prevent that damage$</c>): matches ONLY the standalone uncoloured
/// "to you" shield. It cannot fire on the coloured/typed siblings ("a red source",
/// "a black or red source"), a different recipient ("to target creature"), or the
/// activated cost-gated forms (those clauses open with "{cost}:" and are dispatched
/// through the activated-effect registry, never here). The SpellAbilityParser's
/// sentence splitter feeds each sentence separately, so the trailing "You gain life
/// equal to the damage prevented this way." sentence on Intervention Pact / Reverse
/// Damage is matched by its own rule and never reaches this pattern.
/// </para>
///
/// <para>
/// CR 615.8 (cited verbatim): "Some prevention effects generated by the resolution of a
/// spell or ability refer to the next time a specific source would deal damage. These
/// effects prevent the next instance of damage from that source, regardless of how much
/// damage that is. Once an instance of damage from that source has been prevented, any
/// subsequent instances of damage that would be dealt by that source are dealt normally."
/// CR 615.2 (cited verbatim): "Many prevention effects apply to damage from a source.
/// See rule 609.7."
/// </para>
/// </summary>
[SpellRule(Priority = 90)]
public sealed class PreventNextDamageFromChosenSourceSpellRule : ISpellRule
{
  private static readonly Regex Pattern = new(
    @"^[Tt]he\s+next\s+time\s+a\s+source\s+of\s+your\s+choice\s+would\s+deal\s+damage\s+to\s+you\s+this\s+turn,\s+prevent\s+that\s+damage$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    var trimmed = text.Trim().TrimEnd('.').Trim();
    if (!Pattern.IsMatch(trimmed))
    {
      return false;
    }

    effect = new PreventDamageEffect
    {
      NextInstance = true,
      Source = new ObjectReference { Kind = ObjectReferenceKind.Designated },
      Target = new ObjectReference { Kind = ObjectReferenceKind.You },
      Duration = UntilTimeDuration.EndOfTurn,
    };
    return true;
  }
}
