namespace MagicAST.Parsing.Parsers.Spell.Rules;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Combat;
using MagicAST.AST.Effects.Damage;
using MagicAST.AST.Effects.Keyword;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Recognises the multi-keyword UEOT grant shape with NO P/T modifier:
///   "Target creature gains &lt;keyword&gt; and &lt;keyword&gt; [and …] until end of turn."
///
/// This closes the gap between:
/// <list type="bullet">
///   <item><see cref="TargetCreatureGainsKeywordRule"/> — exactly ONE keyword,
///     e.g. "Target creature gains deathtouch until end of turn."</item>
///   <item><see cref="ModifyPTAndGainKeywordSpellRule"/> — a P/T modifier PLUS one
///     or more keywords, e.g. "Target creature gets +2/+2 and gains trample …"</item>
/// </list>
/// Neither matched the pure two-or-more-keyword grant with no buff, e.g.:
/// <list type="bullet">
///   <item>"Target creature gains deathtouch and indestructible until end of turn."
///     (Battle-Rage Blessing)</item>
/// </list>
///
/// Emits a flat list via <see cref="IMultiSpellRule.TryMatchMulti"/>: one
/// <see cref="GainAbilityEffect"/> per keyword, all sharing a single
/// until-end-of-turn duration. The FIRST grant carries the actual
/// <c>Target creature</c> object reference; subsequent grants reference the same
/// object anaphorically via <see cref="ObjectReferenceKind.It"/> (mirroring the
/// existing composite-buff rules).
///
/// Requiring at least two " and "-joined keyword segments keeps this rule strictly
/// disjoint from the single-keyword rule, so neither shadows the other.
///
/// Rule citations: 613.1c (Layer 6 — ability-adding effects), 611.2 (continuous
/// effects generated by a resolving spell, with a specified duration),
/// 702.2 (Deathtouch), 702.12 (Indestructible).
/// </summary>
[SpellRule]
public sealed class TargetCreatureGainsMultipleKeywordsSpellRule : ISpellRule, IMultiSpellRule
{
  // Anchored. "kws" captures everything between "gains" and " until end of turn";
  // the caller splits it on " and " and requires >= 2 keyword segments.
  private static readonly Regex _pattern = new(
    @"^Target\s+(?<tgt>creature|permanent)\s+gains\s+(?<kws>.+?)\s+until\s+end\s+of\s+turn$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // -------------------------------------------------------------------------
  // ISpellRule — single-effect path intentionally disabled; dispatch is via
  // TryMatchMulti so the flat GainAbilityEffect list is the only active route.
  // -------------------------------------------------------------------------
  public bool TryMatch(string text, out Effect? effect)
  {
    effect = null;
    return false;
  }

  // -------------------------------------------------------------------------
  // IMultiSpellRule — flat effect list, one GainAbilityEffect per keyword.
  // -------------------------------------------------------------------------
  public bool TryMatchMulti(string text, out IReadOnlyList<Effect>? effects)
  {
    effects = null;
    var m = _pattern.Match(text.Trim());
    if (!m.Success)
    {
      return false;
    }

    var targetNoun = m.Groups["tgt"].Value.ToLowerInvariant();
    var keywordNames = Regex.Split(m.Groups["kws"].Value.Trim(), @"\s+and\s+", RegexOptions.IgnoreCase);

    // Strictly a MULTI-keyword rule: single-keyword grants belong to
    // TargetCreatureGainsKeywordRule, so bail if there is only one segment.
    if (keywordNames.Length < 2)
    {
      return false;
    }

    var duration = UntilTimeDuration.EndOfTurn;
    var target = new ObjectReference
    {
      Kind = ObjectReferenceKind.Target,
      Filter = new ObjectFilter { CardTypes = [targetNoun] },
    };
    var it = new ObjectReference { Kind = ObjectReferenceKind.It };

    var list = new List<Effect>(keywordNames.Length);
    for (var i = 0; i < keywordNames.Length; i++)
    {
      var ability = BuildKeywordAbility(keywordNames[i].Trim());
      if (ability is null)
      {
        // Unrecognised keyword — bail so the fallback parser handles the card.
        effects = null;
        return false;
      }
      list.Add(new GainAbilityEffect
      {
        Target = i == 0 ? target : it,
        GainedAbility = ability,
        Duration = duration,
      });
    }

    effects = list;
    return true;
  }

  // -------------------------------------------------------------------------
  // Keyword → StaticAbility factory. Self-contained, mirroring the mappings in
  // TargetCreatureGainsKeywordRule / ModifyPTAndGainKeywordSpellRule so this rule
  // can evolve independently without editing shared helpers.
  // -------------------------------------------------------------------------
  private static StaticAbility? BuildKeywordAbility(string keyword) =>
    keyword.ToLowerInvariant() switch
    {
      "deathtouch" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Deathtouch,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Deathtouch }],
      },
      "indestructible" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Indestructible,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Indestructible }],
      },
      "trample" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Trample,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Trample }],
      },
      "vigilance" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Vigilance,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Vigilance }],
      },
      "haste" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Haste,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Haste }],
      },
      "hexproof" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Hexproof,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Hexproof }],
      },
      "shroud" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Shroud,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Shroud }],
      },
      "reach" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Reach,
        Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Reach }],
      },
      "lifelink" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Lifelink,
        Effects = [new LifelinkEffect()],
      },
      "first strike" => new StaticAbility
      {
        KeywordSource = KeywordAbility.FirstStrike,
        Effects = [new CombatDamageTimingEffect { Timing = CombatDamageTiming.First }],
      },
      "double strike" => new StaticAbility
      {
        KeywordSource = KeywordAbility.DoubleStrike,
        Effects = [new CombatDamageTimingEffect { Timing = CombatDamageTiming.Both }],
      },
      "flying" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Flying,
        Effects =
        [
          new EvasionEffect
          {
            CanBeBlockedBy = new ObjectFilter
            {
              CardTypes = ["creature"],
              Characteristics = [Characteristic.HasKeyword(KeywordAbility.Flying), Characteristic.HasKeyword(KeywordAbility.Reach)],
            },
          },
        ],
      },
      "menace" => new StaticAbility
      {
        KeywordSource = KeywordAbility.Menace,
        Effects =
        [
          new EvasionEffect
          {
            CanBeBlockedBy = new ObjectFilter { CardTypes = ["creature"] },
            MinimumBlockers = 2,
          },
        ],
      },
      _ => null,
    };
}
