namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Recognises the Incarnation cycle's graveyard-functional conditional keyword grant:
/// "As long as this card is in your graveyard and you control a &lt;basic land
/// subtype&gt;, &lt;card type&gt;s you control have &lt;keyword&gt;." — Brawn's third
/// line: "As long as this card is in your graveyard and you control a Forest,
/// creatures you control have trample."
///
/// <para>
/// CR 112.6a: an ability can function from a graveyard (or another zone) if it's
/// written to do so or if the ability is characteristic-defining; MAST does not model
/// zone-functioning machinery itself (ADR 0003/0004 describe-not-execute) — it simply
/// records that the condition's first conjunct is a state check on the source card's
/// OWN current zone (<c>ObjectFilter.IsSelf</c> + <c>Zone.Graveyard</c>), composed with
/// the ordinary "you control a [land]" board-state conjunct via <see cref="AllCondition"/>
/// (ADR 0007, composing primitives over new leaves — mirrors <c>ImpendingStaticRule</c>'s
/// manually-built compound gate). CR 702.19a: "Trample is a static ability." — the
/// granted keyword is generalised through <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/>
/// rather than hard-coded to Trample, so any bare keyword in this template resolves.
/// </para>
///
/// <para>
/// The "as long as" gate is a continuous <see cref="Duration"/> on the
/// <see cref="GainAbilityEffect"/> (CR 611.2 — a continuous effect generated by a
/// static ability lasts as long as the source remains in the zone it functions from
/// and the condition holds), not an ability-scope <see cref="StaticAbility.Condition"/>:
/// the latter is reserved for "if …" resolution-time gates (e.g. Deepwood Legate's
/// <c>AllCondition</c>-gated <c>castWithoutPaying</c>), whereas "as long as" is a
/// duration on the grant itself, matching <c>AsLongAsControlledObjectsHaveAbilityRule</c>
/// and <c>TheWorldTree</c>'s "As long as you control six or more lands, lands you
/// control have […]" sibling shape.
/// </para>
///
/// <para>
/// Priority 970 — above the generic <see cref="AsLongAsStaticGrantRule"/> (968) and
/// <see cref="AsLongAsControlledObjectsHaveAbilityRule"/> (969, which requires a QUOTED
/// activated-ability body and would not match this bare-keyword shape anyway). The
/// pattern is anchored (^…$) and requires the literal "this card is in your graveyard
/// and you control a" prefix, so it cannot steal a shorter/longer sibling clause.
/// </para>
/// </summary>
[StaticRule(Priority = 970)]
public sealed class AsLongAsInGraveyardKeywordGrantRule : IStaticRule
{
  // Matches: "As long as this card is in your graveyard and you control a <land>,
  // <type>s you control have <keyword>." <land> is the basic land subtype noun
  // (e.g. "Forest", "Mountain"); <type> is the (potentially plural) card-type noun
  // before " you control have"; <kw> is the bare (unquoted) keyword name.
  private static readonly Regex _pattern = new(
    @"^\s*As\s+long\s+as\s+this\s+card\s+is\s+in\s+your\s+graveyard\s+and\s+you\s+control\s+a\s+"
    + @"(?<land>[A-Za-z]+),\s*(?<type>[A-Za-z]+s?)\s+you\s+control\s+have\s+"
    + @"(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Known card-type plural-to-singular mapping (oracle uses plural in this shape).
  private static readonly Dictionary<string, string> _pluralToSingular = new(
    StringComparer.OrdinalIgnoreCase)
  {
    ["creatures"] = "creature",
    ["artifacts"] = "artifact",
    ["enchantments"] = "enchantment",
    ["lands"] = "land",
    ["planeswalkers"] = "planeswalker",
    ["permanents"] = "permanent",
    ["creature"] = "creature",
    ["artifact"] = "artifact",
    ["enchantment"] = "enchantment",
    ["land"] = "land",
    ["planeswalker"] = "planeswalker",
    ["permanent"] = "permanent",
  };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var m = _pattern.Match(clause.RawText);
    if (!m.Success)
    {
      return null;
    }

    var landSubtype = m.Groups["land"].Value.Trim();
    var typeText = m.Groups["type"].Value.Trim();
    var kw = m.Groups["kw"].Value.Trim().ToLowerInvariant();

    if (!_pluralToSingular.TryGetValue(typeText, out var singularType))
    {
      // Unknown card type — decline and let the fallback handle it.
      return null;
    }

    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(kw);
    if (grantedAbility is null)
    {
      return null;
    }

    // Conjunct 1: "this card is in your graveyard" — the graveyard-functional zone
    // check (CR 112.6a) on the source card itself.
    var inGraveyard = new CountCondition
    {
      Filter = new ObjectFilter
      {
        CardTypes = ["card"],
        IsSelf = true,
        Zone = Zone.Graveyard,
      },
      Count = new Comparison { Operator = ComparisonOperator.GreaterThanOrEqual, Value = 1 },
    };

    // Conjunct 2: "you control a <land>".
    var controlsLand = new CountCondition
    {
      Filter = new ObjectFilter
      {
        Subtypes = [landSubtype],
        Controller = ControllerFilter.You,
      },
      Count = new Comparison { Operator = ComparisonOperator.GreaterThanOrEqual, Value = 1 },
    };

    var duration = new AsLongAsDuration
    {
      Condition = new AllCondition { Conditions = [inGraveyard, controlsLand] },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new GainAbilityEffect
          {
            Target = new ObjectReference
            {
              Kind = ObjectReferenceKind.Each,
              Filter = new ObjectFilter
              {
                CardTypes = [singularType],
                Controller = ControllerFilter.You,
              },
            },
            GainedAbility = grantedAbility,
            Duration = duration,
          },
        ],
      },
    ];
  }
}
