namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached-P/T anthem + card-type grant:
/// "[Enchanted|Equipped] creature gets +N/+M and is a[n] &lt;card type&gt; in addition to
/// its other types."
/// e.g. Silverskin Armor — "Equipped creature gets +1/+1 and is an artifact in addition to
/// its other types."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the MAST
/// multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+M, CR 613.4c — a
/// layer-7c power/toughness-modifying continuous effect) and an <see cref="AddTypeEffect"/>
/// additively granting the card type (CR 613.1d — layer 4, type-changing effects; CR
/// 205.1b — "in addition to its other types" retains all prior card types, supertypes, and
/// subtypes), BOTH targeting the same attached subject "Enchanted/Equipped creature". One
/// oracle clause generates one continuous effect from one static ability, so the two
/// effects share a single ability rather than being split into two abilities (CR 611.3 —
/// "A continuous effect may be generated by the static ability of an object.").
/// </para>
///
/// <para>
/// Direct sibling of <see cref="AttachedModifyPTAndEveryCreatureTypeRule"/> (Runed
/// Stalactite: "...and is every creature type.", modeled via a Changeling
/// <see cref="GainAbilityEffect"/> grant instead of an <see cref="AddTypeEffect"/>) — both
/// share the same "attached P/T anthem + type rider" shape, differing only in how the type
/// grant is expressed. Also related to <see cref="EquippedPTKeywordAddTypeRule"/> (Raven
/// Wings: "...has flying, and is a Bird in addition to its other types."), which adds a
/// creature SUBTYPE via a three-part clause including a keyword grant; here the grant is a
/// CARD TYPE (not a subtype) and there is no keyword rider, so the clause is only two parts.
/// </para>
///
/// <para>
/// CR 205.1b (verbatim): "Some effects change an object's card type, supertype, or subtype
/// but specify that the object retains a prior card type, supertype, or subtype. In such
/// cases, all the object's prior card types, supertypes, and subtypes are retained. This
/// rule applies to effects that use phrases such as 'in addition to its other types' or
/// that state that something is 'still a [type, supertype, or subtype].'"
/// </para>
/// <para>
/// CR 613.1d (verbatim): "Layer 4: Type-changing effects are applied. These include effects
/// that change an object's card type, subtype, and/or supertype."
/// </para>
/// <para>
/// CR 613.4c (verbatim): "Layer 7c: Effects and counters that modify power and/or toughness
/// (but don't set power and/or toughness to a specific number or value) are applied."
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class AttachedModifyPTAndCardTypeRule : IStaticRule
{
  // "[Enchanted|Equipped] creature gets +N/+M and is a[n] <card type> in addition to its
  // other types."
  // Both P/T sides require an explicit sign (anthems use signed notation).
  private static readonly Regex _attachedPTAndCardTypePattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+is\s+an?\s+(?<type>[A-Za-z]+)\s+in\s+addition\s+to\s+its\s+other\s+types\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Known card types (CR 205.2a) — the "a[n] <type>" rider must name one of these,
  // otherwise the captured word is a creature subtype (handled by a sibling rule) rather
  // than a card type.
  private static readonly HashSet<string> _cardTypes = new(StringComparer.OrdinalIgnoreCase)
  {
    "Artifact", "Battle", "Conspiracy", "Creature", "Enchantment", "Instant",
    "Land", "Phenomenon", "Plane", "Planeswalker", "Scheme", "Sorcery",
    "Tribal", "Vanguard",
  };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attachedPTAndCardTypePattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var cardType = match.Groups["type"].Value;
    if (!_cardTypes.Contains(cardType))
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new AddTypeEffect
          {
            Target = Subject(),
            AddedCardTypes = [cardType.ToLowerInvariant()],
          },
        ],
      },
    ];
  }
}
