namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Combat;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached-P/T anthem + goaded designation:
/// "[Enchanted|Equipped] creature gets +N/+M and is goaded."
/// e.g. Bloodthirsty Blade — "Equipped creature gets +2/+0 and is goaded."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/>
/// (+N/+M) and a <see cref="GoadedEffect"/> (CR 701.15b — the goaded
/// designation), BOTH targeting the same attached subject "Enchanted/Equipped
/// creature". One oracle clause generates one continuous effect from one
/// static ability, so the two effects share a single ability rather than
/// being split into two abilities (CR 611.3 — "A continuous effect may be
/// generated by the static ability of an object.").
/// </para>
///
/// <para>
/// Distinct from <see cref="AnthemModifyPTRule"/> (the bare "Enchanted/
/// Equipped creature gets +N/+M." shape, no goaded rider). Mirrors the
/// compound shape used by <see cref="SupertypeAnthemAndKeywordGrantRule"/>
/// for the analogous "and have [keyword]" conjunction, but the rider here is
/// a designation (CR 701.15b — "Goaded is a designation a permanent can
/// have."), not a keyword ability, so it is recorded via
/// <see cref="GoadedEffect"/> rather than <see cref="GainAbilityEffect"/>.
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class AttachedModifyPTAndGoadedRule : IStaticRule
{
  // "[Enchanted|Equipped] creature gets +N/+M and is goaded." Both P/T sides
  // require an explicit sign (anthems use signed notation). Optional trailing
  // reminder text (e.g. the goaded reminder) is captured separately.
  private static readonly Regex _attachedPTAndGoadedPattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+is\s+goaded\.?\s*(?<reminder>\(.*\))?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attachedPTAndGoadedPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);

    Parenthetical? reminder = null;
    var reminderGroup = match.Groups["reminder"];
    if (reminderGroup.Success && reminderGroup.Value.Length > 0)
    {
      reminder = new Parenthetical { Text = reminderGroup.Value };
    }

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Reminder = reminder,
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GoadedEffect { Target = Subject() },
        ],
      },
    ];
  }
}
