namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined ATTACKING-scoped subtype anthem + keyword grant, with the "creatures"
/// noun OMITTED because the bare plural subtype noun itself stands in for it:
/// "Attacking [Subtype-plural] you control get +N/+N and have [keyword]."
/// e.g. Blight Mound — "Attacking Pests you control get +1/+0 and have menace."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+N)
/// and a <see cref="GainAbilityEffect"/> (the keyword), BOTH targeting the same
/// subtype-and-combat-state-filtered subject "[Subtype] you control [that are]
/// attacking". One oracle clause generates one continuous effect from one static
/// ability, so the two effects share a single ability rather than being split into
/// two abilities (CR 611.3 — "A continuous effect may be generated by the static
/// ability of an object. Example: A permanent with the static ability 'All white
/// creatures get +1/+1' generates an effect that continuously gives +1/+1 to each
/// white creature on the battlefield.").
/// </para>
///
/// <para>
/// The leading "Attacking" qualifier (CR 508 — a creature that's attacking) is
/// recorded on <see cref="ObjectFilter.Characteristics"/> as a
/// <see cref="CombatStateCharacteristic"/> with <see cref="CombatState.Attacking"/>,
/// mirroring the same combat-state axis <see cref="Characteristic.FromLabel"/>
/// produces for "attacking creature" filters elsewhere (e.g. Goblin Wardriver's
/// Battle cry). The matched noun ALWAYS routes to <see cref="ObjectFilter.Subtypes"/>
/// (a creature subtype, e.g. "Pests"), matching the sibling
/// <see cref="TribalAnthemAndKeywordGrantRule"/>'s no-"creatures" subject shape.
/// "You control" resolves to the source's controller (CR 109.5).
/// </para>
///
/// <para>
/// The granted keyword is itself a static ability, modelled as a recursive
/// <see cref="GainAbilityEffect.GainedAbility"/> via the shared
/// <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping. No duration is
/// carried — a static ability's continuous effect lasts for as long as the source
/// remains on the battlefield, not until a stated time.
/// </para>
///
/// <para>
/// Distinct from <see cref="TribalAnthemAndKeywordGrantRule"/> (the plain
/// "Other [Subtype] you control get +N/+N and have [keyword]" shape, no combat-state
/// qualifier) and <see cref="SupertypeAnthemAndKeywordGrantRule"/> (requires the
/// "creatures" word). The mandatory "Attacking" prefix here means this pattern never
/// starts with an optional "Other " group, so the two never collide on the same
/// clause.
/// </para>
/// </summary>
[StaticRule(Priority = 971)]
public sealed class AttackingSubtypeAnthemAndKeywordGrantRule : IStaticRule
{
  // "Attacking <Subtype-plural> you control get +N/+N and have <keyword>." — no
  // "creatures" word between the subtype noun and the controller clause: the bare
  // plural subtype noun itself stands in for "[Subtype] creatures" (Blight Mound's
  // "Attacking Pests", not "Attacking Pest creatures"). Both P/T sides require an
  // explicit '+' sign (anthems use signed notation). The keyword runs to
  // end-of-clause (letters and spaces only).
  private static readonly Regex _attackingSubtypeAnthemKeywordPattern = new(
    @"^\s*Attacking\s+(?<sub>[A-Z][a-z]+)\s+(?<ctrl>you\s+control|your\s+opponents\s+control)\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\s+and\s+have\s+(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attackingSubtypeAnthemKeywordPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    // The captured noun is grammatically plural (unlike the sibling
    // TribalAnthemAndKeywordGrantRule's plural-invariant subtypes, e.g. Merfolk);
    // singularize it to the printed card subtype (Pests -> Pest). Conservative
    // trailing-"s" strip, matching the established StaticRuleHelpers.Singularize
    // convention used elsewhere for board-count filters.
    var subtype = Singularize(match.Groups["sub"].Value);

    var keyword = match.Groups["kw"].Value.Trim();
    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(keyword);
    if (grantedAbility is null)
    {
      // Recognised the compound shape but the keyword is not yet supported; decline so
      // the clause falls through to an honest fallback rather than emitting a partial buff.
      return null;
    }

    var ctrl = match.Groups["ctrl"].Value.ToLowerInvariant();
    var controller = ctrl.StartsWith("you")
      ? ControllerFilter.You
      : ControllerFilter.Opponent;
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    // Both effects share the same filtered subject. A fresh ObjectReference is built per effect
    // (records are immutable; the two filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Subtypes = [subtype],
        Controller = controller,
        Characteristics = [Characteristic.InCombat(CombatState.Attacking)],
      },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = grantedAbility,
          },
        ],
      },
    ];
  }

  // Strips a trailing plural "s" so the captured noun matches the printed card
  // subtype ("Pests" -> "Pest"). Conservative: only a simple trailing "s", local
  // to this rule so it does not depend on the shared StaticRuleHelpers internals.
  private static string Singularize(string noun) =>
    noun.Length > 1 && noun.EndsWith('s') ? noun[..^1] : noun;
}
