namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Control;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached-P/T anthem + doesn't-untap rider:
/// "[Enchanted|Equipped] creature gets +N/+M and doesn't untap during its
/// controller's untap step." e.g. T-45 Power Armor — "Equipped creature gets
/// +3/+3 and doesn't untap during its controller's untap step."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/>
/// (+N/+M) and a <see cref="DoesntUntapEffect"/> (CR 502.3 — a continuous
/// effect can keep a permanent from untapping during the untap step), BOTH
/// targeting the same attached subject "Enchanted/Equipped creature". One
/// oracle clause generates one continuous effect from one static ability, so
/// the two effects share a single ability rather than being split into two
/// abilities (CR 611.3 — "A continuous effect may be generated by the static
/// ability of an object.").
/// </para>
///
/// <para>
/// Sibling of <see cref="AttachedModifyPTAndGoadedRule"/> (the analogous
/// "gets +N/+M and is goaded" compound) — same shape, different rider effect.
/// Distinct from <see cref="AnthemModifyPTRule"/> (the bare "Enchanted/
/// Equipped creature gets +N/+M." shape, no rider) and from
/// <see cref="DoesntUntapRule"/>'s bare enchanted/equipped "doesn't untap"
/// shape (no P/T grant).
/// </para>
///
/// <para>
/// CR 702.6 (Equip); CR 502.3 (verbatim): "Third, the active player determines
/// which permanents they control will untap. Then they untap them all
/// simultaneously. This turn-based action doesn't use the stack. Normally, all
/// of a player's permanents untap, but effects can keep one or more of a
/// player's permanents from untapping."
/// </para>
///
/// <para>
/// ANCHORED (^…$): the full oracle sentence is matched exactly so this rule
/// cannot fire on a substring of a more specific sibling clause. The
/// apostrophe class tolerates both the straight (U+0027) and curly (U+2019)
/// forms used across printings (matching the convention in
/// <see cref="SubjectDoesntUntapDuringControllersUntapStepsRule"/>).
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class AttachedModifyPTAndDoesntUntapRule : IStaticRule
{
  // "[Enchanted|Equipped] creature gets +N/+M and doesn't untap during its
  // controller's untap step." Both P/T sides require an explicit sign (anthems
  // use signed notation).
  private static readonly Regex _attachedPTAndDoesntUntapPattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+doesn[’']?t\s+untap\s+during\s+its\s+controller[’']?s\s+untap\s+step\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attachedPTAndDoesntUntapPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new DoesntUntapEffect
          {
            Target = Subject(),
            WhoseUntapStep = "its controller's",
          },
        ],
      },
    ];
  }
}
