namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached-P/T anthem + keyword-removal rider:
/// "[Enchanted|Equipped] creature gets +N/+M and loses [keyword]." e.g.
/// Magebane Armor — "Equipped creature gets +2/+4 and loses flying."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/>
/// (+N/+M) and a <see cref="LoseAbilityEffect"/> (the removed keyword), BOTH
/// targeting the same attached subject "Enchanted/Equipped creature". One
/// oracle clause generates one continuous effect from one static ability, so
/// the two effects share a single ability rather than being split into two
/// abilities (CR 611.3 — "A continuous effect may be generated by the static
/// ability of an object.").
/// </para>
///
/// <para>
/// CR 702.6 (Equip); CR 611.2 — a continuous effect generated by a static
/// ability can, among other things, remove an ability from an object; the
/// removed keyword is recorded on <see cref="LoseAbilityEffect.AbilityText"/>
/// (a designed free-text field, mirroring the "all other abilities" and
/// "enchant creature card in a graveyard" usages elsewhere) rather than a
/// structured keyword node, since the lost side carries no recursive ability
/// definition to model (unlike a grant, which must recreate the full ability).
/// </para>
///
/// <para>
/// Sibling of <see cref="AttachedModifyPTAndDoesntUntapRule"/> and
/// <see cref="AttachedModifyPTAndGoadedRule"/> (same compound shape, different
/// rider effect). Distinct from <see cref="AnthemModifyPTRule"/> (the bare
/// "Enchanted/Equipped creature gets +N/+M." shape, no rider).
/// </para>
///
/// <para>
/// ANCHORED (^…$): the full oracle sentence is matched exactly so this rule
/// cannot fire on a substring of a more specific sibling clause. The keyword
/// is generalized (captured as free text, not hardcoded to "flying") so any
/// "loses [keyword]" rider is covered by this one rule.
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class AttachedModifyPTAndLosesKeywordRule : IStaticRule
{
  // "[Enchanted|Equipped] creature gets +N/+M and loses <keyword>." Both P/T
  // sides require an explicit sign (anthems use signed notation). The keyword
  // runs to end-of-clause (letters and spaces only), generalized rather than
  // hardcoded to a single named keyword.
  private static readonly Regex _attachedPTAndLosesKeywordPattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+loses\s+(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attachedPTAndLosesKeywordPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);
    var keyword = match.Groups["kw"].Value.Trim();

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          BuildLoseKeyword(Subject(), keyword),
        ],
      },
    ];
  }

  // "loses [keyword]" — when the removed ability is a single named keyword expressible
  // by the KeywordAbility enum, record the STRUCTURED value (LoseAbilityEffect.Keyword)
  // rather than the free-text AbilityText escape hatch. AbilityText remains for genuine
  // ability SCOPES ("all abilities") the enum can't capture. (De-string initiative PB-9.)
  private static LoseAbilityEffect BuildLoseKeyword(ObjectReference target, string keyword)
  {
    if (System.Enum.TryParse<KeywordAbility>(keyword.Replace(" ", string.Empty), ignoreCase: true, out var kw))
    {
      return new LoseAbilityEffect { Target = target, Keyword = kw };
    }
    return new LoseAbilityEffect { Target = target, AbilityText = keyword };
  }
}
