namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Keyword;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached-P/T anthem + Changeling grant:
/// "[Enchanted|Equipped] creature gets +N/+M and is every creature type."
/// e.g. Runed Stalactite — "Equipped creature gets +1/+1 and is every creature type."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/>
/// (+N/+M, CR 613.4c — a layer-7c power/toughness-modifying continuous effect)
/// and a <see cref="GainAbilityEffect"/> granting the Changeling
/// characteristic-defining ability (CR 205.3m — creature types are a subset of
/// subtypes; CR 702.73a — Changeling as an ability grant), BOTH targeting the
/// same attached subject "Enchanted/Equipped creature". One oracle clause
/// generates one continuous effect from one static ability, so the two
/// effects share a single ability rather than being split into two abilities
/// (CR 611.3 — "A continuous effect may be generated by the static ability of
/// an object.").
/// </para>
///
/// <para>
/// Mirrors the sibling compound-rider shapes <see cref="AttachedModifyPTAndGoadedRule"/>
/// (is goaded), <see cref="AttachedModifyPTAndDoesntUntapRule"/> (doesn't
/// untap), and <see cref="AttachedModifyPTAndLosesKeywordRule"/> (loses
/// [keyword]) — all target the same "Enchanted/Equipped creature" subject
/// with a P/T anthem plus one rider clause. Here the rider is a
/// characteristic-defining-ability grant, so it is recorded via
/// <see cref="GainAbilityEffect"/> wrapping a Changeling <see cref="StaticAbility"/>
/// (KeywordSource = Changeling), exactly the shape <c>CreaturesAreEveryCreatureTypeRule</c>
/// (Maskwood Nexus) uses per-scope, but here scoped directly to the single
/// attached subject rather than a filtered "each creature" collection.
/// </para>
///
/// <para>
/// CR 702.73a (verbatim): "Changeling is a characteristic-defining ability.
/// 'Changeling' means 'This object is every creature type.' This ability
/// works everywhere, even outside the game. See rule 604.3."
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class AttachedModifyPTAndEveryCreatureTypeRule : IStaticRule
{
  // "[Enchanted|Equipped] creature gets +N/+M and is every creature type."
  // Both P/T sides require an explicit sign (anthems use signed notation).
  private static readonly Regex _attachedPTAndEveryCreatureTypePattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+is\s+every\s+creature\s+type\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  /// <summary>
  /// The Changeling keyword static ability — granted to the attached subject.
  /// CR 702.73a: "Changeling" means "This object is every creature type."
  /// </summary>
  private static readonly StaticAbility _changelingAbility = new()
  {
    KeywordSource = KeywordAbility.Changeling,
    Effects = [new KeywordAbilityEffect { Keyword = KeywordAbility.Changeling }],
  };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _attachedPTAndEveryCreatureTypePattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = _changelingAbility,
          },
        ],
      },
    ];
  }
}
