namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Recognises the static keyword-pair grant on an attached permanent:
/// "(Enchanted|Equipped) creature has [kw1] and [kw2]."
///
/// <para>
/// This is a <b>static</b> continuous effect (CR 611.1: "A continuous effect modifies
/// characteristics of objects … for a fixed or indefinite period."; CR 611.3: "A
/// continuous effect may be generated by the static ability of an object."). The grant
/// persists for as long as the Aura or Equipment remains attached — there is no
/// Duration node (distinct from the activated "gains [kw] until end of turn" shape).
/// </para>
///
/// <para>
/// CR 702.5a: "Enchant is a static ability … The enchant ability restricts what an
/// Aura spell can target and what an Aura can enchant." The enchanted/equipped subject
/// maps to <see cref="ObjectReferenceKind.EnchantedOrEquipped"/>.
/// </para>
///
/// <para>
/// Per the MAST multi-effect-per-clause doctrine, "has [kw1] and [kw2]" on one oracle
/// line is bundled into a single <see cref="StaticAbility"/> whose
/// <see cref="Ability.Effects"/> list carries two independent
/// <see cref="GainAbilityEffect"/> nodes — one per keyword. No
/// <c>CompositeEffect</c> wrapper is used: the flat Effects list is the idiomatic
/// multi-effect encoding for a static ability.
/// </para>
/// </summary>
[StaticRule(Priority = 968)]
public sealed class BareKeywordPairGrantRule : IStaticRule
{
  // "(Enchanted|Equipped) creature has <kw1> and <kw2>."
  // kw1 is a non-greedy word (or two-word keyword like "first strike") that stops
  // at the first " and " token; kw2 is captured to the end-anchor.
  // The patterns are case-insensitive so "enchanted" / "Enchanted" both match.
  private static readonly Regex _enchantedDualKeywordPattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+has\s+(?<kw1>[a-z][a-z]*(?:\s+[a-z]+)*?)\s+and\s+(?<kw2>[a-z][a-z ]+?)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    // Strip trailing parenthetical reminder text (Rule 207.2 — reminder text is
    // not rules text) so lines like "Enchanted creature has trample and haste.
    // (It can deal excess…)" still match the end-anchored pattern.
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);

    var match = _enchantedDualKeywordPattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var kw1 = match.Groups["kw1"].Value.Trim().ToLowerInvariant();
    var kw2 = match.Groups["kw2"].Value.Trim().ToLowerInvariant();

    var grantedAbility1 = StaticRuleHelpers.MapKeywordToStaticAbility(kw1);
    var grantedAbility2 = StaticRuleHelpers.MapKeywordToStaticAbility(kw2);

    if (grantedAbility1 is null || grantedAbility2 is null)
    {
      // One or both keywords unrecognised — fall through so the fallback surfaces the gap.
      return null;
    }

    var target = new ObjectReference { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    // Two GainAbilityEffect nodes in a flat Effects list on one StaticAbility —
    // the multi-effect-per-clause encoding (MAST doctrine). No Duration: this is
    // a persistent static grant, not a temporary "until end of turn" grant.
    return
    [
      new StaticAbility
      {
        Effects =
        [
          new GainAbilityEffect
          {
            Target = target,
            GainedAbility = grantedAbility1,
          },
          new GainAbilityEffect
          {
            Target = target,
            GainedAbility = grantedAbility2,
          },
        ],
      },
    ];
  }
}
