namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Recognises the static three-keyword Oxford-comma grant on an attached permanent:
/// "(Enchanted|Equipped) creature has [kw1], [kw2], and [kw3]."
///
/// <para>
/// This is a <b>static</b> continuous effect (CR 611.1: "A continuous effect modifies
/// characteristics of objects … for a fixed or indefinite period."; CR 611.3: "A
/// continuous effect may be generated by the static ability of an object."). The grant
/// persists for as long as the Aura or Equipment remains attached — there is no
/// Duration node (distinct from the activated "gains [kw] until end of turn" shape).
/// </para>
///
/// <para>
/// CR 301.5d: an Equipment's ability "may be an ability that's expressed as
/// 'Equipped creature gains [ability]' or 'Equipped creature has [ability]'." The
/// enchanted/equipped subject maps to <see cref="ObjectReferenceKind.EnchantedOrEquipped"/>.
/// </para>
///
/// <para>
/// Per the MAST multi-effect-per-clause doctrine, "has [kw1], [kw2], and [kw3]" on one
/// oracle line is bundled into a single <see cref="StaticAbility"/> whose
/// <see cref="Ability.Effects"/> list carries three independent
/// <see cref="GainAbilityEffect"/> nodes — one per keyword. No
/// <c>CompositeEffect</c> wrapper is used: the flat Effects list is the idiomatic
/// multi-effect encoding for a static ability.
/// </para>
/// </summary>
[StaticRule(Priority = 969)]
public sealed class BareKeywordListGrantRule : IStaticRule
{
  // "(Enchanted|Equipped) creature has <kw1>, <kw2>, and <kw3>."
  // kw1/kw2 are non-greedy words (or multi-word keywords like "first strike") that
  // stop at the following comma; kw3 is captured up to the end-anchor.
  // The pattern is case-insensitive so "enchanted" / "Enchanted" both match.
  private static readonly Regex _enchantedTripleKeywordPattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+has\s+(?<kw1>[a-z][a-z ]+?),\s+(?<kw2>[a-z][a-z ]+?),\s+and\s+(?<kw3>[a-z][a-z ]+?)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    // Strip trailing parenthetical reminder text (Rule 207.2 — reminder text is
    // not rules text) so lines like "Equipped creature has vigilance, trample,
    // and haste. (Reminder text…)" still match the end-anchored pattern.
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);

    var match = _enchantedTripleKeywordPattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var kw1 = match.Groups["kw1"].Value.Trim().ToLowerInvariant();
    var kw2 = match.Groups["kw2"].Value.Trim().ToLowerInvariant();
    var kw3 = match.Groups["kw3"].Value.Trim().ToLowerInvariant();

    var grantedAbility1 = StaticRuleHelpers.MapKeywordToStaticAbility(kw1);
    var grantedAbility2 = StaticRuleHelpers.MapKeywordToStaticAbility(kw2);
    var grantedAbility3 = StaticRuleHelpers.MapKeywordToStaticAbility(kw3);

    if (grantedAbility1 is null || grantedAbility2 is null || grantedAbility3 is null)
    {
      // One or more keywords unrecognised — fall through so the fallback surfaces the gap.
      return null;
    }

    var target = new ObjectReference { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    // Three GainAbilityEffect nodes in a flat Effects list on one StaticAbility —
    // the multi-effect-per-clause encoding (MAST doctrine). No Duration: this is
    // a persistent static grant, not a temporary "until end of turn" grant.
    return
    [
      new StaticAbility
      {
        Effects =
        [
          new GainAbilityEffect
          {
            Target = target,
            GainedAbility = grantedAbility1,
          },
          new GainAbilityEffect
          {
            Target = target,
            GainedAbility = grantedAbility2,
          },
          new GainAbilityEffect
          {
            Target = target,
            GainedAbility = grantedAbility3,
          },
        ],
      },
    ];
  }
}
