namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// "Creatures you control of the chosen color get +X/+Y." (Heraldic Banner) — a
/// continuous P/T anthem (CR 611.3: "Some continuous effects are generated by
/// spells or abilities that give another object an ability that generates a
/// continuous effect. ... in this case the source of the effect is the object
/// that has the ability") whose affected set is filtered by the color chosen as
/// this permanent entered.
///
/// <para>The "of the chosen color" clause is the structured consumer half of a CR
/// 607 linked ability — the producer is the "As this [permanent] enters, choose a
/// color" effect under <c>StaticAbility.When = AsThisEnters</c>
/// (<see cref="MagicAST.AST.Effects.Keyword.ChooseColorEffect"/>). It is encoded
/// with the structured <see cref="ObjectFilter.ChosenCharacteristic"/> =
/// <see cref="ChosenCharacteristicKind.Color"/> reference, never free-text.</para>
///
/// <para>Sibling of <see cref="ChosenTypeAnthemModifyPTRule"/> (the analogous
/// "of the chosen type" shape): the surface noun chosen ("a color" vs. "a creature
/// type") differs, and downstream references to "the chosen color" name a distinct
/// axis than "the chosen type" (<see cref="ChosenCharacteristicKind"/> is
/// kind-based), so this is a separate rule rather than a shared regex.</para>
/// </summary>
[StaticRule(Priority = 971)]
public sealed class ChosenColorAnthemModifyPTRule : IStaticRule
{
  private static readonly Regex _chosenColorAnthemModifyPTPattern = new(
    @"^\s*Creatures\s+you\s+control\s+of\s+the\s+chosen\s+color\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _chosenColorAnthemModifyPTPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    return
    [
      new StaticAbility
      {
        Effects = [new ModifyPTEffect
        {
          Target = new ObjectReference
          {
            Kind = ObjectReferenceKind.Each,
            Filter = new ObjectFilter
            {
              CardTypes = ["creature"],
              Controller = ControllerFilter.You,
              ChosenCharacteristic = ChosenCharacteristicKind.Color,
            },
          },
          PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
          ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
        }],
      },
    ];
  }
}
