namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// Color-source damage-prevention static ability (the "Sphere of X" family):
/// "If a red source would deal damage to you, prevent 2 of that damage."
///
/// CR 615.10 (cited verbatim — its example is this exact template with N=1):
/// "Some prevention effects generated by static abilities refer to a specific
/// amount of damage — for example, \"If a source would deal damage to you, prevent
/// 1 of that damage.\" Such an effect prevents only the indicated amount of damage
/// in any applicable damage event at any given time. It will apply separately to
/// damage from other applicable events that would happen at the same time, or at a
/// different time."
///
/// CR 615.1: "Some continuous effects are prevention effects. Like replacement
/// effects (see rule 614), prevention effects apply continuously as events happen …
/// Such effects watch for a damage event that would happen and completely or
/// partially prevent the damage that would be dealt."
/// CR 615.1a: "Effects that use the word \"prevent\" are prevention effects."
/// CR 615.2: "Many prevention effects apply to damage from a source."
///
/// Structure: a <c>StaticAbility</c> with a <c>ReplacementEffect</c> that:
/// <list type="bullet">
///   <item>Watches for a <c>DamageEvent</c> whose <c>Source</c> has the named color
///   (<c>Source.Colors = [color]</c>) and whose recipient is you
///   (<c>AffectedObjects.Controller = You</c>).</item>
///   <item>Replaces the damage with a <c>PreventDamageEffect</c> that prevents a
///   fixed <c>Amount</c> of it (<c>LiteralQuantity.Of(N)</c>) from the affected
///   player (<c>Target = You</c>). Only <c>Amount</c> is prevented — the color
///   filter lives on the watched event's source, not on the prevention action.</item>
/// </list>
///
/// ANCHORED (^...$): the full-line template "If a [color] source would deal damage
/// to you, prevent [N] of that damage." is matched in its entirety, so it cannot
/// fire as a substring of a broader clause. It is distinct from the Circle/Rune of
/// Protection activated shape ("The next time a red source of your choice would deal
/// damage to you this turn, prevent that damage."), which has no leading "If", no
/// numeric amount, and is an activated ability.
/// </summary>
[StaticRule(Priority = 966)]
public sealed class ColorSourceDamagePreventionStaticRule : IStaticRule
{
  // "If a [color] source would deal damage to you, prevent [N] of that damage."
  // ANCHORED (^...$) to prevent substring matching inside broader clauses.
  private static readonly Regex _pattern = new(
    @"^\s*If\s+a\s+(?<color>white|blue|black|red|green)\s+source\s+would\s+deal\s+damage\s+to\s+you,\s*prevent\s+(?<amount>\d+)\s+of\s+that\s+damage\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  private static readonly IReadOnlyDictionary<string, string> _colorAbbreviations =
    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
      ["white"] = "W",
      ["blue"] = "U",
      ["black"] = "B",
      ["red"] = "R",
      ["green"] = "G",
    };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var body = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(body);
    if (!match.Success)
    {
      return null;
    }

    var color = _colorAbbreviations[match.Groups["color"].Value];
    var amount = int.Parse(match.Groups["amount"].Value);

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new MagicAST.AST.Effects.Replacement.ReplacementEffect
          {
            Event = new MagicAST.AST.Effects.Replacement.DamageEvent
            {
              // "a [color] source" — the damage source filtered by color (CR 615.2).
              Source = new ObjectFilter { Colors = [color] },
              // "to you" — the recipient is the ability's controller (a player).
              AffectedObjects = new ObjectFilter { Controller = ControllerFilter.You },
            },
            OriginalEventOccurs = false,
            // "prevent N of that damage" — bounded prevention of the watched event
            // (CR 615.10). Only Amount points are prevented; no color filter on the
            // prevention action itself (the color already scopes the watched event).
            Replacement = new MagicAST.AST.Effects.Damage.PreventDamageEffect
            {
              Amount = LiteralQuantity.Of(amount),
              Target = ObjectReference.You(),
            },
          },
        ],
      },
    ];
  }
}
