namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined multi-subtype anthem + keyword grant in the singular "Each creature …
/// that's" relative-clause form, with a TWO-subtype DISJUNCTION qualifier:
/// "Each creature you control that's a [Subtype1] or a [Subtype2] gets +N/+N and has
/// [keyword]." — Brenard, Ginger Sculptor: "Each creature you control that's a Food or
/// a Golem gets +2/+2 and has trample."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects (the MAST
/// multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+N) and a
/// <see cref="GainAbilityEffect"/> (the keyword), BOTH targeting the same
/// subtype-disjunction-filtered subject. One oracle clause generates one continuous
/// effect from one static ability, so the two effects share a single ability rather
/// than being split into two abilities (CR 611.3 — "A continuous effect may be
/// generated by the static ability of an object. Example: A permanent with the static
/// ability 'All white creatures get +1/+1' generates an effect that continuously gives
/// +1/+1 to each white creature on the battlefield.").
/// </para>
///
/// <para>
/// The "that's a [Subtype1] or a [Subtype2]" relative clause qualifies the "creature"
/// noun with a DISJUNCTION on <see cref="ObjectFilter.Subtypes"/> (OR semantics —
/// CR 205.3: a permanent has zero or more subtypes, so a creature qualifies by having
/// ANY one of the listed subtypes, not all of them): a Food that is not a Golem still
/// gets +2/+2. This mirrors the established multi-subtype-disjunction convention on
/// <see cref="MultiSubtypeAnthemModifyPTRule"/> (Kirri, Talented Sprout's "Plants and
/// Treefolk"). "You control" resolves to the source's controller (CR 109.5). No
/// "other" qualifier is present, so <see cref="ObjectFilter.ExcludeSelf"/> is left
/// unset (the source is a Human Artificer and never qualifies on its own subtypes, but
/// the rule text does not exclude it either).
/// </para>
///
/// <para>
/// The granted keyword is itself a static ability, modelled as a recursive
/// <see cref="GainAbilityEffect.GainedAbility"/> via the shared
/// <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping (Trample →
/// CR 702.19). No duration is carried — a static ability's continuous effect lasts as
/// long as the source remains on the battlefield.
/// </para>
///
/// <para>
/// Distinct from <see cref="TribalAnthemAndKeywordGrantRule"/> (the bare-plural
/// "[Subtype] you control get(s) +N/+N and have [keyword]" form, one subtype, plural
/// subject, no "creature"/"that's" relative clause) and from
/// <see cref="EachSupertypeCreatureAnthemModifyPTRule"/> ("Each [supertype] creature
/// you control gets +N/+N", supertype qualifier, no keyword grant, no disjunction).
/// ANCHORED (^…$) end to end on the singular "Each creature you control that's a X or a
/// Y gets … and has …" surface so it cannot claim a substring of a longer clause.
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class EachControlledMultiSubtypeAnthemAndKeywordRule : IStaticRule
{
  // "Each creature you control that's a <Sub1> or a <Sub2> gets +N/+N and has <keyword>."
  // Apostrophe in "that's"/"it's" is accepted as ASCII (') or curly (’). Both P/T sides
  // require an explicit '+' sign (anthems use signed notation). The keyword runs to
  // end-of-clause (letters and spaces only).
  private static readonly Regex _pattern = new(
    @"^\s*Each\s+creature\s+you\s+control\s+that['’]s\s+an?\s+(?<s1>[A-Z][A-Za-z]+)\s+or\s+an?\s+(?<s2>[A-Z][A-Za-z]+)\s+gets\s+\+(?<p>\d+)/\+(?<t>\d+)\s+and\s+has\s+(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var keyword = match.Groups["kw"].Value.Trim();
    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(keyword);
    if (grantedAbility is null)
    {
      // Recognised the compound shape but the keyword is not yet supported; decline so
      // the clause falls through to an honest fallback rather than emitting a partial buff.
      return null;
    }

    var subtypes = new List<string>
    {
      match.Groups["s1"].Value,
      match.Groups["s2"].Value,
    };
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    // Both effects share the same filtered subject. A fresh ObjectReference is built per
    // effect (records are immutable; the two filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Subtypes = subtypes,
        Controller = ControllerFilter.You,
      },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = grantedAbility,
          },
        ],
      },
    ];
  }
}
