namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// The bare supertype anthem in the "Each [supertype] creature you control gets
/// +N/+M." form (Mirror Box: "Each legendary creature you control gets +1/+1.").
/// Emits ONE <see cref="StaticAbility"/> carrying a single
/// <see cref="ModifyPTEffect"/> whose <c>Target</c> is the supertype-filtered
/// subject "[supertype] creatures you control" (<c>Kind=Each,
/// Filter={CardTypes:["creature"], Supertypes:[…], Controller:You}</c>).
///
/// <para>
/// CR 611.3 — "A continuous effect may be generated by the static ability of an
/// object": one oracle clause generates one continuous P/T effect from one static
/// ability. The subject's supertype qualifier (e.g. "legendary", CR 205.4a) is
/// recorded on <see cref="ObjectFilter.Supertypes"/>, NOT as a subtype or name: it
/// categorises the affected objects by supertype.
/// </para>
///
/// <para>
/// Distinct from <see cref="SupertypeAnthemAndKeywordGrantRule"/> (the "[Supertype]
/// creatures you control get +N/+N and have &lt;keyword&gt;." compound, plural
/// subject + keyword grant) and from <see cref="LordPTBuffRule"/> (which handles the
/// "Other/All &lt;filter&gt; get(s) +N/+M" shapes but recognises neither the leading
/// "Each" quantifier nor the supertype qualifier). ANCHORED (^…$) on the singular
/// "Each [supertype] creature you control gets" surface so it cannot claim a
/// substring of a longer clause (e.g. the "… gets +1/+1 for each …" same-name
/// anthem falls through to its own rule because the trailing text defeats the $
/// anchor here).
/// </para>
/// </summary>
[StaticRule(Priority = 974)]
public sealed class EachSupertypeCreatureAnthemModifyPTRule : IStaticRule
{
  private static readonly Regex _pattern = new(
    @"^\s*Each\s+(?<sup>[A-Za-z]+)\s+creature\s+you\s+control\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  // Printed-type-line supertypes (CR 205.4a) recognised as an anthem subject
  // qualifier. A capitalised-or-lowercase non-supertype adjective (a subtype such
  // as "Goblin", a state word such as "nontoken") is NOT matched here and falls
  // through to its own rule.
  private static readonly IReadOnlyDictionary<string, string> _supertypes =
    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
      ["legendary"] = "Legendary",
      ["snow"] = "Snow",
      ["basic"] = "Basic",
      ["world"] = "World",
    };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    if (!_supertypes.TryGetValue(match.Groups["sup"].Value, out var supertype))
    {
      return null;
    }

    var power = int.Parse(match.Groups["psign"].Value + match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["tsign"].Value + match.Groups["t"].Value);

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = new ObjectReference
            {
              Kind = ObjectReferenceKind.Each,
              Filter = new ObjectFilter
              {
                CardTypes = ["creature"],
                Supertypes = [supertype],
                Controller = ControllerFilter.You,
              },
            },
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
        ],
      },
    ];
  }
}
