namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// "Enchanted permanent gets +N/+M and has &lt;keyword&gt;." — the "permanent" wording
/// sibling of <see cref="EnchantedPTAndKeywordRule"/> ("Enchanted/Equipped CREATURE gets
/// ..."). Auras whose enchant restriction spans a card-type disjunction (e.g. "Enchant
/// creature or Vehicle") word the attached-P/T-and-keyword rider as "Enchanted PERMANENT"
/// rather than "Enchanted creature", since the attached object need not be a creature (a
/// Vehicle isn't one unless crewed — CR 301.7c). Anchored on the literal word "permanent"
/// so it never collides with the creature-worded sibling.
///
/// <para>
/// Canonical example: Silken Strength — "Enchant creature or Vehicle" ... "Enchanted
/// permanent gets +1/+2 and has reach."
/// </para>
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying a <see cref="CompositeEffect"/> of a
/// <see cref="ModifyPTEffect"/> (layer 7c — CR 613.4c) and a <see cref="GainAbilityEffect"/>
/// (layer 6 — CR 613.1f), both targeting <see cref="ObjectReferenceKind.EnchantedOrEquipped"/>.
/// One oracle clause generates one continuous effect from one static ability (CR 611.3 —
/// "A continuous effect may be generated by the static ability of an object.").
/// </para>
/// </summary>
[StaticRule(Priority = 966)]
public sealed class EnchantedPermanentPTAndKeywordRule : IStaticRule
{
  private static readonly Regex _pattern = new(
    @"^\s*Enchanted\s+permanent\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+and\s+has\s+(?<kw>[a-z][a-z ]+?)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    // Strip trailing parenthetical reminder text before matching (Rule 207.2 —
    // reminder text is not rules text), mirroring EnchantedPTAndKeywordRule.
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var psign = match.Groups["psign"].Value;
    var power = int.Parse(match.Groups["p"].Value);
    if (psign == "-") power = -power;

    var tsign = match.Groups["tsign"].Value;
    var toughness = int.Parse(match.Groups["t"].Value);
    if (tsign == "-") toughness = -toughness;

    var kw = match.Groups["kw"].Value.Trim();
    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(kw);
    if (grantedAbility is null)
    {
      // Unrecognised keyword — fall through so the fallback surfaces the gap.
      return null;
    }

    var target = new ObjectReference { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects = [new MagicAST.AST.Effects.Core.CompositeEffect
        {
          Effects =
          [
            new ModifyPTEffect
            {
              Target = target,
              PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
              ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
            },
            new GainAbilityEffect
            {
              Target = target,
              GainedAbility = grantedAbility,
            },
          ],
        }],
      },
    ];
  }
}
