namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Control;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined attached ability-strip + doesn't-untap rider:
/// "[Enchanted|Equipped] [type] loses all abilities and doesn't untap during
/// its controller's untap step." e.g. Stop Cold — "Enchanted permanent loses
/// all abilities and doesn't untap during its controller's untap step."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="LoseAbilityEffect"/>
/// (CR 613 — the ability-scope "all abilities" is recorded on the designed
/// free-text <see cref="LoseAbilityEffect.AbilityText"/> escape hatch, mirroring
/// the existing "all other abilities" usage, since it is a SCOPE rather than a
/// single named keyword) and a <see cref="DoesntUntapEffect"/> (CR 502.3 — a
/// continuous effect can keep a permanent from untapping during the untap
/// step), BOTH targeting the same attached subject "Enchanted/Equipped [type]".
/// One oracle clause generates one continuous effect from one static ability,
/// so the two effects share a single ability rather than being split into two
/// abilities (CR 611.3 — "A continuous effect may be generated by the static
/// ability of an object.").
/// </para>
///
/// <para>
/// Sibling of <see cref="AttachedModifyPTAndDoesntUntapRule"/> and
/// <see cref="AttachedModifyPTAndLosesKeywordRule"/> (same flat two-effects
/// compound-clause shape, different left-hand rider — here the left-hand
/// effect is a full ability strip rather than a P/T anthem). Distinct from
/// <see cref="DoesntUntapRule"/>'s bare enchanted/equipped "doesn't untap"
/// shape (no ability-loss rider).
/// </para>
///
/// <para>
/// CR 502.3 (verbatim): "Third, the active player determines which permanents
/// they control will untap. Then they untap them all simultaneously. This
/// turn-based action doesn't use the stack. Normally, all of a player's
/// permanents untap, but effects can keep one or more of a player's
/// permanents from untapping."
/// </para>
///
/// <para>
/// ANCHORED (^…$): the full oracle sentence is matched exactly so this rule
/// cannot fire on a substring of a more specific sibling clause. The
/// apostrophe class tolerates both the straight (U+0027) and curly (U+2019)
/// forms used across printings (matching the convention in
/// <see cref="DoesntUntapRule"/>).
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class EnchantedLosesAllAbilitiesAndDoesntUntapRule : IStaticRule
{
  // "[Enchanted|Equipped] [type] loses all abilities and doesn't untap during
  // its controller's untap step." The attached-object noun is generalized
  // (any single word) rather than hardcoded to "permanent", mirroring
  // DoesntUntapRule's enchanted/equipped form.
  private static readonly Regex _pattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+\w+\s+loses\s+all\s+abilities\s+and\s+doesn['’]?t\s+untap\s+during\s+its\s+controller['’]?s\s+untap\s+step\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    // A fresh ObjectReference is built per effect (records are immutable; the
    // two targets are value-equal).
    ObjectReference Subject() => new() { Kind = ObjectReferenceKind.EnchantedOrEquipped };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new LoseAbilityEffect
          {
            Target = Subject(),
            AbilityText = "all abilities",
          },
          new DoesntUntapEffect
          {
            Target = Subject(),
            WhoseUntapStep = "its controller's",
          },
        ],
      },
    ];
  }
}
