namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Parses "Equipped &lt;Subtype&gt;s you control have [keyword]." — Kor
/// Blademaster: "Equipped Warriors you control have double strike." — a static
/// continuous effect (CR 611.3 (verbatim): "A continuous effect may be
/// generated by the static ability of an object. Example: A permanent with
/// the static ability 'All white creatures get +1/+1' generates an effect
/// that continuously gives +1/+1 to each white creature on the battlefield.")
/// granting a keyword ability to every creature of the named subtype the
/// controller controls, further restricted to those currently carrying an
/// attached Equipment (CR 702.6).
///
/// <para>
/// A "state-qualified subtype anthem": the bare-plural subtype noun
/// ("Warriors") is prefixed by the "Equipped" state adjective rather than
/// immediately following "have". Sibling to
/// <see cref="TappedStateSubtypeCreaturesHaveKeywordRule"/> (which owns the
/// same shape for the "Tapped"/"Untapped" state words) and to
/// <see cref="SubtypeCreaturesHaveKeywordListRule"/>, which owns "&lt;Subtype&gt;
/// creatures you control have …" (literal "creature(s)" noun after the
/// subtype) and explicitly DECLINES "Equipped" as a captured subtype word (it
/// is a state, not a subtype — CR 205.3 does not list it as a creature type)
/// so it never shadows this rule. This rule requires the state word "Equipped"
/// to come FIRST, followed directly by the bare plural subtype noun (no
/// "creatures" word), so the two rules' anchored patterns are disjoint by
/// construction — neither is a substring match inside the other.
/// </para>
///
/// <para>
/// The equipped-state predicate is expressed as an
/// <see cref="EquippedStateCharacteristic"/> on the granted-to filter's
/// <see cref="ObjectFilter.Characteristics"/> (CR 702.6), the attachment-state
/// analogue of the tap-state <see cref="TappedStateCharacteristic"/> already
/// used by the sibling rule — MAST records only that the granted-to set is
/// scoped to that attachment state; whether any given permanent actually has
/// an Equipment attached is engine territory.
/// </para>
///
/// <para>
/// Double strike (CR 702.4) is resolved via the shared keyword map
/// (<c>StaticRuleHelpers.MapKeywordToStaticAbility</c>'s "double strike" arm)
/// — read, not modified, by this rule.
/// </para>
/// </summary>
[StaticRule]
public sealed class EquippedSubtypeCreaturesHaveKeywordRule : IStaticRule
{
  // "Equipped <Subtype>s you control have <kw>." — anchored end-to-end.
  // The state word "Equipped" MUST come first (distinguishing this from
  // SubtypeCreaturesHaveKeywordListRule's "<Subtype> creatures …" shape) and the
  // subtype MUST be a bare plural noun with no "creatures" word.
  private static readonly Regex _pattern = new(
    @"^\s*Equipped\s+(?<sub>[A-Z][a-z]+)s\s+you\s+control\s+have\s+" +
    @"(?<kw>[a-z][a-z ]*?)\.?\s*$",
    RegexOptions.Compiled
  );

  // Known irregular plural → singular mappings for MTG creature subtypes (mirrors
  // the small closed set TappedStateSubtypeCreaturesHaveKeywordRule already carries
  // for the same purpose; duplicated locally rather than shared since that rule's
  // table is private to its file and this rule must not edit that sibling body).
  private static readonly IReadOnlyDictionary<string, string> _irregularPlurals = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
  {
    ["Elves"] = "Elf",
    ["Wolves"] = "Wolf",
    ["Dwarves"] = "Dwarf",
    ["Mice"] = "Mouse",
  };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var pluralSubtype = match.Groups["sub"].Value + "s";
    var subtype = _irregularPlurals.TryGetValue(pluralSubtype, out var irregular)
      ? irregular
      : match.Groups["sub"].Value;

    var kw = match.Groups["kw"].Value.Trim().ToLowerInvariant();
    var granted = StaticRuleHelpers.MapKeywordToStaticAbility(kw);
    if (granted is null)
    {
      return null;
    }

    var filter = new ObjectFilter
    {
      CardTypes = ["creature"],
      Subtypes = [subtype],
      Controller = ControllerFilter.You,
      Characteristics = [new EquippedStateCharacteristic()],
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new GainAbilityEffect
          {
            Target = new ObjectReference { Kind = ObjectReferenceKind.Each, Filter = filter },
            GainedAbility = granted,
          },
        ],
      },
    ];
  }
}
