namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Parses "Equipped creatures you control have [keyword1][ and keyword2]." —
/// Dalakos, Crafter of Wonders: "Equipped creatures you control have flying and
/// haste." — a static continuous effect (CR 611.3 (verbatim): "A continuous
/// effect may be generated by the static ability of an object. Example: A
/// permanent with the static ability 'All white creatures get +1/+1' generates
/// an effect that continuously gives +1/+1 to each white creature on the
/// battlefield.") granting one or two keyword abilities to every creature the
/// controller controls that currently has an Equipment attached (CR 702.9
/// Flying / CR 702.10 Haste are both static abilities).
///
/// <para>
/// "Equipped" is a permanent STATE (CR 702.6: a creature with an Equipment
/// attached to it is "equipped"), NOT a creature subtype (CR 205.3 lists no such
/// subtype). <see cref="SubtypeCreaturesHaveKeywordListRule"/> explicitly declines
/// the capitalised word "Equipped" (alongside "Tapped"/"Enchanted"/"Modified" and
/// others) from its bare subject-capture group precisely so it never shadows this
/// rule — this rule is the sibling that owns that declined shape, mirroring how
/// <see cref="TappedStateSubtypeCreaturesHaveKeywordRule"/> owns the "Tapped
/// &lt;Subtype&gt;s …" shape declined by the same guard. The equipped-state
/// predicate is expressed as an <see cref="EquippedStateCharacteristic"/> on the
/// granted-to filter's <see cref="ObjectFilter.Characteristics"/> — the same
/// mechanism <see cref="TappedStateSubtypeCreaturesHaveKeywordRule"/> uses for
/// tapped/untapped, and distinct from <see cref="ObjectFilter.IsEquipped"/> (which
/// names the specific permanent a SOURCE Equipment is itself attached to, e.g.
/// "whenever equipped creature attacks" printed on an Equipment — Dalakos is a
/// creature, not an Equipment, so it has no such back-reference; it instead
/// quantifies over ANY creature carrying ANY Equipment). MAST describes the
/// printed predicate; the engine evaluates which creatures are actually equipped
/// (reference-not-resolution, ADR 0004).
/// </para>
///
/// <para>
/// No subtype qualifier — the bare "Equipped creatures you control" shape, unlike
/// a hypothetical "Equipped &lt;Subtype&gt;s you control" sibling. Filter:
/// <c>CardTypes=["creature"], Controller=You, Characteristics=[EquippedStateCharacteristic
/// {Equipped=true}]</c>.
/// </para>
///
/// <para>
/// Keyword list: one or two keywords, optionally joined by "and". Per the MAST
/// multi-effect-per-clause doctrine, a two-keyword grant is bundled into a single
/// <see cref="StaticAbility"/> whose <see cref="Ability.Effects"/> list carries two
/// independent <see cref="GainAbilityEffect"/> nodes — mirroring
/// <see cref="SubtypeCreaturesHaveKeywordListRule"/>'s and
/// <see cref="ControlledFilterHaveKeywordListRule"/>'s two-keyword grant shape.
/// Each keyword resolves through <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/>
/// (read, not modified, by this rule) — "flying" yields the CR 702.9 evasion effect,
/// "haste" the CR 702.10 keyword-ability effect.
/// </para>
///
/// <para>
/// Anchored (^…$) pattern with the case-sensitive literal "Equipped" lead-in, so
/// this rule cannot match any other subject shape and cannot be matched as a
/// substring inside a longer clause.
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class EquippedCreaturesHaveKeywordListRule : IStaticRule
{
  // "Equipped creatures you control have <kw1>[ and <kw2>]." — anchored end-to-end,
  // case-sensitive "Equipped" so it cannot match a lowercase mid-sentence occurrence.
  private static readonly Regex _pattern = new(
    @"^\s*Equipped\s+creatures?\s+you\s+control\s+have\s+" +
    @"(?<kw1>[a-z][a-z]*(?:\s+[a-z]+)*?)(?:\s+and\s+(?<kw2>[a-z][a-z ]+?))?\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var filter = new ObjectFilter
    {
      CardTypes = ["creature"],
      Controller = ControllerFilter.You,
      Characteristics = [new EquippedStateCharacteristic { Equipped = true }],
    };

    var kw1 = match.Groups["kw1"].Value.Trim().ToLowerInvariant();
    var granted1 = StaticRuleHelpers.MapKeywordToStaticAbility(kw1);
    if (granted1 is null)
    {
      return null;
    }

    var effects = new List<Effect>
    {
      new GainAbilityEffect
      {
        Target = new ObjectReference { Kind = ObjectReferenceKind.Each, Filter = filter },
        GainedAbility = granted1,
      },
    };

    if (match.Groups["kw2"].Success)
    {
      var kw2 = match.Groups["kw2"].Value.Trim().ToLowerInvariant();
      var granted2 = StaticRuleHelpers.MapKeywordToStaticAbility(kw2);
      if (granted2 is null)
      {
        // First keyword resolved but the second didn't — decline entirely so
        // the fallback surfaces the gap rather than emitting a partial grant.
        return null;
      }

      effects.Add(new GainAbilityEffect
      {
        Target = new ObjectReference { Kind = ObjectReferenceKind.Each, Filter = filter },
        GainedAbility = granted2,
      });
    }

    return [new StaticAbility { Effects = effects }];
  }
}
