namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// "(Enchanted|Equipped) creature gets +N/+M for each opponent you have." — an
/// attached P/T anthem scaled by the controller's opponent count (Blazing
/// Sunsteel: "Equipped creature gets +1/+0 for each opponent you have.").
///
/// <para>
/// Sibling of <see cref="EnchantedPTForEachRule"/> (which handles the "for each
/// &lt;filter&gt; you control" object-count shape); this rule is the disjoint
/// "for each opponent you have" player-count shape, so it does not go through
/// <see cref="StaticRuleHelpers.BuildObjectCountFilter"/> — "opponent" is a
/// player, not an <see cref="ObjectFilter"/>-matched object (CR 109 vs CR 102).
/// The amount is carried on the dedicated <see cref="OpponentCountQuantity"/>
/// node (reference-not-resolution, ADR 0004).
/// </para>
///
/// <para>
/// CR 611.3: "A continuous effect may be generated by the static ability of an
/// object. Such an effect is said to be 'generated by' that object's static
/// ability. ... A continuous effect generated this way lasts as long as the
/// permanent with the ability remains on the battlefield with the ability
/// ... unless the ability states otherwise." The attached-P/T anthem is such a
/// continuous effect, targeting the equipped/enchanted creature
/// (<see cref="ObjectReferenceKind.EnchantedOrEquipped"/>) for as long as the
/// Equipment/Aura remains attached and on the battlefield.
/// </para>
///
/// <para>
/// Only handles multiplier-1 increments — cards with a higher per-opponent
/// increment are a distinct shape and fall through to the fallback, mirroring
/// <see cref="EnchantedPTForEachRule"/>'s own multiplier-1 scope limit.
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class EquippedPTForEachOpponentRule : IStaticRule
{
  private static readonly Regex _pattern = new(
    @"^\s*(?:Enchanted|Equipped)\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+for\s+each\s+opponent\s+you\s+have\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var psign = match.Groups["psign"].Value;
    var p = int.Parse(match.Groups["p"].Value);
    var tsign = match.Groups["tsign"].Value;
    var t = int.Parse(match.Groups["t"].Value);

    var power = psign == "-" ? -p : p;
    var toughness = tsign == "-" ? -t : t;

    // Only handle multiplier-1 increments — cards with higher per-opponent
    // increments are a distinct shape and should fall through to the fallback.
    if (Math.Abs(power) > 1 || Math.Abs(toughness) > 1)
    {
      return null;
    }

    var opponentCount = new OpponentCountQuantity();

    MagicAST.AST.Quantities.Quantity powerModifier = power == 0
      ? LiteralQuantity.Of(0)
      : opponentCount;

    MagicAST.AST.Quantities.Quantity toughnessModifier = toughness == 0
      ? LiteralQuantity.Of(0)
      : opponentCount;

    return
    [
      new StaticAbility
      {
        Effects = [new ModifyPTEffect
        {
          Target = new ObjectReference { Kind = ObjectReferenceKind.EnchantedOrEquipped },
          PowerModifier = powerModifier,
          ToughnessModifier = toughnessModifier,
        }],
      },
    ];
  }
}
