namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// "Equipped creature gets +N/+M as long as [condition]." — a conditional
/// P/T modifier applied to the equipped creature. Paradigm card: KHM Toralf's Hammer —
/// "Equipped creature gets +3/+0 as long as it's legendary."
///
/// <para>
/// This is a <b>static</b> continuous effect with an <see cref="AsLongAsDuration"/>:
/// the P/T modification applies only while the stated condition holds (CR 611.2 —
/// "A continuous effect generated by a static ability has no defined end; it lasts as
/// long as the permanent with that ability remains on the battlefield and the condition
/// holds"). The condition is parsed by <see cref="MagicAST.Parsing.ConditionParser"/>;
/// conditions not yet structured emit an <see cref="OtherCondition"/> residual.
/// </para>
///
/// <para>
/// Emits a single <see cref="StaticAbility"/> with one <see cref="ModifyPTEffect"/>
/// targeting <see cref="ObjectReferenceKind.EnchantedOrEquipped"/> and an
/// <see cref="AsLongAsDuration"/> carrying the condition. Both the P (power) and T
/// (toughness) modifiers accept a '+'/'-' sign and a digit so "+3/+0" and "+0/+3"
/// round-trip correctly.
/// </para>
///
/// <para>
/// Priority 963 — below <see cref="EquippedCreatureHasQuotedAbilityRule"/> (964)
/// and below the existing "Equipped creature gets … and has …" compound rules (965-968)
/// so those more-specific forms are consumed first. Sits above the generic
/// <see cref="AsLongAsStaticGrantRule"/> (968) priority so it is tried before the
/// leading/suffix forms in that rule (which require "it/this creature" as the subject
/// rather than "Equipped creature").
/// </para>
/// </summary>
[StaticRule(Priority = 963)]
public sealed class EquippedPTAsLongAsConditionRule : IStaticRule
{
  // "Equipped creature gets +N/+M as long as [condition]."
  // Both P and T accept an explicit sign (+/-) followed by one or more digits.
  // The condition runs from "as long as " to end-of-clause (period stripped by the
  // suffix anchoring).
  private static readonly Regex _pattern = new(
    @"^\s*Equipped\s+creature\s+gets\s+(?<psign>[+\-])(?<p>\d+)/(?<tsign>[+\-])(?<t>\d+)\s+as\s+long\s+as\s+(?<cond>.+?)\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var psign = match.Groups["psign"].Value;
    var power = int.Parse(match.Groups["p"].Value);
    if (psign == "-") power = -power;

    var tsign = match.Groups["tsign"].Value;
    var toughness = int.Parse(match.Groups["t"].Value);
    if (tsign == "-") toughness = -toughness;

    var conditionText = match.Groups["cond"].Value.Trim();
    var duration = new AsLongAsDuration
    {
      Condition = MagicAST.Parsing.ConditionParser.Parse(conditionText),
    };

    return
    [
      new StaticAbility
      {
        Effects = [new ModifyPTEffect
        {
          Target = new ObjectReference { Kind = ObjectReferenceKind.EnchantedOrEquipped },
          PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
          ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          Duration = duration,
        }],
      },
    ];
  }
}
