namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Keyword;
using MagicAST.AST.References;
using MagicAST.Parsing;

/// <summary>
/// Parses "Instant and sorcery spells you control can't be countered." — a static
/// continuous effect (CR 611.3: the duration "you control" scopes a continuous effect
/// generated by a static ability) that grants uncounterability to every instant or
/// sorcery spell the controller casts. This is the Sphinx of the Final Word shape,
/// the type-disjunction sibling of <see cref="CreatureSpellsCantBeCounteredRule"/>
/// (creature spells) and Archwing Dragon-style "you control" scoping.
///
/// <para>
/// CR 113.6g (verbatim): "An object's ability that states it can't be countered or
/// can't be copied functions on the stack."
/// </para>
///
/// <para>
/// The affected objects are instant or sorcery spells on the stack controlled by the
/// source's controller. <c>CardTypes: ["instant", "sorcery"]</c> follows the
/// established MAST convention for the "instant and/or sorcery" type disjunction
/// (Rule 700.4) — no separate "spell" entry is needed since instant and sorcery
/// cards only ever exist as spells while eligible to be countered. The
/// <see cref="CantBeCounteredEffect"/> records the restriction; its presence on a
/// <see cref="StaticAbility"/> with <c>AffectedObjects</c> scoping to instant/sorcery
/// spells you control is the structured form of this lock.
/// </para>
///
/// <para>
/// Priority 972 — same tier as the sibling <see cref="CreatureSpellsCantBeCounteredRule"/>,
/// above <see cref="CantBeCastRestrictionRule"/> (971) and well above the generic
/// counter/spell rules (50–80 band). Anchored (^...$) to prevent substring matches
/// against other static lines.
/// </para>
/// </summary>
[StaticRule(Priority = 972)]
public sealed class InstantAndSorcerySpellsCantBeCounteredRule : IStaticRule
{
  // "Instant and sorcery spells you control can't be countered." — anchored at both ends.
  // Accepts the curly-apostrophe variant (can’t) as well as the ASCII form.
  private static readonly Regex _pattern = new(
    @"^\s*Instant\s+and\s+sorcery\s+spells\s+you\s+control\s+can’?'?t\s+be\s+countered\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    if (!_pattern.IsMatch(clause.RawText))
    {
      return null;
    }

    return
    [
      new StaticAbility
      {
        AffectedObjects = new ObjectFilter
        {
          CardTypes = ["instant", "sorcery"],
          Controller = ControllerFilter.You,
        },
        Effects = [new CantBeCounteredEffect()],
      },
    ];
  }
}
