namespace MagicAST.Parsing.Parsers.Static;

using System.Linq;
using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Multi-subtype tribal anthem, no "creatures" noun (the bare plural subtype
/// nouns themselves stand in for it, same convention as the single-subtype
/// sibling <see cref="TribalAnthemModifyPTRule"/>), with TWO OR MORE subtypes
/// joined by "and": "Other [Subtype1] and [Subtype2] you control get +N/+N."
/// Kirri, Talented Sprout: "Other Plants and Treefolk you control get +2/+0."
///
/// <para>
/// CR 611.3 — a continuous effect generated by a static ability. The listed
/// subtypes form a DISJUNCTION on <see cref="ObjectFilter.Subtypes"/> (OR
/// semantics — CR 205.3: a card/permanent has zero or more subtypes, so a
/// creature qualifies by having ANY one of the listed subtypes, not all of
/// them): a Plant that is not a Treefolk still gets +2/+0. This mirrors the
/// established multi-subtype-disjunction convention elsewhere in the corpus
/// (e.g. <see cref="MagicAST.Parsing.Parsers.Triggered.Rules.AddManaThenIfSecondTimeRevealUntilRule"/>'s
/// "an Elf or Elemental card" → <c>Subtypes: ["Elf","Elemental"]</c>).
/// </para>
///
/// <para>
/// The leading "Other " qualifier (CR 109.5 — "another") sets
/// <see cref="ObjectFilter.ExcludeSelf"/> = true so the source itself is
/// excluded from its own buff, matching <see cref="TribalAnthemModifyPTRule"/>'s
/// convention. "You control" resolves to the source's controller (CR 109.5).
/// </para>
///
/// <para>
/// Each subtype word is depluralised with a conservative trailing-"s" strip
/// (regular plurals like "Plants" → "Plant"); plural-invariant subtypes
/// (e.g. "Treefolk", mirroring "Merfolk"/"Sheep" noted on
/// <see cref="TribalAnthemAndKeywordGrantRule"/>) have no trailing "s" to
/// strip and pass through unchanged.
/// </para>
///
/// <para>
/// Distinct from <see cref="TribalAnthemModifyPTRule"/> (exactly ONE subtype,
/// REQUIRES the literal "creatures" word) and from <see cref="LordPTBuffRule"/>
/// (whose bare-plural-subtype branch only recognises a SINGLE trailing subtype
/// word, so it declines — and thus never collides with — this rule's two(+)-word
/// "and"-joined list). ANCHORED (^…$) end to end.
/// </para>
/// </summary>
[StaticRule(Priority = 970)]
public sealed class MultiSubtypeAnthemModifyPTRule : IStaticRule
{
  // "Other <Sub1>[, <Sub2>]* and <SubN> you control get +N/+N." — no "creatures"
  // word; two or more capitalised plural subtype nouns joined by "and" (with an
  // optional Oxford comma before it for 3+ members). Both P/T sides require an
  // explicit '+' sign (anthems use signed notation).
  private static readonly Regex _multiSubtypeAnthemPattern = new(
    @"^\s*Other\s+(?<subs>[A-Z][a-z]+(?:\s*,\s*[A-Z][a-z]+)*\s*,?\s*and\s+[A-Z][a-z]+)\s+(?<ctrl>you\s+control|an\s+opponent\s+controls)\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _multiSubtypeAnthemPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var subtypes = Regex
      .Split(match.Groups["subs"].Value.Trim(), @"\s*,\s*and\s+|\s*,\s*|\s+and\s+")
      .Where(s => s.Length > 0)
      .Select(Depluralize)
      .ToList();
    if (subtypes.Count < 2)
    {
      // Should always be 2+ given the pattern requires "and", but guard anyway
      // rather than emit a degenerate single-subtype filter.
      return null;
    }

    var ctrl = match.Groups["ctrl"].Value.ToLowerInvariant();
    var controller = ctrl.StartsWith("you")
      ? ControllerFilter.You
      : ControllerFilter.Opponent;
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    return
    [
      new StaticAbility
      {
        Effects = [new ModifyPTEffect
        {
          Target = new ObjectReference
          {
            Kind = ObjectReferenceKind.Each,
            Filter = new ObjectFilter
            {
              CardTypes = ["creature"],
              Subtypes = subtypes,
              Controller = controller,
              ExcludeSelf = true,
            },
          },
          PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
          ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
        }],
      },
    ];
  }

  // Strips a trailing plural "s" so the captured noun matches the printed card
  // subtype ("Plants" -> "Plant"). Plural-invariant subtypes (e.g. "Treefolk")
  // have no trailing "s" and pass through unchanged.
  private static string Depluralize(string noun) =>
    noun.Length > 1 && noun.EndsWith('s') ? noun[..^1] : noun;
}
