namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Quantities;
using MagicAST.AST.References;

/// <summary>
/// Opponent-controlled-source damage-prevention static ability (Heart-Shaped Herb):
/// "If a source an opponent controls would deal damage to you, prevent 1 of that
/// damage."
///
/// CR 615.10 (cited verbatim — its example is this exact template with N=1):
/// "Some prevention effects generated by static abilities refer to a specific
/// amount of damage — for example, \"If a source would deal damage to you, prevent
/// 1 of that damage.\" Such an effect prevents only the indicated amount of damage
/// in any applicable damage event at any given time. It will apply separately to
/// damage from other applicable events that would happen at the same time, or at a
/// different time."
///
/// CR 615.1: "Some continuous effects are prevention effects. Like replacement
/// effects (see rule 614), prevention effects apply continuously as events happen …
/// Such effects watch for a damage event that would happen and completely or
/// partially prevent the damage that would be dealt."
/// CR 615.1a: "Effects that use the word \"prevent\" are prevention effects."
/// CR 615.2: "Many prevention effects apply to damage from a source."
///
/// Structure mirrors <see cref="ColorSourceDamagePreventionStaticRule"/> (the "Sphere
/// of X" family, "If a red source would deal damage to you, prevent 2 …"): the only
/// difference is that the watched <c>DamageEvent.Source</c> is filtered by controller
/// (<c>Controller = Opponent</c>) rather than by color. A <c>StaticAbility</c> with a
/// <c>ReplacementEffect</c> that:
/// <list type="bullet">
///   <item>Watches for a <c>DamageEvent</c> whose <c>Source</c> is controlled by an
///   opponent (<c>Source.Controller = Opponent</c>) and whose recipient is you
///   (<c>AffectedObjects.Controller = You</c>).</item>
///   <item>Replaces the damage with a <c>PreventDamageEffect</c> that prevents a fixed
///   <c>Amount</c> of it (<c>LiteralQuantity.Of(N)</c>) from the affected player
///   (<c>Target = You</c>). Only <c>Amount</c> is prevented — the controller filter
///   lives on the watched event's source, not on the prevention action.</item>
/// </list>
///
/// ANCHORED (^...$): the full-line template "If a source an opponent controls would
/// deal damage to you, prevent [N] of that damage." is matched in its entirety, so it
/// cannot fire as a substring of a broader clause.
/// </summary>
[StaticRule(Priority = 965)]
public sealed class OpponentControlledSourceDamagePreventionStaticRule : IStaticRule
{
  // "If a source an opponent controls would deal damage to you, prevent [N] of that
  // damage." ANCHORED (^...$) to prevent substring matching inside broader clauses.
  private static readonly Regex _pattern = new(
    @"^\s*If\s+a\s+source\s+an\s+opponent\s+controls\s+would\s+deal\s+damage\s+to\s+you,\s*prevent\s+(?<amount>\d+)\s+of\s+that\s+damage\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var body = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(body);
    if (!match.Success)
    {
      return null;
    }

    var amount = int.Parse(match.Groups["amount"].Value);

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new MagicAST.AST.Effects.Replacement.ReplacementEffect
          {
            Event = new MagicAST.AST.Effects.Replacement.DamageEvent
            {
              // "a source an opponent controls" — the damage source filtered by
              // controller (CR 615.2).
              Source = new ObjectFilter { Controller = ControllerFilter.Opponent },
              // "to you" — the recipient is the ability's controller (a player).
              AffectedObjects = new ObjectFilter { Controller = ControllerFilter.You },
            },
            OriginalEventOccurs = false,
            // "prevent N of that damage" — bounded prevention of the watched event
            // (CR 615.10). Only Amount points are prevented; no controller filter on
            // the prevention action itself (the source scope already lives on the
            // watched event).
            Replacement = new MagicAST.AST.Effects.Damage.PreventDamageEffect
            {
              Amount = LiteralQuantity.Of(amount),
              Target = ObjectReference.You(),
            },
          },
        ],
      },
    ];
  }
}
