namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Parses "Instant and sorcery spells you control have [keyword]." — a static
/// continuous effect (CR 611.3: "A continuous effect may be generated by the static
/// ability of an object.") granting a keyword ability to a filtered class of the
/// controller's OWN spells while they sit on the stack (Soulfire Grand Master:
/// "Instant and sorcery spells you control have lifelink.").
///
/// <para>
/// <c>CardTypes = ["spell", "instant", "sorcery"]</c> is the established MAST
/// convention for the "instant and sorcery spell" type-disjunction on a stack
/// object: identical to the filter <see cref="MagicAST.Parsing.Parsers.Triggered.Rules.CastOrCopyInstantOrSorceryConditionRule"/>
/// and <see cref="MagicAST.Parsing.Parsers.Spell.Rules.NextCastCopySpellDelayedRule"/>
/// already emit for "an instant or sorcery spell", and parallel to
/// <see cref="CreatureSpellsCantBeCounteredRule"/>'s <c>["spell", "creature"]</c>
/// (a single type appended to the "spell" marker). "you control" is <c>Controller =
/// You</c> — CR 109.4 controller of an object on the stack.
/// </para>
///
/// <para>
/// Reuses <see cref="GainAbilityEffect"/> targeting an <c>Each</c>-kinded reference
/// over the spell filter, mirroring the "&lt;filter&gt; you control have [keyword]"
/// family (<see cref="ControlledFilterHaveKeywordListRule"/>,
/// <see cref="SubtypeTokensHaveKeywordRule"/>): the grant is CR 611.1's "continuous
/// effect [that] modifies characteristics of objects" for as long as this ability's
/// source remains on the battlefield (CR 604.2). Lifelink itself is CR 702.15a: "Lifelink
/// is a static ability."
/// </para>
///
/// <para>
/// Anchored (^…$) to the exact "Instant and sorcery spells you control have
/// [keyword]." surface, so it cannot fire as a substring of a broader clause or
/// collide with a sibling anthem over a different subject noun (permanents, tokens,
/// creatures). Priority 973 — same band as the sibling filter-scoped keyword-grant
/// rules (<see cref="ControlledFilterHaveKeywordListRule"/>), well above the
/// unfiltered <see cref="BareKeywordGrantRule"/> (967).
/// </para>
/// </summary>
[StaticRule(Priority = 973)]
public sealed class SpellTypeListHaveKeywordRule : IStaticRule
{
  // "Instant and sorcery spells you control have <kw1>[ and <kw2>]." kw1 is a
  // lazy word run so the optional " and <kw2>" tail can bind (mirrors
  // ControlledFilterHaveKeywordListRule's kw1/kw2 groups).
  private static readonly Regex _pattern = new(
    @"^\s*Instant\s+and\s+sorcery\s+spells\s+you\s+control\s+have\s+" +
    @"(?<kw1>[a-z][a-z]*(?:\s+[a-z]+)*?)(?:\s+and\s+(?<kw2>[a-z][a-z ]+?))?\.?\s*$",
    RegexOptions.IgnoreCase | RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var filter = new ObjectFilter
    {
      CardTypes = ["spell", "instant", "sorcery"],
      Controller = ControllerFilter.You,
    };
    var target = new ObjectReference { Kind = ObjectReferenceKind.Each, Filter = filter };

    var kw1 = match.Groups["kw1"].Value.Trim().ToLowerInvariant();
    var granted1 = StaticRuleHelpers.MapKeywordToStaticAbility(kw1);
    if (granted1 is null)
    {
      // Unrecognised keyword — decline so the fallback surfaces the gap rather
      // than emitting a partial grant.
      return null;
    }

    var effects = new List<Effect>
    {
      new GainAbilityEffect { Target = target, GainedAbility = granted1 },
    };

    if (match.Groups["kw2"].Success)
    {
      var kw2 = match.Groups["kw2"].Value.Trim().ToLowerInvariant();
      var granted2 = StaticRuleHelpers.MapKeywordToStaticAbility(kw2);
      if (granted2 is null)
      {
        return null;
      }

      effects.Add(new GainAbilityEffect { Target = target, GainedAbility = granted2 });
    }

    return [new StaticAbility { Effects = effects }];
  }
}
