namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined supertype anthem + keyword grant:
/// "[Supertype] creatures you control get +N/+N and have [keyword]."
/// e.g. Bloodsworn Steward — "Commander creatures you control get +2/+2 and have haste."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+N)
/// and a <see cref="GainAbilityEffect"/> (the keyword), BOTH targeting the same
/// supertype-filtered subject "[Supertype] creatures you control". One oracle clause
/// generates one continuous effect from one static ability, so the two effects share
/// a single ability rather than being split into two abilities (CR 611.3 — "A
/// continuous effect may be generated by the static ability of an object. Example: A
/// permanent with the static ability 'All white creatures get +1/+1' generates an
/// effect that continuously gives +1/+1 to each white creature on the battlefield.").
/// </para>
///
/// <para>
/// The subject's supertype qualifier (e.g. "Commander", CR 903 — a commander
/// designation that behaves as a supertype on the affected set) is recorded on
/// <see cref="ObjectFilter.Supertypes"/>, NOT as a name or subtype: it categorises the
/// affected objects rather than naming a specific card or its creature-type line.
/// </para>
///
/// <para>
/// The granted keyword is itself a static ability (e.g. CR 702.10a — "Haste is a static
/// ability."), modelled as a recursive <see cref="GainAbilityEffect.GainedAbility"/> via
/// the shared <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping. No
/// duration is carried — a static ability's continuous effect lasts for as long as the
/// source remains on the battlefield, not until a stated time.
/// </para>
///
/// <para>
/// Distinct from <see cref="AnthemModifyPTRule"/> (the bare anchor-target "Enchanted/
/// Equipped creature gets +N/+M." shape, no keyword grant and no supertype subject) and
/// from <see cref="TribalAnthemModifyPTRule"/> (the named-SUBTYPE anthem with no keyword
/// conjunction). This rule is the supertype-subject compound (pump AND keyword grant).
/// </para>
/// </summary>
[StaticRule(Priority = 971)]
public sealed class SupertypeAnthemAndKeywordGrantRule : IStaticRule
{
  // "[Supertype] creatures you control get +N/+N and have <keyword>."
  // <sup> is a single capitalised supertype word recognised by the oracle-subject
  // supertype vocabulary below. Both P/T sides require an explicit '+' sign (anthems
  // use signed notation). The keyword runs to end-of-clause (letters and spaces only).
  private static readonly Regex _supertypeAnthemKeywordPattern = new(
    @"^\s*(?<other>Other\s+)?(?<noun>[A-Z][a-z]+)\s+creatures\s+(?<ctrl>you\s+control|your\s+opponents\s+control)\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\s+and\s+have\s+(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.Compiled
  );

  // Supertypes that legitimately qualify the affected set in an oracle-subject anthem.
  // "Commander" is the commander designation (CR 903); the printed-type-line supertypes
  // (Legendary, Snow, Basic, World, Ongoing) round out the recognised vocabulary so a
  // capitalised non-supertype noun (a subtype like "Goblin") is NOT misclassified here —
  // those belong to TribalAnthemModifyPTRule's subtype shape.
  private static readonly HashSet<string> _oracleSubjectSupertypes =
    new(StringComparer.Ordinal)
    {
      "Commander",
      "Legendary",
      "Snow",
      "Basic",
      "World",
      "Ongoing",
    };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _supertypeAnthemKeywordPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    // The qualifying noun is either a recognised supertype (Commander/Legendary/…) → Supertypes
    // filter, or a creature subtype (Goblin, Vampire, …) → Subtypes filter. A leading "Other"
    // (CR 109.2) excludes the source object → ExcludeSelf. The subtype branch is the
    // keyword-conjunction sibling of TribalAnthemModifyPTRule (which handles the bare "[Subtype]
    // creatures get +N/+N" anthem with NO "and have <kw>" conjunction).
    var noun = match.Groups["noun"].Value;
    var isOther = match.Groups["other"].Success;
    var isSupertype = _oracleSubjectSupertypes.Contains(noun);

    var keyword = match.Groups["kw"].Value.Trim();
    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(keyword);
    if (grantedAbility is null)
    {
      // Recognised the compound shape but the keyword is not yet supported; decline so
      // the clause falls through to an honest fallback rather than emitting a partial buff.
      return null;
    }

    var ctrl = match.Groups["ctrl"].Value.ToLowerInvariant();
    var controller = ctrl.StartsWith("you")
      ? ControllerFilter.You
      : ControllerFilter.Opponent;
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    IReadOnlyList<string>? supertypes = isSupertype ? [noun] : null;
    IReadOnlyList<string>? subtypes = isSupertype ? null : [noun];

    // Both effects share the same filtered subject. A fresh ObjectReference is built per effect
    // (records are immutable; the two filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Supertypes = supertypes,
        Subtypes = subtypes,
        Controller = controller,
        ExcludeSelf = isOther ? true : (bool?)null,
      },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = grantedAbility,
          },
        ],
      },
    ];
  }
}
