namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined SUPERTYPE + SUBTYPE keyword-only grant, with the "creatures" noun
/// OMITTED because the bare plural subtype noun itself stands in for it (same
/// convention as <see cref="TribalAnthemAndKeywordGrantRule"/>): "[Supertype]
/// [Subtype-plural] you control have [keyword]." e.g. General's Enforcer —
/// "Legendary Humans you control have indestructible."
///
/// <para>
/// Unlike <see cref="SupertypeAnthemAndKeywordGrantRule"/> (which requires the
/// literal "creatures" noun AND a "get +N/+N and" P/T clause before the keyword
/// grant), this shape has NO P/T modification at all — the clause is a bare
/// keyword grant gated on BOTH a supertype and a subtype qualifier simultaneously
/// (CR 611.3: "A continuous effect may be generated by the static ability of an
/// object."). A creature must have BOTH the named supertype (CR 205.4a) AND the
/// named creature subtype (CR 205.3m) to qualify — <see cref="ObjectFilter"/>'s
/// <see cref="ObjectFilter.Supertypes"/> and <see cref="ObjectFilter.Subtypes"/>
/// axes are independent AND-ed filters on the same object, not a disjunction.
/// </para>
///
/// <para>
/// The recognised supertype vocabulary mirrors
/// <see cref="SupertypeAnthemAndKeywordGrantRule"/>'s closed set (Commander,
/// Legendary, Snow, Basic, World, Ongoing) so a capitalised non-supertype word
/// immediately preceding another capitalised word (e.g. an "Untapped Dragons"/
/// "Equipped Warriors" combat-/attachment-state qualifier, each owned by its own
/// sibling rule) is never misclassified as a supertype — it declines instead,
/// leaving those clauses to their owning rules.
/// </para>
///
/// <para>
/// The granted keyword is itself a static ability (CR 702.12b: "Indestructible is
/// a static ability."), modelled as a recursive
/// <see cref="GainAbilityEffect.GainedAbility"/> via the shared
/// <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping. No duration
/// is carried — a static ability's continuous effect lasts for as long as the
/// source remains on the battlefield (CR 611.3 example generalised to two filter
/// axes), not until a stated time.
/// </para>
///
/// <para>
/// Distinct from <see cref="TribalAnthemAndKeywordGrantRule"/> (subtype-only, but
/// REQUIRES a "get +N/+N and" P/T clause before "have") and from
/// <see cref="SubtypeCreaturesHaveKeywordListRule"/> (subtype-only, but REQUIRES
/// the literal "creatures" noun). This rule's two-capitalised-word subject with NO
/// "get ... and" P/T clause and NO "creatures" noun is a disjoint third shape.
/// Optional leading "Other " (CR 109.5 — "another") sets
/// <see cref="ObjectFilter.ExcludeSelf"/>, mirroring the sibling anthem rules.
/// Anchored (^…$) end to end so it can never match a substring of a longer clause.
/// </para>
/// </summary>
[StaticRule(Priority = 972)]
public sealed class SupertypeSubtypeKeywordGrantRule : IStaticRule
{
  // "[Other ][Supertype] [Subtype-plural] you control have <kw1>[ and <kw2>]." —
  // no "creatures" word, no P/T clause. Two capitalised words (supertype then
  // subtype) directly precede the controller clause.
  private static readonly Regex _pattern = new(
    @"^\s*(?<other>Other\s+)?(?<sup>[A-Z][a-z]+)\s+(?<sub>[A-Z][a-z]+)\s+you\s+control\s+have\s+" +
    @"(?<kw1>[a-z][a-z]*(?:\s+[a-z]+)*?)(?:\s+and\s+(?<kw2>[a-z][a-z ]+?))?\.?\s*$",
    RegexOptions.Compiled
  );

  // Closed supertype vocabulary — mirrors SupertypeAnthemAndKeywordGrantRule's
  // set. Anything outside this set (a combat-state or attachment-state adjective
  // like "Untapped"/"Equipped") is NOT a supertype, so the rule declines and lets
  // the owning sibling rule handle that clause.
  private static readonly HashSet<string> _oracleSubjectSupertypes =
    new(StringComparer.Ordinal)
    {
      "Commander",
      "Legendary",
      "Snow",
      "Basic",
      "World",
      "Ongoing",
    };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var supertype = match.Groups["sup"].Value;
    if (!_oracleSubjectSupertypes.Contains(supertype))
    {
      // Not a recognised supertype — decline so the owning sibling rule (see
      // class doc) handles this clause instead.
      return null;
    }

    var subtype = Depluralize(match.Groups["sub"].Value);
    var isOther = match.Groups["other"].Success;

    var kw1 = match.Groups["kw1"].Value.Trim().ToLowerInvariant();
    var granted1 = StaticRuleHelpers.MapKeywordToStaticAbility(kw1);
    if (granted1 is null)
    {
      // Recognised the compound shape but the keyword is not yet supported;
      // decline so the clause falls through to an honest fallback rather than
      // emitting a partial grant.
      return null;
    }

    // Both effects (if a second keyword is present) share the same filtered
    // subject. A fresh ObjectReference is built per effect (records are
    // immutable; the two filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Supertypes = [supertype],
        Subtypes = [subtype],
        Controller = ControllerFilter.You,
        ExcludeSelf = isOther ? true : (bool?)null,
      },
    };

    var effects = new List<MagicAST.AST.Effects.Effect>
    {
      new GainAbilityEffect { Target = Subject(), GainedAbility = granted1 },
    };

    if (match.Groups["kw2"].Success)
    {
      var kw2 = match.Groups["kw2"].Value.Trim().ToLowerInvariant();
      var granted2 = StaticRuleHelpers.MapKeywordToStaticAbility(kw2);
      if (granted2 is null)
      {
        // First keyword resolved but the second didn't — decline entirely so
        // the fallback surfaces the gap rather than emitting a partial grant.
        return null;
      }
      effects.Add(new GainAbilityEffect { Target = Subject(), GainedAbility = granted2 });
    }

    return [new StaticAbility { Effects = effects }];
  }

  // Strips a trailing plural "s" so the captured noun matches the printed card
  // subtype ("Humans" -> "Human"). Plural-invariant subtypes (e.g. "Merfolk")
  // have no trailing "s" and pass through unchanged.
  private static string Depluralize(string noun) =>
    noun.Length > 1 && noun.EndsWith('s') ? noun[..^1] : noun;
}
