namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Parses "&lt;Tapped|Untapped&gt; &lt;Subtype&gt;s you control have [keyword]." —
/// Dragonologist: "Untapped Dragons you control have hexproof." — a static
/// continuous effect (CR 611.3 (verbatim): "A continuous effect may be
/// generated by the static ability of an object. Example: A permanent with
/// the static ability 'All white creatures get +1/+1' generates an effect
/// that continuously gives +1/+1 to each white creature on the battlefield.")
/// granting a keyword ability to every creature of the named subtype the
/// controller controls, further restricted to those currently in the named
/// tap state (CR 701.26 / 110.5, per <see cref="TappedStateCharacteristic"/>'s
/// own established citation, reused below).
///
/// <para>
/// A "state-qualified subtype anthem": the bare-plural subtype noun
/// ("Dragons") is prefixed by a tapped/untapped state adjective rather than
/// immediately following "have". Sibling to
/// <see cref="SubtypeCreaturesHaveKeywordListRule"/>, which owns "&lt;Subtype&gt;
/// creatures you control have …" (literal "creature(s)" noun after the
/// subtype) and explicitly DECLINES "Tapped"/"Untapped" as a captured subtype
/// word (they are states, not subtypes — CR 205.3 lists neither as a creature
/// type) so it never shadows this rule. This rule instead requires the state
/// word to come FIRST, followed directly by the bare plural subtype noun (no
/// "creatures" word), so the two rules' anchored patterns are disjoint by
/// construction — neither is a substring match inside the other.
/// </para>
///
/// <para>
/// Also distinct from <see cref="BareKeywordGrantRule"/>'s "Other tapped/untapped
/// creatures you control have …" arm (<c>ParseLordPTFilter</c>'s bare
/// "tapped creature(s)"/"untapped creature(s)" shape, Saryth, the Viper's Fang):
/// that shape has NO subtype qualifier and REQUIRES the "Other " prefix. This
/// rule has NO "Other" prefix and REQUIRES a capitalised subtype noun
/// immediately after the state word, so the two anchored patterns cannot
/// double-match the same clause.
/// </para>
///
/// <para>
/// The tapped/untapped predicate is expressed as a
/// <see cref="TappedStateCharacteristic"/> on the granted-to filter's
/// <see cref="ObjectFilter.Characteristics"/> (CR 701.26 / 110.5, per that
/// node's own doc), the same node <see cref="BareKeywordGrantRule"/>'s Saryth
/// arm and
/// <see cref="MagicAST.Parsing.Parsers.Spell.Rules.AddManaForEachTappedLandOpponentsControlRule"/>
/// already use — MAST
/// records only that the granted-to set is scoped to that tap state; the
/// actual tap status of any given permanent is engine territory.
/// </para>
///
/// <para>
/// Hexproof (Rule 702.11, per the existing citation on
/// <c>StaticRuleHelpers.MapKeywordToStaticAbility</c>'s "hexproof" arm: "this
/// permanent can't be the target of spells or abilities opponents control")
/// is resolved via that shared keyword map — read, not modified, by this rule.
/// </para>
/// </summary>
[StaticRule]
public sealed class TappedStateSubtypeCreaturesHaveKeywordRule : IStaticRule
{
  // "<Tapped|Untapped> <Subtype>s you control have <kw>." — anchored end-to-end.
  // The state word MUST come first (distinguishing this from SubtypeCreaturesHaveKeywordListRule's
  // "<Subtype> creatures …" shape) and the subtype MUST be a bare plural noun with
  // no "creatures" word (distinguishing this from BareKeywordGrantRule's bare
  // "Other tapped/untapped creatures …" arm, which carries no subtype).
  private static readonly Regex _pattern = new(
    @"^\s*(?<state>Tapped|Untapped)\s+(?<sub>[A-Z][a-z]+)s\s+you\s+control\s+have\s+" +
    @"(?<kw>[a-z][a-z ]*?)\.?\s*$",
    RegexOptions.Compiled
  );

  // Known irregular plural → singular mappings for MTG creature subtypes (mirrors
  // the small closed set BareKeywordGrantRule already carries for the same purpose;
  // duplicated locally rather than shared since that method is private to its file
  // and this rule must not edit that shared multi-arm rule body).
  private static readonly IReadOnlyDictionary<string, string> _irregularPlurals = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
  {
    ["Elves"] = "Elf",
    ["Wolves"] = "Wolf",
    ["Dwarves"] = "Dwarf",
    ["Mice"] = "Mouse",
  };

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var rawText = StaticRuleHelpers.StripReminderText(clause.RawText);
    var match = _pattern.Match(rawText);
    if (!match.Success)
    {
      return null;
    }

    var state = match.Groups["state"].Value;
    var tapped = string.Equals(state, "Tapped", StringComparison.OrdinalIgnoreCase);

    var pluralSubtype = match.Groups["sub"].Value + "s";
    var subtype = _irregularPlurals.TryGetValue(pluralSubtype, out var irregular)
      ? irregular
      : match.Groups["sub"].Value;

    var kw = match.Groups["kw"].Value.Trim().ToLowerInvariant();
    var granted = StaticRuleHelpers.MapKeywordToStaticAbility(kw);
    if (granted is null)
    {
      return null;
    }

    var filter = new ObjectFilter
    {
      CardTypes = ["creature"],
      Subtypes = [subtype],
      Controller = ControllerFilter.You,
      Characteristics = [new TappedStateCharacteristic { Tapped = tapped }],
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new GainAbilityEffect
          {
            Target = new ObjectReference { Kind = ObjectReferenceKind.Each, Filter = filter },
            GainedAbility = granted,
          },
        ],
      },
    ];
  }
}
