namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined tribal (subtype) anthem + TWO-keyword grant, with the "creatures"
/// noun OMITTED because the bare plural subtype noun itself stands in for it:
/// "[Subtype-plural] you control get +N/+N and have [keyword1] and [keyword2]."
/// e.g. Hofri Ghostforge — "Spirits you control get +1/+1 and have trample and
/// haste."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying THREE effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+N)
/// and TWO <see cref="GainAbilityEffect"/>s (one per keyword), all targeting the
/// same subtype-filtered subject "[Subtype] you control". One oracle clause
/// generates one continuous effect from one static ability, so the effects share a
/// single ability rather than being split across several (CR 611.3 — "A continuous
/// effect may be generated by the static ability of an object. Example: A permanent
/// with the static ability 'All white creatures get +1/+1' generates an effect that
/// continuously gives +1/+1 to each white creature on the battlefield.").
/// </para>
///
/// <para>
/// The matched noun ALWAYS routes to <see cref="ObjectFilter.Subtypes"/> (a
/// creature subtype, e.g. "Spirit") — singularized from the grammatically plural
/// oracle noun ("Spirits" → "Spirit"), mirroring
/// <see cref="AttackingSubtypeAnthemAndKeywordGrantRule"/>'s local Singularize
/// helper. It means a permanent of that subtype on the battlefield (CR 109.2).
/// "You control" resolves to the source's controller (CR 109.5).
/// </para>
///
/// <para>
/// Each granted keyword is itself a static ability (e.g. Trample — CR 702.19;
/// Haste — CR 702.10), modelled as a recursive
/// <see cref="GainAbilityEffect.GainedAbility"/> via the shared
/// <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping. No duration is
/// carried — a static ability's continuous effect lasts for as long as the source
/// remains on the battlefield, not until a stated time.
/// </para>
///
/// <para>
/// Distinct from <see cref="TribalAnthemAndKeywordGrantRule"/> (the SAME bare-plural
/// subject shape but with exactly ONE keyword): that rule's non-greedy keyword group
/// would swallow "trample and haste" whole as a single unrecognised keyword string
/// and correctly decline (<see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/>
/// returns null for a multi-word phrase), falling through to this rule — so the two
/// never both succeed on the same clause. This rule REQUIRES the second " and
/// [keyword2]" clause (mandatory, not optional), keeping it disjoint from the
/// single-keyword sibling by construction. Also distinct from
/// <see cref="SubtypeCreaturesHaveKeywordListRule"/> (requires the "creatures" word)
/// and <see cref="AttackingSubtypeAnthemAndKeywordGrantRule"/> (requires the leading
/// "Attacking" qualifier, single keyword only).
/// </para>
/// </summary>
[StaticRule(Priority = 971)]
public sealed class TribalAnthemAndKeywordListGrantRule : IStaticRule
{
  // "[Subtype-plural] you control get +N/+N and have <kw1> and <kw2>." — no
  // "creatures" word between the subtype noun and the controller clause (the bare
  // plural subtype noun stands in for "[Subtype] creatures"). Both P/T sides
  // require an explicit '+' sign (anthems use signed notation). kw1 is a
  // non-greedy multi-word capture (mirrors SupertypeSubtypeKeywordGrantRule's
  // kw1/kw2 shape) so the mandatory " and " boundary correctly splits the two
  // keyword names; kw2 runs to end-of-clause.
  private static readonly Regex _pattern = new(
    @"^\s*(?<other>Other\s+)?(?<sub>[A-Z][a-z]+)\s+(?<ctrl>you\s+control|your\s+opponents\s+control)\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\s+and\s+have\s+(?<kw1>[a-z][a-z]*(?:\s+[a-z]+)*?)\s+and\s+(?<kw2>[a-z][a-z ]+?)\s*\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _pattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    // The captured noun is grammatically plural (unlike TribalAnthemAndKeywordGrantRule's
    // plural-invariant subtypes, e.g. Merfolk); singularize it to the printed card
    // subtype (Spirits -> Spirit). Conservative trailing-"s" strip, matching the
    // established AttackingSubtypeAnthemAndKeywordGrantRule.Singularize convention.
    var subtype = Singularize(match.Groups["sub"].Value);
    var isOther = match.Groups["other"].Success;

    var keyword1 = match.Groups["kw1"].Value.Trim();
    var granted1 = StaticRuleHelpers.MapKeywordToStaticAbility(keyword1);
    if (granted1 is null)
    {
      // Recognised the compound shape but the first keyword is not yet supported;
      // decline so the clause falls through to an honest fallback rather than
      // emitting a partial buff.
      return null;
    }

    var keyword2 = match.Groups["kw2"].Value.Trim();
    var granted2 = StaticRuleHelpers.MapKeywordToStaticAbility(keyword2);
    if (granted2 is null)
    {
      // First keyword resolved but the second didn't — decline entirely so the
      // fallback surfaces the gap rather than emitting a partial grant.
      return null;
    }

    var ctrl = match.Groups["ctrl"].Value.ToLowerInvariant();
    var controller = ctrl.StartsWith("you")
      ? ControllerFilter.You
      : ControllerFilter.Opponent;
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    // Every effect shares the same filtered subject. A fresh ObjectReference is built
    // per effect (records are immutable; the filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Subtypes = [subtype],
        Controller = controller,
        ExcludeSelf = isOther ? true : (bool?)null,
      },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = granted1,
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = granted2,
          },
        ],
      },
    ];
  }

  // Strips a trailing plural "s" so the captured noun matches the printed card
  // subtype ("Spirits" -> "Spirit"). Conservative: only a simple trailing "s",
  // local to this rule so it does not depend on shared StaticRuleHelpers internals.
  private static string Singularize(string noun) =>
    noun.Length > 1 && noun.EndsWith('s') ? noun[..^1] : noun;
}
