namespace MagicAST.Parsing.Parsers.Static;

using System.Text.RegularExpressions;
using MagicAST.AST.Abilities;
using MagicAST.AST.Effects.Modification;
using MagicAST.AST.References;

/// <summary>
/// Combined tribal (subtype) anthem + keyword grant, with the "creatures" noun
/// OMITTED because the subject subtype is plural-invariant in oracle text:
/// "Other [Subtype] you control get +N/+N and have [keyword]."
/// e.g. Mist Dancer — "Other Merfolk you control get +1/+0 and have flying."
///
/// <para>
/// Emits ONE <see cref="StaticAbility"/> carrying TWO effects in its list (the
/// MAST multi-effect-per-clause encoding): a <see cref="ModifyPTEffect"/> (+N/+N)
/// and a <see cref="GainAbilityEffect"/> (the keyword), BOTH targeting the same
/// subtype-filtered subject "[Subtype] you control". One oracle clause generates
/// one continuous effect from one static ability, so the two effects share a
/// single ability rather than being split into two abilities (CR 611.3 — "A
/// continuous effect may be generated by the static ability of an object. Example: A
/// permanent with the static ability 'All white creatures get +1/+1' generates an
/// effect that continuously gives +1/+1 to each white creature on the battlefield.").
/// </para>
///
/// <para>
/// The matched noun ALWAYS routes to <see cref="ObjectFilter.Subtypes"/> (a
/// creature subtype, e.g. "Merfolk"), never to Supertypes — this rule requires the
/// ABSENCE of the "creatures" word, which is what a subtype-only oracle subject
/// looks like when the subtype is plural-invariant. It means a Merfolk permanent
/// on the battlefield (CR 109.2 — "If a spell or ability uses a description of an
/// object that includes a card type or subtype, but doesn't refer to a specific
/// zone or include the word 'card,' 'spell,' 'source,' or 'scheme,' it means a
/// permanent of that card type or subtype on the battlefield."). "You control"
/// resolves to the source's controller (CR 109.5 — "The words 'you' and 'your' on
/// an object refer to the object's controller... For a static ability, this is the
/// current controller of the object it's on.").
/// </para>
///
/// <para>
/// The granted keyword is itself a static ability (e.g. Flying — "A keyword
/// ability that restricts how a creature may be blocked. See rule 702.9,
/// 'Flying.'"), modelled as a recursive <see cref="GainAbilityEffect.GainedAbility"/>
/// via the shared <see cref="StaticRuleHelpers.MapKeywordToStaticAbility"/> mapping.
/// No duration is carried — a static ability's continuous effect lasts for as long
/// as the source remains on the battlefield, not until a stated time.
/// </para>
///
/// <para>
/// Distinct from <see cref="SupertypeAnthemAndKeywordGrantRule"/> (the sibling
/// compound REQUIRING the "creatures" word — "[Supertype/Subtype] creatures you
/// control get +N/+N and have [keyword]"). The two patterns are disjoint: this
/// rule requires "creatures" to be ABSENT (noun directly followed by the controller
/// clause), so despite sharing a priority band, they never both match the same
/// clause. Also distinct from <see cref="TribalAnthemModifyPTRule"/> (the bare
/// tribal anthem with no keyword conjunction).
/// </para>
/// </summary>
[StaticRule(Priority = 971)]
public sealed class TribalAnthemAndKeywordGrantRule : IStaticRule
{
  // "Other <Subtype> you control get +N/+N and have <keyword>." — no "creatures"
  // word between the subtype noun and the controller clause (plural-invariant
  // subtypes like Merfolk and Sheep omit it in oracle text). Both P/T sides
  // require an explicit '+' sign (anthems use signed notation). The keyword runs
  // to end-of-clause (letters and spaces only).
  private static readonly Regex _tribalAnthemKeywordPattern = new(
    @"^\s*(?<other>Other\s+)?(?<sub>[A-Z][a-z]+)\s+(?<ctrl>you\s+control|your\s+opponents\s+control)\s+get\s+\+(?<p>\d+)/\+(?<t>\d+)\s+and\s+have\s+(?<kw>[A-Za-z][A-Za-z\s]*?)\s*\.?\s*$",
    RegexOptions.Compiled
  );

  public IReadOnlyList<Ability>? TryParse(OracleClause clause, ClauseClassification classification)
  {
    var match = _tribalAnthemKeywordPattern.Match(clause.RawText);
    if (!match.Success)
    {
      return null;
    }

    var subtype = match.Groups["sub"].Value;
    var isOther = match.Groups["other"].Success;

    var keyword = match.Groups["kw"].Value.Trim();
    var grantedAbility = StaticRuleHelpers.MapKeywordToStaticAbility(keyword);
    if (grantedAbility is null)
    {
      // Recognised the compound shape but the keyword is not yet supported; decline so
      // the clause falls through to an honest fallback rather than emitting a partial buff.
      return null;
    }

    var ctrl = match.Groups["ctrl"].Value.ToLowerInvariant();
    var controller = ctrl.StartsWith("you")
      ? ControllerFilter.You
      : ControllerFilter.Opponent;
    var power = int.Parse(match.Groups["p"].Value);
    var toughness = int.Parse(match.Groups["t"].Value);

    // Both effects share the same filtered subject. A fresh ObjectReference is built per effect
    // (records are immutable; the two filters are value-equal).
    ObjectReference Subject() => new()
    {
      Kind = ObjectReferenceKind.Each,
      Filter = new ObjectFilter
      {
        CardTypes = ["creature"],
        Subtypes = [subtype],
        Controller = controller,
        ExcludeSelf = isOther ? true : (bool?)null,
      },
    };

    return
    [
      new StaticAbility
      {
        Effects =
        [
          new ModifyPTEffect
          {
            Target = Subject(),
            PowerModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(power),
            ToughnessModifier = MagicAST.AST.Quantities.LiteralQuantity.Of(toughness),
          },
          new GainAbilityEffect
          {
            Target = Subject(),
            GainedAbility = grantedAbility,
          },
        ],
      },
    ];
  }
}
